name: 'Store Metadata Exporter'
description: 'Extract App Store Connect and Google Play metadata and write to a directory'
author: 'AdguardTeam'

branding:
  icon: 'download-cloud'
  color: 'blue'

inputs:
  # App Store Connect inputs (optional if using Google Play only)
  asc-issuer-id:
    description: 'App Store Connect Issuer ID'
    required: false
  asc-key-id:
    description: 'App Store Connect Key ID'
    required: false
  asc-private-key:
    description: 'App Store Connect private key content (.p8 file contents)'
    required: false

  # Google Play inputs (optional if using App Store Connect only)
  gp-service-account:
    description: 'Google Play service account JSON content'
    required: false
  gp-package-names:
    description: 'Google Play package names (comma-separated)'
    required: false
  gp-package-names-file:
    description: 'Path to file with Google Play package names (one per line). Default: gp-packages.txt'
    required: false

  # Common inputs
  output-dir:
    description: 'Output directory for metadata files'
    required: false
    default: '.'
  verbose:
    description: 'Enable verbose output'
    required: false
    default: 'false'

outputs:
  apps-count:
    description: 'Number of apps processed'
    value: ${{ steps.run.outputs.apps-count }}

runs:
  using: 'composite'
  steps:
    - name: Download store-metadata-exporter
      shell: bash
      run: |
        curl -sL -o "${{ github.action_path }}/store-metadata-exporter.jar" \
          "https://github.com/AdguardTeam/store-metadata-exporter/releases/latest/download/store-metadata-exporter.jar"

    - name: Run store-metadata-exporter
      id: run
      shell: bash
      env:
        ASC_ISSUER_ID: ${{ inputs.asc-issuer-id }}
        ASC_KEY_ID: ${{ inputs.asc-key-id }}
        ASC_PRIVATE_KEY: ${{ inputs.asc-private-key }}
        GP_SERVICE_ACCOUNT: ${{ inputs.gp-service-account }}
        GP_PACKAGE_NAMES: ${{ inputs.gp-package-names }}
        GP_PACKAGE_NAMES_FILE: ${{ inputs.gp-package-names-file }}
      run: |
        VERBOSE_FLAG=""
        if [[ "${{ inputs.verbose }}" == "true" ]]; then
          VERBOSE_FLAG="--verbose"
        fi

        OUTPUT=$(java -jar "${{ github.action_path }}/store-metadata-exporter.jar" \
          --output-dir="${{ inputs.output-dir }}" \
          $VERBOSE_FLAG 2>&1) || {
          echo "$OUTPUT"
          exit 1
        }

        echo "$OUTPUT"

        # Extract apps count from output
        APPS_COUNT=$(echo "$OUTPUT" | grep -oP 'Processed \K\d+(?= apps)' || echo "0")
        echo "apps-count=${APPS_COUNT}" >> $GITHUB_OUTPUT
