name: Sync Store Metadata

on:
  schedule:
    - cron: '0 6 * * *'  # Daily at 6:00 UTC
  workflow_dispatch:

jobs:
  sync:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Download store-metadata-exporter
        run: |
          curl -sL -o store-metadata-exporter.jar \
            "https://github.com/AdguardTeam/store-metadata-exporter/releases/latest/download/store-metadata-exporter.jar"

      - name: Run store-metadata-exporter
        env:
          # App Store Connect (optional)
          ASC_ISSUER_ID: ${{ secrets.ASC_ISSUER_ID }}
          ASC_KEY_ID: ${{ secrets.ASC_KEY_ID }}
          ASC_PRIVATE_KEY: ${{ secrets.ASC_PRIVATE_KEY }}
          # Google Play (optional)
          GP_SERVICE_ACCOUNT: ${{ secrets.GP_SERVICE_ACCOUNT }}
          GP_PACKAGE_NAMES: ${{ secrets.GP_PACKAGE_NAMES }}
        run: |
          java -jar store-metadata-exporter.jar --output-dir=. --verbose

      - name: Commit and push changes
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "github-actions[bot]@users.noreply.github.com"
          
          if [ -n "$(git status --porcelain)" ]; then
            git add -A
            git commit -m "Update store metadata $(date -u +'%Y-%m-%d %H:%M:%S UTC')"
            git push
            echo "Changes committed and pushed"
          else
            echo "No changes detected"
          fi
