/*
 * App Store Connect API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 4.2
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

package com.adguard.stores.appstoreconnect.api;

import com.adguard.stores.appstoreconnect.ApiClient;
import com.adguard.stores.appstoreconnect.ApiException;
import com.adguard.stores.appstoreconnect.ApiResponse;
import com.adguard.stores.appstoreconnect.Configuration;
import com.adguard.stores.appstoreconnect.Pair;

import com.adguard.stores.appstoreconnect.model.EndUserLicenseAgreementCreateRequest;
import com.adguard.stores.appstoreconnect.model.EndUserLicenseAgreementResponse;
import com.adguard.stores.appstoreconnect.model.EndUserLicenseAgreementTerritoriesLinkagesResponse;
import com.adguard.stores.appstoreconnect.model.EndUserLicenseAgreementUpdateRequest;
import com.adguard.stores.appstoreconnect.model.ErrorResponse;
import com.adguard.stores.appstoreconnect.model.TerritoriesWithoutIncludesResponse;

import com.fasterxml.jackson.core.type.TypeReference;
import com.fasterxml.jackson.databind.ObjectMapper;

import java.io.InputStream;
import java.io.ByteArrayInputStream;
import java.io.ByteArrayOutputStream;
import java.io.File;
import java.io.IOException;
import java.io.OutputStream;
import java.net.http.HttpRequest;
import java.nio.channels.Channels;
import java.nio.channels.Pipe;
import java.net.URI;
import java.net.http.HttpClient;
import java.net.http.HttpRequest;
import java.net.http.HttpResponse;
import java.time.Duration;

import java.util.ArrayList;
import java.util.StringJoiner;
import java.util.List;
import java.util.Map;
import java.util.Set;
import java.util.Locale;
import java.util.function.Consumer;

@jakarta.annotation.Generated(value = "org.openapitools.codegen.languages.JavaClientCodegen", comments = "Generator version: 7.17.0")
public class EndUserLicenseAgreementsApi {
  /**
   * Utility class for extending HttpRequest.Builder functionality.
   */
  private static class HttpRequestBuilderExtensions {
    /**
     * Adds additional headers to the provided HttpRequest.Builder. Useful for adding method/endpoint specific headers.
     *
     * @param builder the HttpRequest.Builder to which headers will be added
     * @param headers a map of header names and values to add; may be null
     * @return the same HttpRequest.Builder instance with the additional headers set
     */
    static HttpRequest.Builder withAdditionalHeaders(HttpRequest.Builder builder, Map<String, String> headers) {
        if (headers != null) {
            for (Map.Entry<String, String> entry : headers.entrySet()) {
                builder.header(entry.getKey(), entry.getValue());
            }
        }
        return builder;
    }
  }
  private final HttpClient memberVarHttpClient;
  private final ObjectMapper memberVarObjectMapper;
  private final String memberVarBaseUri;
  private final Consumer<HttpRequest.Builder> memberVarInterceptor;
  private final Duration memberVarReadTimeout;
  private final Consumer<HttpResponse<InputStream>> memberVarResponseInterceptor;
  private final Consumer<HttpResponse<String>> memberVarAsyncResponseInterceptor;

  public EndUserLicenseAgreementsApi() {
    this(Configuration.getDefaultApiClient());
  }

  public EndUserLicenseAgreementsApi(ApiClient apiClient) {
    memberVarHttpClient = apiClient.getHttpClient();
    memberVarObjectMapper = apiClient.getObjectMapper();
    memberVarBaseUri = apiClient.getBaseUri();
    memberVarInterceptor = apiClient.getRequestInterceptor();
    memberVarReadTimeout = apiClient.getReadTimeout();
    memberVarResponseInterceptor = apiClient.getResponseInterceptor();
    memberVarAsyncResponseInterceptor = apiClient.getAsyncResponseInterceptor();
  }


  protected ApiException getApiException(String operationId, HttpResponse<InputStream> response) throws IOException {
    String body = response.body() == null ? null : new String(response.body().readAllBytes());
    String message = formatExceptionMessage(operationId, response.statusCode(), body);
    return new ApiException(response.statusCode(), message, response.headers(), body);
  }

  private String formatExceptionMessage(String operationId, int statusCode, String body) {
    if (body == null || body.isEmpty()) {
      body = "[no body]";
    }
    return operationId + " call failed with: " + statusCode + " - " + body;
  }

  /**
   * Download file from the given response.
   *
   * @param response Response
   * @return File
   * @throws ApiException If fail to read file content from response and write to disk
   */
  public File downloadFileFromResponse(HttpResponse<InputStream> response) throws ApiException {
    try {
      File file = prepareDownloadFile(response);
      java.nio.file.Files.copy(response.body(), file.toPath(), java.nio.file.StandardCopyOption.REPLACE_EXISTING);
      return file;
    } catch (IOException e) {
      throw new ApiException(e);
    }
  }

  /**
   * <p>Prepare the file for download from the response.</p>
   *
   * @param response a {@link java.net.http.HttpResponse} object.
   * @return a {@link java.io.File} object.
   * @throws java.io.IOException if any.
   */
  private File prepareDownloadFile(HttpResponse<InputStream> response) throws IOException {
    String filename = null;
    java.util.Optional<String> contentDisposition = response.headers().firstValue("Content-Disposition");
    if (contentDisposition.isPresent() && !"".equals(contentDisposition.get())) {
      // Get filename from the Content-Disposition header.
      java.util.regex.Pattern pattern = java.util.regex.Pattern.compile("filename=['\"]?([^'\"\\s]+)['\"]?");
      java.util.regex.Matcher matcher = pattern.matcher(contentDisposition.get());
      if (matcher.find())
        filename = matcher.group(1);
    }
    File file = null;
    if (filename != null) {
      java.nio.file.Path tempDir = java.nio.file.Files.createTempDirectory("swagger-gen-native");
      java.nio.file.Path filePath = java.nio.file.Files.createFile(tempDir.resolve(filename));
      file = filePath.toFile();
      tempDir.toFile().deleteOnExit();   // best effort cleanup
      file.deleteOnExit(); // best effort cleanup
    } else {
      file = java.nio.file.Files.createTempFile("download-", "").toFile();
      file.deleteOnExit(); // best effort cleanup
    }
    return file;
  }

  /**
   * 
   * 
   * @param endUserLicenseAgreementCreateRequest EndUserLicenseAgreement representation (required)
   * @return EndUserLicenseAgreementResponse
   * @throws ApiException if fails to make API call
   */
  public EndUserLicenseAgreementResponse endUserLicenseAgreementsCreateInstance(@jakarta.annotation.Nonnull EndUserLicenseAgreementCreateRequest endUserLicenseAgreementCreateRequest) throws ApiException {
    return endUserLicenseAgreementsCreateInstance(endUserLicenseAgreementCreateRequest, null);
  }

  /**
   * 
   * 
   * @param endUserLicenseAgreementCreateRequest EndUserLicenseAgreement representation (required)
   * @param headers Optional headers to include in the request
   * @return EndUserLicenseAgreementResponse
   * @throws ApiException if fails to make API call
   */
  public EndUserLicenseAgreementResponse endUserLicenseAgreementsCreateInstance(@jakarta.annotation.Nonnull EndUserLicenseAgreementCreateRequest endUserLicenseAgreementCreateRequest, Map<String, String> headers) throws ApiException {
    ApiResponse<EndUserLicenseAgreementResponse> localVarResponse = endUserLicenseAgreementsCreateInstanceWithHttpInfo(endUserLicenseAgreementCreateRequest, headers);
    return localVarResponse.getData();
  }

  /**
   * 
   * 
   * @param endUserLicenseAgreementCreateRequest EndUserLicenseAgreement representation (required)
   * @return ApiResponse&lt;EndUserLicenseAgreementResponse&gt;
   * @throws ApiException if fails to make API call
   */
  public ApiResponse<EndUserLicenseAgreementResponse> endUserLicenseAgreementsCreateInstanceWithHttpInfo(@jakarta.annotation.Nonnull EndUserLicenseAgreementCreateRequest endUserLicenseAgreementCreateRequest) throws ApiException {
    return endUserLicenseAgreementsCreateInstanceWithHttpInfo(endUserLicenseAgreementCreateRequest, null);
  }

  /**
   * 
   * 
   * @param endUserLicenseAgreementCreateRequest EndUserLicenseAgreement representation (required)
   * @param headers Optional headers to include in the request
   * @return ApiResponse&lt;EndUserLicenseAgreementResponse&gt;
   * @throws ApiException if fails to make API call
   */
  public ApiResponse<EndUserLicenseAgreementResponse> endUserLicenseAgreementsCreateInstanceWithHttpInfo(@jakarta.annotation.Nonnull EndUserLicenseAgreementCreateRequest endUserLicenseAgreementCreateRequest, Map<String, String> headers) throws ApiException {
    HttpRequest.Builder localVarRequestBuilder = endUserLicenseAgreementsCreateInstanceRequestBuilder(endUserLicenseAgreementCreateRequest, headers);
    try {
      HttpResponse<InputStream> localVarResponse = memberVarHttpClient.send(
          localVarRequestBuilder.build(),
          HttpResponse.BodyHandlers.ofInputStream());
      if (memberVarResponseInterceptor != null) {
        memberVarResponseInterceptor.accept(localVarResponse);
      }
      try {
        if (localVarResponse.statusCode()/ 100 != 2) {
          throw getApiException("endUserLicenseAgreementsCreateInstance", localVarResponse);
        }
        if (localVarResponse.body() == null) {
          return new ApiResponse<EndUserLicenseAgreementResponse>(
              localVarResponse.statusCode(),
              localVarResponse.headers().map(),
              null
          );
        }

        
        
        String responseBody = new String(localVarResponse.body().readAllBytes());
        EndUserLicenseAgreementResponse responseValue = responseBody.isBlank()? null: memberVarObjectMapper.readValue(responseBody, new TypeReference<EndUserLicenseAgreementResponse>() {});
        
        localVarResponse.body().close();

        return new ApiResponse<EndUserLicenseAgreementResponse>(
            localVarResponse.statusCode(),
            localVarResponse.headers().map(),
            responseValue
        );
      } finally {
      }
    } catch (IOException e) {
      throw new ApiException(e);
    }
    catch (InterruptedException e) {
      Thread.currentThread().interrupt();
      throw new ApiException(e);
    }
  }

  private HttpRequest.Builder endUserLicenseAgreementsCreateInstanceRequestBuilder(@jakarta.annotation.Nonnull EndUserLicenseAgreementCreateRequest endUserLicenseAgreementCreateRequest, Map<String, String> headers) throws ApiException {
    // verify the required parameter 'endUserLicenseAgreementCreateRequest' is set
    if (endUserLicenseAgreementCreateRequest == null) {
      throw new ApiException(400, "Missing the required parameter 'endUserLicenseAgreementCreateRequest' when calling endUserLicenseAgreementsCreateInstance");
    }

    HttpRequest.Builder localVarRequestBuilder = HttpRequest.newBuilder();

    String localVarPath = "/v1/endUserLicenseAgreements";

    localVarRequestBuilder.uri(URI.create(memberVarBaseUri + localVarPath));

    localVarRequestBuilder.header("Content-Type", "application/json");
    localVarRequestBuilder.header("Accept", "application/json");

    try {
      byte[] localVarPostBody = memberVarObjectMapper.writeValueAsBytes(endUserLicenseAgreementCreateRequest);
      localVarRequestBuilder.method("POST", HttpRequest.BodyPublishers.ofByteArray(localVarPostBody));
    } catch (IOException e) {
      throw new ApiException(e);
    }
    if (memberVarReadTimeout != null) {
      localVarRequestBuilder.timeout(memberVarReadTimeout);
    }
    // Add custom headers if provided
    localVarRequestBuilder = HttpRequestBuilderExtensions.withAdditionalHeaders(localVarRequestBuilder, headers);
    if (memberVarInterceptor != null) {
      memberVarInterceptor.accept(localVarRequestBuilder);
    }
    return localVarRequestBuilder;
  }

  /**
   * 
   * 
   * @param id the id of the requested resource (required)
   * @throws ApiException if fails to make API call
   */
  public void endUserLicenseAgreementsDeleteInstance(@jakarta.annotation.Nonnull String id) throws ApiException {
    endUserLicenseAgreementsDeleteInstance(id, null);
  }

  /**
   * 
   * 
   * @param id the id of the requested resource (required)
   * @param headers Optional headers to include in the request
   * @throws ApiException if fails to make API call
   */
  public void endUserLicenseAgreementsDeleteInstance(@jakarta.annotation.Nonnull String id, Map<String, String> headers) throws ApiException {
    endUserLicenseAgreementsDeleteInstanceWithHttpInfo(id, headers);
  }

  /**
   * 
   * 
   * @param id the id of the requested resource (required)
   * @return ApiResponse&lt;Void&gt;
   * @throws ApiException if fails to make API call
   */
  public ApiResponse<Void> endUserLicenseAgreementsDeleteInstanceWithHttpInfo(@jakarta.annotation.Nonnull String id) throws ApiException {
    return endUserLicenseAgreementsDeleteInstanceWithHttpInfo(id, null);
  }

  /**
   * 
   * 
   * @param id the id of the requested resource (required)
   * @param headers Optional headers to include in the request
   * @return ApiResponse&lt;Void&gt;
   * @throws ApiException if fails to make API call
   */
  public ApiResponse<Void> endUserLicenseAgreementsDeleteInstanceWithHttpInfo(@jakarta.annotation.Nonnull String id, Map<String, String> headers) throws ApiException {
    HttpRequest.Builder localVarRequestBuilder = endUserLicenseAgreementsDeleteInstanceRequestBuilder(id, headers);
    try {
      HttpResponse<InputStream> localVarResponse = memberVarHttpClient.send(
          localVarRequestBuilder.build(),
          HttpResponse.BodyHandlers.ofInputStream());
      if (memberVarResponseInterceptor != null) {
        memberVarResponseInterceptor.accept(localVarResponse);
      }
      try {
        if (localVarResponse.statusCode()/ 100 != 2) {
          throw getApiException("endUserLicenseAgreementsDeleteInstance", localVarResponse);
        }
        return new ApiResponse<>(
            localVarResponse.statusCode(),
            localVarResponse.headers().map(),
            null
        );
      } finally {
        // Drain the InputStream
        while (localVarResponse.body().read() != -1) {
          // Ignore
        }
        localVarResponse.body().close();
      }
    } catch (IOException e) {
      throw new ApiException(e);
    }
    catch (InterruptedException e) {
      Thread.currentThread().interrupt();
      throw new ApiException(e);
    }
  }

  private HttpRequest.Builder endUserLicenseAgreementsDeleteInstanceRequestBuilder(@jakarta.annotation.Nonnull String id, Map<String, String> headers) throws ApiException {
    // verify the required parameter 'id' is set
    if (id == null) {
      throw new ApiException(400, "Missing the required parameter 'id' when calling endUserLicenseAgreementsDeleteInstance");
    }

    HttpRequest.Builder localVarRequestBuilder = HttpRequest.newBuilder();

    String localVarPath = "/v1/endUserLicenseAgreements/{id}"
        .replace("{id}", ApiClient.urlEncode(id.toString()));

    localVarRequestBuilder.uri(URI.create(memberVarBaseUri + localVarPath));

    localVarRequestBuilder.header("Accept", "application/json");

    localVarRequestBuilder.method("DELETE", HttpRequest.BodyPublishers.noBody());
    if (memberVarReadTimeout != null) {
      localVarRequestBuilder.timeout(memberVarReadTimeout);
    }
    // Add custom headers if provided
    localVarRequestBuilder = HttpRequestBuilderExtensions.withAdditionalHeaders(localVarRequestBuilder, headers);
    if (memberVarInterceptor != null) {
      memberVarInterceptor.accept(localVarRequestBuilder);
    }
    return localVarRequestBuilder;
  }

  /**
   * 
   * 
   * @param id the id of the requested resource (required)
   * @param fieldsEndUserLicenseAgreements the fields to include for returned resources of type endUserLicenseAgreements (optional)
   * @param fieldsTerritories the fields to include for returned resources of type territories (optional)
   * @param include comma-separated list of relationships to include (optional)
   * @param limitTerritories maximum number of related territories returned (when they are included) (optional)
   * @return EndUserLicenseAgreementResponse
   * @throws ApiException if fails to make API call
   */
  public EndUserLicenseAgreementResponse endUserLicenseAgreementsGetInstance(@jakarta.annotation.Nonnull String id, @jakarta.annotation.Nullable List<String> fieldsEndUserLicenseAgreements, @jakarta.annotation.Nullable List<String> fieldsTerritories, @jakarta.annotation.Nullable List<String> include, @jakarta.annotation.Nullable Integer limitTerritories) throws ApiException {
    return endUserLicenseAgreementsGetInstance(id, fieldsEndUserLicenseAgreements, fieldsTerritories, include, limitTerritories, null);
  }

  /**
   * 
   * 
   * @param id the id of the requested resource (required)
   * @param fieldsEndUserLicenseAgreements the fields to include for returned resources of type endUserLicenseAgreements (optional)
   * @param fieldsTerritories the fields to include for returned resources of type territories (optional)
   * @param include comma-separated list of relationships to include (optional)
   * @param limitTerritories maximum number of related territories returned (when they are included) (optional)
   * @param headers Optional headers to include in the request
   * @return EndUserLicenseAgreementResponse
   * @throws ApiException if fails to make API call
   */
  public EndUserLicenseAgreementResponse endUserLicenseAgreementsGetInstance(@jakarta.annotation.Nonnull String id, @jakarta.annotation.Nullable List<String> fieldsEndUserLicenseAgreements, @jakarta.annotation.Nullable List<String> fieldsTerritories, @jakarta.annotation.Nullable List<String> include, @jakarta.annotation.Nullable Integer limitTerritories, Map<String, String> headers) throws ApiException {
    ApiResponse<EndUserLicenseAgreementResponse> localVarResponse = endUserLicenseAgreementsGetInstanceWithHttpInfo(id, fieldsEndUserLicenseAgreements, fieldsTerritories, include, limitTerritories, headers);
    return localVarResponse.getData();
  }

  /**
   * 
   * 
   * @param id the id of the requested resource (required)
   * @param fieldsEndUserLicenseAgreements the fields to include for returned resources of type endUserLicenseAgreements (optional)
   * @param fieldsTerritories the fields to include for returned resources of type territories (optional)
   * @param include comma-separated list of relationships to include (optional)
   * @param limitTerritories maximum number of related territories returned (when they are included) (optional)
   * @return ApiResponse&lt;EndUserLicenseAgreementResponse&gt;
   * @throws ApiException if fails to make API call
   */
  public ApiResponse<EndUserLicenseAgreementResponse> endUserLicenseAgreementsGetInstanceWithHttpInfo(@jakarta.annotation.Nonnull String id, @jakarta.annotation.Nullable List<String> fieldsEndUserLicenseAgreements, @jakarta.annotation.Nullable List<String> fieldsTerritories, @jakarta.annotation.Nullable List<String> include, @jakarta.annotation.Nullable Integer limitTerritories) throws ApiException {
    return endUserLicenseAgreementsGetInstanceWithHttpInfo(id, fieldsEndUserLicenseAgreements, fieldsTerritories, include, limitTerritories, null);
  }

  /**
   * 
   * 
   * @param id the id of the requested resource (required)
   * @param fieldsEndUserLicenseAgreements the fields to include for returned resources of type endUserLicenseAgreements (optional)
   * @param fieldsTerritories the fields to include for returned resources of type territories (optional)
   * @param include comma-separated list of relationships to include (optional)
   * @param limitTerritories maximum number of related territories returned (when they are included) (optional)
   * @param headers Optional headers to include in the request
   * @return ApiResponse&lt;EndUserLicenseAgreementResponse&gt;
   * @throws ApiException if fails to make API call
   */
  public ApiResponse<EndUserLicenseAgreementResponse> endUserLicenseAgreementsGetInstanceWithHttpInfo(@jakarta.annotation.Nonnull String id, @jakarta.annotation.Nullable List<String> fieldsEndUserLicenseAgreements, @jakarta.annotation.Nullable List<String> fieldsTerritories, @jakarta.annotation.Nullable List<String> include, @jakarta.annotation.Nullable Integer limitTerritories, Map<String, String> headers) throws ApiException {
    HttpRequest.Builder localVarRequestBuilder = endUserLicenseAgreementsGetInstanceRequestBuilder(id, fieldsEndUserLicenseAgreements, fieldsTerritories, include, limitTerritories, headers);
    try {
      HttpResponse<InputStream> localVarResponse = memberVarHttpClient.send(
          localVarRequestBuilder.build(),
          HttpResponse.BodyHandlers.ofInputStream());
      if (memberVarResponseInterceptor != null) {
        memberVarResponseInterceptor.accept(localVarResponse);
      }
      try {
        if (localVarResponse.statusCode()/ 100 != 2) {
          throw getApiException("endUserLicenseAgreementsGetInstance", localVarResponse);
        }
        if (localVarResponse.body() == null) {
          return new ApiResponse<EndUserLicenseAgreementResponse>(
              localVarResponse.statusCode(),
              localVarResponse.headers().map(),
              null
          );
        }

        
        
        String responseBody = new String(localVarResponse.body().readAllBytes());
        EndUserLicenseAgreementResponse responseValue = responseBody.isBlank()? null: memberVarObjectMapper.readValue(responseBody, new TypeReference<EndUserLicenseAgreementResponse>() {});
        
        localVarResponse.body().close();

        return new ApiResponse<EndUserLicenseAgreementResponse>(
            localVarResponse.statusCode(),
            localVarResponse.headers().map(),
            responseValue
        );
      } finally {
      }
    } catch (IOException e) {
      throw new ApiException(e);
    }
    catch (InterruptedException e) {
      Thread.currentThread().interrupt();
      throw new ApiException(e);
    }
  }

  private HttpRequest.Builder endUserLicenseAgreementsGetInstanceRequestBuilder(@jakarta.annotation.Nonnull String id, @jakarta.annotation.Nullable List<String> fieldsEndUserLicenseAgreements, @jakarta.annotation.Nullable List<String> fieldsTerritories, @jakarta.annotation.Nullable List<String> include, @jakarta.annotation.Nullable Integer limitTerritories, Map<String, String> headers) throws ApiException {
    // verify the required parameter 'id' is set
    if (id == null) {
      throw new ApiException(400, "Missing the required parameter 'id' when calling endUserLicenseAgreementsGetInstance");
    }

    HttpRequest.Builder localVarRequestBuilder = HttpRequest.newBuilder();

    String localVarPath = "/v1/endUserLicenseAgreements/{id}"
        .replace("{id}", ApiClient.urlEncode(id.toString()));

    List<Pair> localVarQueryParams = new ArrayList<>();
    StringJoiner localVarQueryStringJoiner = new StringJoiner("&");
    String localVarQueryParameterBaseName;
    localVarQueryParameterBaseName = "fields[endUserLicenseAgreements]";
    localVarQueryParams.addAll(ApiClient.parameterToPairs("csv", "fields[endUserLicenseAgreements]", fieldsEndUserLicenseAgreements));
    localVarQueryParameterBaseName = "fields[territories]";
    localVarQueryParams.addAll(ApiClient.parameterToPairs("csv", "fields[territories]", fieldsTerritories));
    localVarQueryParameterBaseName = "include";
    localVarQueryParams.addAll(ApiClient.parameterToPairs("csv", "include", include));
    localVarQueryParameterBaseName = "limit[territories]";
    localVarQueryParams.addAll(ApiClient.parameterToPairs("limit[territories]", limitTerritories));

    if (!localVarQueryParams.isEmpty() || localVarQueryStringJoiner.length() != 0) {
      StringJoiner queryJoiner = new StringJoiner("&");
      localVarQueryParams.forEach(p -> queryJoiner.add(p.getName() + '=' + p.getValue()));
      if (localVarQueryStringJoiner.length() != 0) {
        queryJoiner.add(localVarQueryStringJoiner.toString());
      }
      localVarRequestBuilder.uri(URI.create(memberVarBaseUri + localVarPath + '?' + queryJoiner.toString()));
    } else {
      localVarRequestBuilder.uri(URI.create(memberVarBaseUri + localVarPath));
    }

    localVarRequestBuilder.header("Accept", "application/json");

    localVarRequestBuilder.method("GET", HttpRequest.BodyPublishers.noBody());
    if (memberVarReadTimeout != null) {
      localVarRequestBuilder.timeout(memberVarReadTimeout);
    }
    // Add custom headers if provided
    localVarRequestBuilder = HttpRequestBuilderExtensions.withAdditionalHeaders(localVarRequestBuilder, headers);
    if (memberVarInterceptor != null) {
      memberVarInterceptor.accept(localVarRequestBuilder);
    }
    return localVarRequestBuilder;
  }

  /**
   * 
   * 
   * @param id the id of the requested resource (required)
   * @param fieldsTerritories the fields to include for returned resources of type territories (optional)
   * @param limit maximum resources per page (optional)
   * @return TerritoriesWithoutIncludesResponse
   * @throws ApiException if fails to make API call
   */
  public TerritoriesWithoutIncludesResponse endUserLicenseAgreementsTerritoriesGetToManyRelated(@jakarta.annotation.Nonnull String id, @jakarta.annotation.Nullable List<String> fieldsTerritories, @jakarta.annotation.Nullable Integer limit) throws ApiException {
    return endUserLicenseAgreementsTerritoriesGetToManyRelated(id, fieldsTerritories, limit, null);
  }

  /**
   * 
   * 
   * @param id the id of the requested resource (required)
   * @param fieldsTerritories the fields to include for returned resources of type territories (optional)
   * @param limit maximum resources per page (optional)
   * @param headers Optional headers to include in the request
   * @return TerritoriesWithoutIncludesResponse
   * @throws ApiException if fails to make API call
   */
  public TerritoriesWithoutIncludesResponse endUserLicenseAgreementsTerritoriesGetToManyRelated(@jakarta.annotation.Nonnull String id, @jakarta.annotation.Nullable List<String> fieldsTerritories, @jakarta.annotation.Nullable Integer limit, Map<String, String> headers) throws ApiException {
    ApiResponse<TerritoriesWithoutIncludesResponse> localVarResponse = endUserLicenseAgreementsTerritoriesGetToManyRelatedWithHttpInfo(id, fieldsTerritories, limit, headers);
    return localVarResponse.getData();
  }

  /**
   * 
   * 
   * @param id the id of the requested resource (required)
   * @param fieldsTerritories the fields to include for returned resources of type territories (optional)
   * @param limit maximum resources per page (optional)
   * @return ApiResponse&lt;TerritoriesWithoutIncludesResponse&gt;
   * @throws ApiException if fails to make API call
   */
  public ApiResponse<TerritoriesWithoutIncludesResponse> endUserLicenseAgreementsTerritoriesGetToManyRelatedWithHttpInfo(@jakarta.annotation.Nonnull String id, @jakarta.annotation.Nullable List<String> fieldsTerritories, @jakarta.annotation.Nullable Integer limit) throws ApiException {
    return endUserLicenseAgreementsTerritoriesGetToManyRelatedWithHttpInfo(id, fieldsTerritories, limit, null);
  }

  /**
   * 
   * 
   * @param id the id of the requested resource (required)
   * @param fieldsTerritories the fields to include for returned resources of type territories (optional)
   * @param limit maximum resources per page (optional)
   * @param headers Optional headers to include in the request
   * @return ApiResponse&lt;TerritoriesWithoutIncludesResponse&gt;
   * @throws ApiException if fails to make API call
   */
  public ApiResponse<TerritoriesWithoutIncludesResponse> endUserLicenseAgreementsTerritoriesGetToManyRelatedWithHttpInfo(@jakarta.annotation.Nonnull String id, @jakarta.annotation.Nullable List<String> fieldsTerritories, @jakarta.annotation.Nullable Integer limit, Map<String, String> headers) throws ApiException {
    HttpRequest.Builder localVarRequestBuilder = endUserLicenseAgreementsTerritoriesGetToManyRelatedRequestBuilder(id, fieldsTerritories, limit, headers);
    try {
      HttpResponse<InputStream> localVarResponse = memberVarHttpClient.send(
          localVarRequestBuilder.build(),
          HttpResponse.BodyHandlers.ofInputStream());
      if (memberVarResponseInterceptor != null) {
        memberVarResponseInterceptor.accept(localVarResponse);
      }
      try {
        if (localVarResponse.statusCode()/ 100 != 2) {
          throw getApiException("endUserLicenseAgreementsTerritoriesGetToManyRelated", localVarResponse);
        }
        if (localVarResponse.body() == null) {
          return new ApiResponse<TerritoriesWithoutIncludesResponse>(
              localVarResponse.statusCode(),
              localVarResponse.headers().map(),
              null
          );
        }

        
        
        String responseBody = new String(localVarResponse.body().readAllBytes());
        TerritoriesWithoutIncludesResponse responseValue = responseBody.isBlank()? null: memberVarObjectMapper.readValue(responseBody, new TypeReference<TerritoriesWithoutIncludesResponse>() {});
        
        localVarResponse.body().close();

        return new ApiResponse<TerritoriesWithoutIncludesResponse>(
            localVarResponse.statusCode(),
            localVarResponse.headers().map(),
            responseValue
        );
      } finally {
      }
    } catch (IOException e) {
      throw new ApiException(e);
    }
    catch (InterruptedException e) {
      Thread.currentThread().interrupt();
      throw new ApiException(e);
    }
  }

  private HttpRequest.Builder endUserLicenseAgreementsTerritoriesGetToManyRelatedRequestBuilder(@jakarta.annotation.Nonnull String id, @jakarta.annotation.Nullable List<String> fieldsTerritories, @jakarta.annotation.Nullable Integer limit, Map<String, String> headers) throws ApiException {
    // verify the required parameter 'id' is set
    if (id == null) {
      throw new ApiException(400, "Missing the required parameter 'id' when calling endUserLicenseAgreementsTerritoriesGetToManyRelated");
    }

    HttpRequest.Builder localVarRequestBuilder = HttpRequest.newBuilder();

    String localVarPath = "/v1/endUserLicenseAgreements/{id}/territories"
        .replace("{id}", ApiClient.urlEncode(id.toString()));

    List<Pair> localVarQueryParams = new ArrayList<>();
    StringJoiner localVarQueryStringJoiner = new StringJoiner("&");
    String localVarQueryParameterBaseName;
    localVarQueryParameterBaseName = "fields[territories]";
    localVarQueryParams.addAll(ApiClient.parameterToPairs("csv", "fields[territories]", fieldsTerritories));
    localVarQueryParameterBaseName = "limit";
    localVarQueryParams.addAll(ApiClient.parameterToPairs("limit", limit));

    if (!localVarQueryParams.isEmpty() || localVarQueryStringJoiner.length() != 0) {
      StringJoiner queryJoiner = new StringJoiner("&");
      localVarQueryParams.forEach(p -> queryJoiner.add(p.getName() + '=' + p.getValue()));
      if (localVarQueryStringJoiner.length() != 0) {
        queryJoiner.add(localVarQueryStringJoiner.toString());
      }
      localVarRequestBuilder.uri(URI.create(memberVarBaseUri + localVarPath + '?' + queryJoiner.toString()));
    } else {
      localVarRequestBuilder.uri(URI.create(memberVarBaseUri + localVarPath));
    }

    localVarRequestBuilder.header("Accept", "application/json");

    localVarRequestBuilder.method("GET", HttpRequest.BodyPublishers.noBody());
    if (memberVarReadTimeout != null) {
      localVarRequestBuilder.timeout(memberVarReadTimeout);
    }
    // Add custom headers if provided
    localVarRequestBuilder = HttpRequestBuilderExtensions.withAdditionalHeaders(localVarRequestBuilder, headers);
    if (memberVarInterceptor != null) {
      memberVarInterceptor.accept(localVarRequestBuilder);
    }
    return localVarRequestBuilder;
  }

  /**
   * 
   * 
   * @param id the id of the requested resource (required)
   * @param limit maximum resources per page (optional)
   * @return EndUserLicenseAgreementTerritoriesLinkagesResponse
   * @throws ApiException if fails to make API call
   */
  public EndUserLicenseAgreementTerritoriesLinkagesResponse endUserLicenseAgreementsTerritoriesGetToManyRelationship(@jakarta.annotation.Nonnull String id, @jakarta.annotation.Nullable Integer limit) throws ApiException {
    return endUserLicenseAgreementsTerritoriesGetToManyRelationship(id, limit, null);
  }

  /**
   * 
   * 
   * @param id the id of the requested resource (required)
   * @param limit maximum resources per page (optional)
   * @param headers Optional headers to include in the request
   * @return EndUserLicenseAgreementTerritoriesLinkagesResponse
   * @throws ApiException if fails to make API call
   */
  public EndUserLicenseAgreementTerritoriesLinkagesResponse endUserLicenseAgreementsTerritoriesGetToManyRelationship(@jakarta.annotation.Nonnull String id, @jakarta.annotation.Nullable Integer limit, Map<String, String> headers) throws ApiException {
    ApiResponse<EndUserLicenseAgreementTerritoriesLinkagesResponse> localVarResponse = endUserLicenseAgreementsTerritoriesGetToManyRelationshipWithHttpInfo(id, limit, headers);
    return localVarResponse.getData();
  }

  /**
   * 
   * 
   * @param id the id of the requested resource (required)
   * @param limit maximum resources per page (optional)
   * @return ApiResponse&lt;EndUserLicenseAgreementTerritoriesLinkagesResponse&gt;
   * @throws ApiException if fails to make API call
   */
  public ApiResponse<EndUserLicenseAgreementTerritoriesLinkagesResponse> endUserLicenseAgreementsTerritoriesGetToManyRelationshipWithHttpInfo(@jakarta.annotation.Nonnull String id, @jakarta.annotation.Nullable Integer limit) throws ApiException {
    return endUserLicenseAgreementsTerritoriesGetToManyRelationshipWithHttpInfo(id, limit, null);
  }

  /**
   * 
   * 
   * @param id the id of the requested resource (required)
   * @param limit maximum resources per page (optional)
   * @param headers Optional headers to include in the request
   * @return ApiResponse&lt;EndUserLicenseAgreementTerritoriesLinkagesResponse&gt;
   * @throws ApiException if fails to make API call
   */
  public ApiResponse<EndUserLicenseAgreementTerritoriesLinkagesResponse> endUserLicenseAgreementsTerritoriesGetToManyRelationshipWithHttpInfo(@jakarta.annotation.Nonnull String id, @jakarta.annotation.Nullable Integer limit, Map<String, String> headers) throws ApiException {
    HttpRequest.Builder localVarRequestBuilder = endUserLicenseAgreementsTerritoriesGetToManyRelationshipRequestBuilder(id, limit, headers);
    try {
      HttpResponse<InputStream> localVarResponse = memberVarHttpClient.send(
          localVarRequestBuilder.build(),
          HttpResponse.BodyHandlers.ofInputStream());
      if (memberVarResponseInterceptor != null) {
        memberVarResponseInterceptor.accept(localVarResponse);
      }
      try {
        if (localVarResponse.statusCode()/ 100 != 2) {
          throw getApiException("endUserLicenseAgreementsTerritoriesGetToManyRelationship", localVarResponse);
        }
        if (localVarResponse.body() == null) {
          return new ApiResponse<EndUserLicenseAgreementTerritoriesLinkagesResponse>(
              localVarResponse.statusCode(),
              localVarResponse.headers().map(),
              null
          );
        }

        
        
        String responseBody = new String(localVarResponse.body().readAllBytes());
        EndUserLicenseAgreementTerritoriesLinkagesResponse responseValue = responseBody.isBlank()? null: memberVarObjectMapper.readValue(responseBody, new TypeReference<EndUserLicenseAgreementTerritoriesLinkagesResponse>() {});
        
        localVarResponse.body().close();

        return new ApiResponse<EndUserLicenseAgreementTerritoriesLinkagesResponse>(
            localVarResponse.statusCode(),
            localVarResponse.headers().map(),
            responseValue
        );
      } finally {
      }
    } catch (IOException e) {
      throw new ApiException(e);
    }
    catch (InterruptedException e) {
      Thread.currentThread().interrupt();
      throw new ApiException(e);
    }
  }

  private HttpRequest.Builder endUserLicenseAgreementsTerritoriesGetToManyRelationshipRequestBuilder(@jakarta.annotation.Nonnull String id, @jakarta.annotation.Nullable Integer limit, Map<String, String> headers) throws ApiException {
    // verify the required parameter 'id' is set
    if (id == null) {
      throw new ApiException(400, "Missing the required parameter 'id' when calling endUserLicenseAgreementsTerritoriesGetToManyRelationship");
    }

    HttpRequest.Builder localVarRequestBuilder = HttpRequest.newBuilder();

    String localVarPath = "/v1/endUserLicenseAgreements/{id}/relationships/territories"
        .replace("{id}", ApiClient.urlEncode(id.toString()));

    List<Pair> localVarQueryParams = new ArrayList<>();
    StringJoiner localVarQueryStringJoiner = new StringJoiner("&");
    String localVarQueryParameterBaseName;
    localVarQueryParameterBaseName = "limit";
    localVarQueryParams.addAll(ApiClient.parameterToPairs("limit", limit));

    if (!localVarQueryParams.isEmpty() || localVarQueryStringJoiner.length() != 0) {
      StringJoiner queryJoiner = new StringJoiner("&");
      localVarQueryParams.forEach(p -> queryJoiner.add(p.getName() + '=' + p.getValue()));
      if (localVarQueryStringJoiner.length() != 0) {
        queryJoiner.add(localVarQueryStringJoiner.toString());
      }
      localVarRequestBuilder.uri(URI.create(memberVarBaseUri + localVarPath + '?' + queryJoiner.toString()));
    } else {
      localVarRequestBuilder.uri(URI.create(memberVarBaseUri + localVarPath));
    }

    localVarRequestBuilder.header("Accept", "application/json");

    localVarRequestBuilder.method("GET", HttpRequest.BodyPublishers.noBody());
    if (memberVarReadTimeout != null) {
      localVarRequestBuilder.timeout(memberVarReadTimeout);
    }
    // Add custom headers if provided
    localVarRequestBuilder = HttpRequestBuilderExtensions.withAdditionalHeaders(localVarRequestBuilder, headers);
    if (memberVarInterceptor != null) {
      memberVarInterceptor.accept(localVarRequestBuilder);
    }
    return localVarRequestBuilder;
  }

  /**
   * 
   * 
   * @param id the id of the requested resource (required)
   * @param endUserLicenseAgreementUpdateRequest EndUserLicenseAgreement representation (required)
   * @return EndUserLicenseAgreementResponse
   * @throws ApiException if fails to make API call
   */
  public EndUserLicenseAgreementResponse endUserLicenseAgreementsUpdateInstance(@jakarta.annotation.Nonnull String id, @jakarta.annotation.Nonnull EndUserLicenseAgreementUpdateRequest endUserLicenseAgreementUpdateRequest) throws ApiException {
    return endUserLicenseAgreementsUpdateInstance(id, endUserLicenseAgreementUpdateRequest, null);
  }

  /**
   * 
   * 
   * @param id the id of the requested resource (required)
   * @param endUserLicenseAgreementUpdateRequest EndUserLicenseAgreement representation (required)
   * @param headers Optional headers to include in the request
   * @return EndUserLicenseAgreementResponse
   * @throws ApiException if fails to make API call
   */
  public EndUserLicenseAgreementResponse endUserLicenseAgreementsUpdateInstance(@jakarta.annotation.Nonnull String id, @jakarta.annotation.Nonnull EndUserLicenseAgreementUpdateRequest endUserLicenseAgreementUpdateRequest, Map<String, String> headers) throws ApiException {
    ApiResponse<EndUserLicenseAgreementResponse> localVarResponse = endUserLicenseAgreementsUpdateInstanceWithHttpInfo(id, endUserLicenseAgreementUpdateRequest, headers);
    return localVarResponse.getData();
  }

  /**
   * 
   * 
   * @param id the id of the requested resource (required)
   * @param endUserLicenseAgreementUpdateRequest EndUserLicenseAgreement representation (required)
   * @return ApiResponse&lt;EndUserLicenseAgreementResponse&gt;
   * @throws ApiException if fails to make API call
   */
  public ApiResponse<EndUserLicenseAgreementResponse> endUserLicenseAgreementsUpdateInstanceWithHttpInfo(@jakarta.annotation.Nonnull String id, @jakarta.annotation.Nonnull EndUserLicenseAgreementUpdateRequest endUserLicenseAgreementUpdateRequest) throws ApiException {
    return endUserLicenseAgreementsUpdateInstanceWithHttpInfo(id, endUserLicenseAgreementUpdateRequest, null);
  }

  /**
   * 
   * 
   * @param id the id of the requested resource (required)
   * @param endUserLicenseAgreementUpdateRequest EndUserLicenseAgreement representation (required)
   * @param headers Optional headers to include in the request
   * @return ApiResponse&lt;EndUserLicenseAgreementResponse&gt;
   * @throws ApiException if fails to make API call
   */
  public ApiResponse<EndUserLicenseAgreementResponse> endUserLicenseAgreementsUpdateInstanceWithHttpInfo(@jakarta.annotation.Nonnull String id, @jakarta.annotation.Nonnull EndUserLicenseAgreementUpdateRequest endUserLicenseAgreementUpdateRequest, Map<String, String> headers) throws ApiException {
    HttpRequest.Builder localVarRequestBuilder = endUserLicenseAgreementsUpdateInstanceRequestBuilder(id, endUserLicenseAgreementUpdateRequest, headers);
    try {
      HttpResponse<InputStream> localVarResponse = memberVarHttpClient.send(
          localVarRequestBuilder.build(),
          HttpResponse.BodyHandlers.ofInputStream());
      if (memberVarResponseInterceptor != null) {
        memberVarResponseInterceptor.accept(localVarResponse);
      }
      try {
        if (localVarResponse.statusCode()/ 100 != 2) {
          throw getApiException("endUserLicenseAgreementsUpdateInstance", localVarResponse);
        }
        if (localVarResponse.body() == null) {
          return new ApiResponse<EndUserLicenseAgreementResponse>(
              localVarResponse.statusCode(),
              localVarResponse.headers().map(),
              null
          );
        }

        
        
        String responseBody = new String(localVarResponse.body().readAllBytes());
        EndUserLicenseAgreementResponse responseValue = responseBody.isBlank()? null: memberVarObjectMapper.readValue(responseBody, new TypeReference<EndUserLicenseAgreementResponse>() {});
        
        localVarResponse.body().close();

        return new ApiResponse<EndUserLicenseAgreementResponse>(
            localVarResponse.statusCode(),
            localVarResponse.headers().map(),
            responseValue
        );
      } finally {
      }
    } catch (IOException e) {
      throw new ApiException(e);
    }
    catch (InterruptedException e) {
      Thread.currentThread().interrupt();
      throw new ApiException(e);
    }
  }

  private HttpRequest.Builder endUserLicenseAgreementsUpdateInstanceRequestBuilder(@jakarta.annotation.Nonnull String id, @jakarta.annotation.Nonnull EndUserLicenseAgreementUpdateRequest endUserLicenseAgreementUpdateRequest, Map<String, String> headers) throws ApiException {
    // verify the required parameter 'id' is set
    if (id == null) {
      throw new ApiException(400, "Missing the required parameter 'id' when calling endUserLicenseAgreementsUpdateInstance");
    }
    // verify the required parameter 'endUserLicenseAgreementUpdateRequest' is set
    if (endUserLicenseAgreementUpdateRequest == null) {
      throw new ApiException(400, "Missing the required parameter 'endUserLicenseAgreementUpdateRequest' when calling endUserLicenseAgreementsUpdateInstance");
    }

    HttpRequest.Builder localVarRequestBuilder = HttpRequest.newBuilder();

    String localVarPath = "/v1/endUserLicenseAgreements/{id}"
        .replace("{id}", ApiClient.urlEncode(id.toString()));

    localVarRequestBuilder.uri(URI.create(memberVarBaseUri + localVarPath));

    localVarRequestBuilder.header("Content-Type", "application/json");
    localVarRequestBuilder.header("Accept", "application/json");

    try {
      byte[] localVarPostBody = memberVarObjectMapper.writeValueAsBytes(endUserLicenseAgreementUpdateRequest);
      localVarRequestBuilder.method("PATCH", HttpRequest.BodyPublishers.ofByteArray(localVarPostBody));
    } catch (IOException e) {
      throw new ApiException(e);
    }
    if (memberVarReadTimeout != null) {
      localVarRequestBuilder.timeout(memberVarReadTimeout);
    }
    // Add custom headers if provided
    localVarRequestBuilder = HttpRequestBuilderExtensions.withAdditionalHeaders(localVarRequestBuilder, headers);
    if (memberVarInterceptor != null) {
      memberVarInterceptor.accept(localVarRequestBuilder);
    }
    return localVarRequestBuilder;
  }

}
