/*
 * App Store Connect API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 4.2
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

package com.adguard.stores.appstoreconnect.api;

import com.adguard.stores.appstoreconnect.ApiClient;
import com.adguard.stores.appstoreconnect.ApiException;
import com.adguard.stores.appstoreconnect.ApiResponse;
import com.adguard.stores.appstoreconnect.Configuration;
import com.adguard.stores.appstoreconnect.Pair;

import com.adguard.stores.appstoreconnect.model.ErrorResponse;
import com.adguard.stores.appstoreconnect.model.GameCenterLeaderboardImageCreateRequest;
import com.adguard.stores.appstoreconnect.model.GameCenterLeaderboardImageResponse;
import com.adguard.stores.appstoreconnect.model.GameCenterLeaderboardImageUpdateRequest;
import com.adguard.stores.appstoreconnect.model.GameCenterLeaderboardImageV2CreateRequest;
import com.adguard.stores.appstoreconnect.model.GameCenterLeaderboardImageV2Response;
import com.adguard.stores.appstoreconnect.model.GameCenterLeaderboardImageV2UpdateRequest;

import com.fasterxml.jackson.core.type.TypeReference;
import com.fasterxml.jackson.databind.ObjectMapper;

import java.io.InputStream;
import java.io.ByteArrayInputStream;
import java.io.ByteArrayOutputStream;
import java.io.File;
import java.io.IOException;
import java.io.OutputStream;
import java.net.http.HttpRequest;
import java.nio.channels.Channels;
import java.nio.channels.Pipe;
import java.net.URI;
import java.net.http.HttpClient;
import java.net.http.HttpRequest;
import java.net.http.HttpResponse;
import java.time.Duration;

import java.util.ArrayList;
import java.util.StringJoiner;
import java.util.List;
import java.util.Map;
import java.util.Set;
import java.util.Locale;
import java.util.function.Consumer;

@jakarta.annotation.Generated(value = "org.openapitools.codegen.languages.JavaClientCodegen", comments = "Generator version: 7.17.0")
public class GameCenterLeaderboardImagesApi {
  /**
   * Utility class for extending HttpRequest.Builder functionality.
   */
  private static class HttpRequestBuilderExtensions {
    /**
     * Adds additional headers to the provided HttpRequest.Builder. Useful for adding method/endpoint specific headers.
     *
     * @param builder the HttpRequest.Builder to which headers will be added
     * @param headers a map of header names and values to add; may be null
     * @return the same HttpRequest.Builder instance with the additional headers set
     */
    static HttpRequest.Builder withAdditionalHeaders(HttpRequest.Builder builder, Map<String, String> headers) {
        if (headers != null) {
            for (Map.Entry<String, String> entry : headers.entrySet()) {
                builder.header(entry.getKey(), entry.getValue());
            }
        }
        return builder;
    }
  }
  private final HttpClient memberVarHttpClient;
  private final ObjectMapper memberVarObjectMapper;
  private final String memberVarBaseUri;
  private final Consumer<HttpRequest.Builder> memberVarInterceptor;
  private final Duration memberVarReadTimeout;
  private final Consumer<HttpResponse<InputStream>> memberVarResponseInterceptor;
  private final Consumer<HttpResponse<String>> memberVarAsyncResponseInterceptor;

  public GameCenterLeaderboardImagesApi() {
    this(Configuration.getDefaultApiClient());
  }

  public GameCenterLeaderboardImagesApi(ApiClient apiClient) {
    memberVarHttpClient = apiClient.getHttpClient();
    memberVarObjectMapper = apiClient.getObjectMapper();
    memberVarBaseUri = apiClient.getBaseUri();
    memberVarInterceptor = apiClient.getRequestInterceptor();
    memberVarReadTimeout = apiClient.getReadTimeout();
    memberVarResponseInterceptor = apiClient.getResponseInterceptor();
    memberVarAsyncResponseInterceptor = apiClient.getAsyncResponseInterceptor();
  }


  protected ApiException getApiException(String operationId, HttpResponse<InputStream> response) throws IOException {
    String body = response.body() == null ? null : new String(response.body().readAllBytes());
    String message = formatExceptionMessage(operationId, response.statusCode(), body);
    return new ApiException(response.statusCode(), message, response.headers(), body);
  }

  private String formatExceptionMessage(String operationId, int statusCode, String body) {
    if (body == null || body.isEmpty()) {
      body = "[no body]";
    }
    return operationId + " call failed with: " + statusCode + " - " + body;
  }

  /**
   * Download file from the given response.
   *
   * @param response Response
   * @return File
   * @throws ApiException If fail to read file content from response and write to disk
   */
  public File downloadFileFromResponse(HttpResponse<InputStream> response) throws ApiException {
    try {
      File file = prepareDownloadFile(response);
      java.nio.file.Files.copy(response.body(), file.toPath(), java.nio.file.StandardCopyOption.REPLACE_EXISTING);
      return file;
    } catch (IOException e) {
      throw new ApiException(e);
    }
  }

  /**
   * <p>Prepare the file for download from the response.</p>
   *
   * @param response a {@link java.net.http.HttpResponse} object.
   * @return a {@link java.io.File} object.
   * @throws java.io.IOException if any.
   */
  private File prepareDownloadFile(HttpResponse<InputStream> response) throws IOException {
    String filename = null;
    java.util.Optional<String> contentDisposition = response.headers().firstValue("Content-Disposition");
    if (contentDisposition.isPresent() && !"".equals(contentDisposition.get())) {
      // Get filename from the Content-Disposition header.
      java.util.regex.Pattern pattern = java.util.regex.Pattern.compile("filename=['\"]?([^'\"\\s]+)['\"]?");
      java.util.regex.Matcher matcher = pattern.matcher(contentDisposition.get());
      if (matcher.find())
        filename = matcher.group(1);
    }
    File file = null;
    if (filename != null) {
      java.nio.file.Path tempDir = java.nio.file.Files.createTempDirectory("swagger-gen-native");
      java.nio.file.Path filePath = java.nio.file.Files.createFile(tempDir.resolve(filename));
      file = filePath.toFile();
      tempDir.toFile().deleteOnExit();   // best effort cleanup
      file.deleteOnExit(); // best effort cleanup
    } else {
      file = java.nio.file.Files.createTempFile("download-", "").toFile();
      file.deleteOnExit(); // best effort cleanup
    }
    return file;
  }

  /**
   * 
   * 
   * @param gameCenterLeaderboardImageCreateRequest GameCenterLeaderboardImage representation (required)
   * @return GameCenterLeaderboardImageResponse
   * @throws ApiException if fails to make API call
   */
  public GameCenterLeaderboardImageResponse gameCenterLeaderboardImagesCreateInstance(@jakarta.annotation.Nonnull GameCenterLeaderboardImageCreateRequest gameCenterLeaderboardImageCreateRequest) throws ApiException {
    return gameCenterLeaderboardImagesCreateInstance(gameCenterLeaderboardImageCreateRequest, null);
  }

  /**
   * 
   * 
   * @param gameCenterLeaderboardImageCreateRequest GameCenterLeaderboardImage representation (required)
   * @param headers Optional headers to include in the request
   * @return GameCenterLeaderboardImageResponse
   * @throws ApiException if fails to make API call
   */
  public GameCenterLeaderboardImageResponse gameCenterLeaderboardImagesCreateInstance(@jakarta.annotation.Nonnull GameCenterLeaderboardImageCreateRequest gameCenterLeaderboardImageCreateRequest, Map<String, String> headers) throws ApiException {
    ApiResponse<GameCenterLeaderboardImageResponse> localVarResponse = gameCenterLeaderboardImagesCreateInstanceWithHttpInfo(gameCenterLeaderboardImageCreateRequest, headers);
    return localVarResponse.getData();
  }

  /**
   * 
   * 
   * @param gameCenterLeaderboardImageCreateRequest GameCenterLeaderboardImage representation (required)
   * @return ApiResponse&lt;GameCenterLeaderboardImageResponse&gt;
   * @throws ApiException if fails to make API call
   */
  public ApiResponse<GameCenterLeaderboardImageResponse> gameCenterLeaderboardImagesCreateInstanceWithHttpInfo(@jakarta.annotation.Nonnull GameCenterLeaderboardImageCreateRequest gameCenterLeaderboardImageCreateRequest) throws ApiException {
    return gameCenterLeaderboardImagesCreateInstanceWithHttpInfo(gameCenterLeaderboardImageCreateRequest, null);
  }

  /**
   * 
   * 
   * @param gameCenterLeaderboardImageCreateRequest GameCenterLeaderboardImage representation (required)
   * @param headers Optional headers to include in the request
   * @return ApiResponse&lt;GameCenterLeaderboardImageResponse&gt;
   * @throws ApiException if fails to make API call
   */
  public ApiResponse<GameCenterLeaderboardImageResponse> gameCenterLeaderboardImagesCreateInstanceWithHttpInfo(@jakarta.annotation.Nonnull GameCenterLeaderboardImageCreateRequest gameCenterLeaderboardImageCreateRequest, Map<String, String> headers) throws ApiException {
    HttpRequest.Builder localVarRequestBuilder = gameCenterLeaderboardImagesCreateInstanceRequestBuilder(gameCenterLeaderboardImageCreateRequest, headers);
    try {
      HttpResponse<InputStream> localVarResponse = memberVarHttpClient.send(
          localVarRequestBuilder.build(),
          HttpResponse.BodyHandlers.ofInputStream());
      if (memberVarResponseInterceptor != null) {
        memberVarResponseInterceptor.accept(localVarResponse);
      }
      try {
        if (localVarResponse.statusCode()/ 100 != 2) {
          throw getApiException("gameCenterLeaderboardImagesCreateInstance", localVarResponse);
        }
        if (localVarResponse.body() == null) {
          return new ApiResponse<GameCenterLeaderboardImageResponse>(
              localVarResponse.statusCode(),
              localVarResponse.headers().map(),
              null
          );
        }

        
        
        String responseBody = new String(localVarResponse.body().readAllBytes());
        GameCenterLeaderboardImageResponse responseValue = responseBody.isBlank()? null: memberVarObjectMapper.readValue(responseBody, new TypeReference<GameCenterLeaderboardImageResponse>() {});
        
        localVarResponse.body().close();

        return new ApiResponse<GameCenterLeaderboardImageResponse>(
            localVarResponse.statusCode(),
            localVarResponse.headers().map(),
            responseValue
        );
      } finally {
      }
    } catch (IOException e) {
      throw new ApiException(e);
    }
    catch (InterruptedException e) {
      Thread.currentThread().interrupt();
      throw new ApiException(e);
    }
  }

  private HttpRequest.Builder gameCenterLeaderboardImagesCreateInstanceRequestBuilder(@jakarta.annotation.Nonnull GameCenterLeaderboardImageCreateRequest gameCenterLeaderboardImageCreateRequest, Map<String, String> headers) throws ApiException {
    // verify the required parameter 'gameCenterLeaderboardImageCreateRequest' is set
    if (gameCenterLeaderboardImageCreateRequest == null) {
      throw new ApiException(400, "Missing the required parameter 'gameCenterLeaderboardImageCreateRequest' when calling gameCenterLeaderboardImagesCreateInstance");
    }

    HttpRequest.Builder localVarRequestBuilder = HttpRequest.newBuilder();

    String localVarPath = "/v1/gameCenterLeaderboardImages";

    localVarRequestBuilder.uri(URI.create(memberVarBaseUri + localVarPath));

    localVarRequestBuilder.header("Content-Type", "application/json");
    localVarRequestBuilder.header("Accept", "application/json");

    try {
      byte[] localVarPostBody = memberVarObjectMapper.writeValueAsBytes(gameCenterLeaderboardImageCreateRequest);
      localVarRequestBuilder.method("POST", HttpRequest.BodyPublishers.ofByteArray(localVarPostBody));
    } catch (IOException e) {
      throw new ApiException(e);
    }
    if (memberVarReadTimeout != null) {
      localVarRequestBuilder.timeout(memberVarReadTimeout);
    }
    // Add custom headers if provided
    localVarRequestBuilder = HttpRequestBuilderExtensions.withAdditionalHeaders(localVarRequestBuilder, headers);
    if (memberVarInterceptor != null) {
      memberVarInterceptor.accept(localVarRequestBuilder);
    }
    return localVarRequestBuilder;
  }

  /**
   * 
   * 
   * @param id the id of the requested resource (required)
   * @throws ApiException if fails to make API call
   */
  public void gameCenterLeaderboardImagesDeleteInstance(@jakarta.annotation.Nonnull String id) throws ApiException {
    gameCenterLeaderboardImagesDeleteInstance(id, null);
  }

  /**
   * 
   * 
   * @param id the id of the requested resource (required)
   * @param headers Optional headers to include in the request
   * @throws ApiException if fails to make API call
   */
  public void gameCenterLeaderboardImagesDeleteInstance(@jakarta.annotation.Nonnull String id, Map<String, String> headers) throws ApiException {
    gameCenterLeaderboardImagesDeleteInstanceWithHttpInfo(id, headers);
  }

  /**
   * 
   * 
   * @param id the id of the requested resource (required)
   * @return ApiResponse&lt;Void&gt;
   * @throws ApiException if fails to make API call
   */
  public ApiResponse<Void> gameCenterLeaderboardImagesDeleteInstanceWithHttpInfo(@jakarta.annotation.Nonnull String id) throws ApiException {
    return gameCenterLeaderboardImagesDeleteInstanceWithHttpInfo(id, null);
  }

  /**
   * 
   * 
   * @param id the id of the requested resource (required)
   * @param headers Optional headers to include in the request
   * @return ApiResponse&lt;Void&gt;
   * @throws ApiException if fails to make API call
   */
  public ApiResponse<Void> gameCenterLeaderboardImagesDeleteInstanceWithHttpInfo(@jakarta.annotation.Nonnull String id, Map<String, String> headers) throws ApiException {
    HttpRequest.Builder localVarRequestBuilder = gameCenterLeaderboardImagesDeleteInstanceRequestBuilder(id, headers);
    try {
      HttpResponse<InputStream> localVarResponse = memberVarHttpClient.send(
          localVarRequestBuilder.build(),
          HttpResponse.BodyHandlers.ofInputStream());
      if (memberVarResponseInterceptor != null) {
        memberVarResponseInterceptor.accept(localVarResponse);
      }
      try {
        if (localVarResponse.statusCode()/ 100 != 2) {
          throw getApiException("gameCenterLeaderboardImagesDeleteInstance", localVarResponse);
        }
        return new ApiResponse<>(
            localVarResponse.statusCode(),
            localVarResponse.headers().map(),
            null
        );
      } finally {
        // Drain the InputStream
        while (localVarResponse.body().read() != -1) {
          // Ignore
        }
        localVarResponse.body().close();
      }
    } catch (IOException e) {
      throw new ApiException(e);
    }
    catch (InterruptedException e) {
      Thread.currentThread().interrupt();
      throw new ApiException(e);
    }
  }

  private HttpRequest.Builder gameCenterLeaderboardImagesDeleteInstanceRequestBuilder(@jakarta.annotation.Nonnull String id, Map<String, String> headers) throws ApiException {
    // verify the required parameter 'id' is set
    if (id == null) {
      throw new ApiException(400, "Missing the required parameter 'id' when calling gameCenterLeaderboardImagesDeleteInstance");
    }

    HttpRequest.Builder localVarRequestBuilder = HttpRequest.newBuilder();

    String localVarPath = "/v1/gameCenterLeaderboardImages/{id}"
        .replace("{id}", ApiClient.urlEncode(id.toString()));

    localVarRequestBuilder.uri(URI.create(memberVarBaseUri + localVarPath));

    localVarRequestBuilder.header("Accept", "application/json");

    localVarRequestBuilder.method("DELETE", HttpRequest.BodyPublishers.noBody());
    if (memberVarReadTimeout != null) {
      localVarRequestBuilder.timeout(memberVarReadTimeout);
    }
    // Add custom headers if provided
    localVarRequestBuilder = HttpRequestBuilderExtensions.withAdditionalHeaders(localVarRequestBuilder, headers);
    if (memberVarInterceptor != null) {
      memberVarInterceptor.accept(localVarRequestBuilder);
    }
    return localVarRequestBuilder;
  }

  /**
   * 
   * 
   * @param id the id of the requested resource (required)
   * @param fieldsGameCenterLeaderboardImages the fields to include for returned resources of type gameCenterLeaderboardImages (optional)
   * @param include comma-separated list of relationships to include (optional)
   * @return GameCenterLeaderboardImageResponse
   * @throws ApiException if fails to make API call
   */
  public GameCenterLeaderboardImageResponse gameCenterLeaderboardImagesGetInstance(@jakarta.annotation.Nonnull String id, @jakarta.annotation.Nullable List<String> fieldsGameCenterLeaderboardImages, @jakarta.annotation.Nullable List<String> include) throws ApiException {
    return gameCenterLeaderboardImagesGetInstance(id, fieldsGameCenterLeaderboardImages, include, null);
  }

  /**
   * 
   * 
   * @param id the id of the requested resource (required)
   * @param fieldsGameCenterLeaderboardImages the fields to include for returned resources of type gameCenterLeaderboardImages (optional)
   * @param include comma-separated list of relationships to include (optional)
   * @param headers Optional headers to include in the request
   * @return GameCenterLeaderboardImageResponse
   * @throws ApiException if fails to make API call
   */
  public GameCenterLeaderboardImageResponse gameCenterLeaderboardImagesGetInstance(@jakarta.annotation.Nonnull String id, @jakarta.annotation.Nullable List<String> fieldsGameCenterLeaderboardImages, @jakarta.annotation.Nullable List<String> include, Map<String, String> headers) throws ApiException {
    ApiResponse<GameCenterLeaderboardImageResponse> localVarResponse = gameCenterLeaderboardImagesGetInstanceWithHttpInfo(id, fieldsGameCenterLeaderboardImages, include, headers);
    return localVarResponse.getData();
  }

  /**
   * 
   * 
   * @param id the id of the requested resource (required)
   * @param fieldsGameCenterLeaderboardImages the fields to include for returned resources of type gameCenterLeaderboardImages (optional)
   * @param include comma-separated list of relationships to include (optional)
   * @return ApiResponse&lt;GameCenterLeaderboardImageResponse&gt;
   * @throws ApiException if fails to make API call
   */
  public ApiResponse<GameCenterLeaderboardImageResponse> gameCenterLeaderboardImagesGetInstanceWithHttpInfo(@jakarta.annotation.Nonnull String id, @jakarta.annotation.Nullable List<String> fieldsGameCenterLeaderboardImages, @jakarta.annotation.Nullable List<String> include) throws ApiException {
    return gameCenterLeaderboardImagesGetInstanceWithHttpInfo(id, fieldsGameCenterLeaderboardImages, include, null);
  }

  /**
   * 
   * 
   * @param id the id of the requested resource (required)
   * @param fieldsGameCenterLeaderboardImages the fields to include for returned resources of type gameCenterLeaderboardImages (optional)
   * @param include comma-separated list of relationships to include (optional)
   * @param headers Optional headers to include in the request
   * @return ApiResponse&lt;GameCenterLeaderboardImageResponse&gt;
   * @throws ApiException if fails to make API call
   */
  public ApiResponse<GameCenterLeaderboardImageResponse> gameCenterLeaderboardImagesGetInstanceWithHttpInfo(@jakarta.annotation.Nonnull String id, @jakarta.annotation.Nullable List<String> fieldsGameCenterLeaderboardImages, @jakarta.annotation.Nullable List<String> include, Map<String, String> headers) throws ApiException {
    HttpRequest.Builder localVarRequestBuilder = gameCenterLeaderboardImagesGetInstanceRequestBuilder(id, fieldsGameCenterLeaderboardImages, include, headers);
    try {
      HttpResponse<InputStream> localVarResponse = memberVarHttpClient.send(
          localVarRequestBuilder.build(),
          HttpResponse.BodyHandlers.ofInputStream());
      if (memberVarResponseInterceptor != null) {
        memberVarResponseInterceptor.accept(localVarResponse);
      }
      try {
        if (localVarResponse.statusCode()/ 100 != 2) {
          throw getApiException("gameCenterLeaderboardImagesGetInstance", localVarResponse);
        }
        if (localVarResponse.body() == null) {
          return new ApiResponse<GameCenterLeaderboardImageResponse>(
              localVarResponse.statusCode(),
              localVarResponse.headers().map(),
              null
          );
        }

        
        
        String responseBody = new String(localVarResponse.body().readAllBytes());
        GameCenterLeaderboardImageResponse responseValue = responseBody.isBlank()? null: memberVarObjectMapper.readValue(responseBody, new TypeReference<GameCenterLeaderboardImageResponse>() {});
        
        localVarResponse.body().close();

        return new ApiResponse<GameCenterLeaderboardImageResponse>(
            localVarResponse.statusCode(),
            localVarResponse.headers().map(),
            responseValue
        );
      } finally {
      }
    } catch (IOException e) {
      throw new ApiException(e);
    }
    catch (InterruptedException e) {
      Thread.currentThread().interrupt();
      throw new ApiException(e);
    }
  }

  private HttpRequest.Builder gameCenterLeaderboardImagesGetInstanceRequestBuilder(@jakarta.annotation.Nonnull String id, @jakarta.annotation.Nullable List<String> fieldsGameCenterLeaderboardImages, @jakarta.annotation.Nullable List<String> include, Map<String, String> headers) throws ApiException {
    // verify the required parameter 'id' is set
    if (id == null) {
      throw new ApiException(400, "Missing the required parameter 'id' when calling gameCenterLeaderboardImagesGetInstance");
    }

    HttpRequest.Builder localVarRequestBuilder = HttpRequest.newBuilder();

    String localVarPath = "/v1/gameCenterLeaderboardImages/{id}"
        .replace("{id}", ApiClient.urlEncode(id.toString()));

    List<Pair> localVarQueryParams = new ArrayList<>();
    StringJoiner localVarQueryStringJoiner = new StringJoiner("&");
    String localVarQueryParameterBaseName;
    localVarQueryParameterBaseName = "fields[gameCenterLeaderboardImages]";
    localVarQueryParams.addAll(ApiClient.parameterToPairs("csv", "fields[gameCenterLeaderboardImages]", fieldsGameCenterLeaderboardImages));
    localVarQueryParameterBaseName = "include";
    localVarQueryParams.addAll(ApiClient.parameterToPairs("csv", "include", include));

    if (!localVarQueryParams.isEmpty() || localVarQueryStringJoiner.length() != 0) {
      StringJoiner queryJoiner = new StringJoiner("&");
      localVarQueryParams.forEach(p -> queryJoiner.add(p.getName() + '=' + p.getValue()));
      if (localVarQueryStringJoiner.length() != 0) {
        queryJoiner.add(localVarQueryStringJoiner.toString());
      }
      localVarRequestBuilder.uri(URI.create(memberVarBaseUri + localVarPath + '?' + queryJoiner.toString()));
    } else {
      localVarRequestBuilder.uri(URI.create(memberVarBaseUri + localVarPath));
    }

    localVarRequestBuilder.header("Accept", "application/json");

    localVarRequestBuilder.method("GET", HttpRequest.BodyPublishers.noBody());
    if (memberVarReadTimeout != null) {
      localVarRequestBuilder.timeout(memberVarReadTimeout);
    }
    // Add custom headers if provided
    localVarRequestBuilder = HttpRequestBuilderExtensions.withAdditionalHeaders(localVarRequestBuilder, headers);
    if (memberVarInterceptor != null) {
      memberVarInterceptor.accept(localVarRequestBuilder);
    }
    return localVarRequestBuilder;
  }

  /**
   * 
   * 
   * @param id the id of the requested resource (required)
   * @param gameCenterLeaderboardImageUpdateRequest GameCenterLeaderboardImage representation (required)
   * @return GameCenterLeaderboardImageResponse
   * @throws ApiException if fails to make API call
   */
  public GameCenterLeaderboardImageResponse gameCenterLeaderboardImagesUpdateInstance(@jakarta.annotation.Nonnull String id, @jakarta.annotation.Nonnull GameCenterLeaderboardImageUpdateRequest gameCenterLeaderboardImageUpdateRequest) throws ApiException {
    return gameCenterLeaderboardImagesUpdateInstance(id, gameCenterLeaderboardImageUpdateRequest, null);
  }

  /**
   * 
   * 
   * @param id the id of the requested resource (required)
   * @param gameCenterLeaderboardImageUpdateRequest GameCenterLeaderboardImage representation (required)
   * @param headers Optional headers to include in the request
   * @return GameCenterLeaderboardImageResponse
   * @throws ApiException if fails to make API call
   */
  public GameCenterLeaderboardImageResponse gameCenterLeaderboardImagesUpdateInstance(@jakarta.annotation.Nonnull String id, @jakarta.annotation.Nonnull GameCenterLeaderboardImageUpdateRequest gameCenterLeaderboardImageUpdateRequest, Map<String, String> headers) throws ApiException {
    ApiResponse<GameCenterLeaderboardImageResponse> localVarResponse = gameCenterLeaderboardImagesUpdateInstanceWithHttpInfo(id, gameCenterLeaderboardImageUpdateRequest, headers);
    return localVarResponse.getData();
  }

  /**
   * 
   * 
   * @param id the id of the requested resource (required)
   * @param gameCenterLeaderboardImageUpdateRequest GameCenterLeaderboardImage representation (required)
   * @return ApiResponse&lt;GameCenterLeaderboardImageResponse&gt;
   * @throws ApiException if fails to make API call
   */
  public ApiResponse<GameCenterLeaderboardImageResponse> gameCenterLeaderboardImagesUpdateInstanceWithHttpInfo(@jakarta.annotation.Nonnull String id, @jakarta.annotation.Nonnull GameCenterLeaderboardImageUpdateRequest gameCenterLeaderboardImageUpdateRequest) throws ApiException {
    return gameCenterLeaderboardImagesUpdateInstanceWithHttpInfo(id, gameCenterLeaderboardImageUpdateRequest, null);
  }

  /**
   * 
   * 
   * @param id the id of the requested resource (required)
   * @param gameCenterLeaderboardImageUpdateRequest GameCenterLeaderboardImage representation (required)
   * @param headers Optional headers to include in the request
   * @return ApiResponse&lt;GameCenterLeaderboardImageResponse&gt;
   * @throws ApiException if fails to make API call
   */
  public ApiResponse<GameCenterLeaderboardImageResponse> gameCenterLeaderboardImagesUpdateInstanceWithHttpInfo(@jakarta.annotation.Nonnull String id, @jakarta.annotation.Nonnull GameCenterLeaderboardImageUpdateRequest gameCenterLeaderboardImageUpdateRequest, Map<String, String> headers) throws ApiException {
    HttpRequest.Builder localVarRequestBuilder = gameCenterLeaderboardImagesUpdateInstanceRequestBuilder(id, gameCenterLeaderboardImageUpdateRequest, headers);
    try {
      HttpResponse<InputStream> localVarResponse = memberVarHttpClient.send(
          localVarRequestBuilder.build(),
          HttpResponse.BodyHandlers.ofInputStream());
      if (memberVarResponseInterceptor != null) {
        memberVarResponseInterceptor.accept(localVarResponse);
      }
      try {
        if (localVarResponse.statusCode()/ 100 != 2) {
          throw getApiException("gameCenterLeaderboardImagesUpdateInstance", localVarResponse);
        }
        if (localVarResponse.body() == null) {
          return new ApiResponse<GameCenterLeaderboardImageResponse>(
              localVarResponse.statusCode(),
              localVarResponse.headers().map(),
              null
          );
        }

        
        
        String responseBody = new String(localVarResponse.body().readAllBytes());
        GameCenterLeaderboardImageResponse responseValue = responseBody.isBlank()? null: memberVarObjectMapper.readValue(responseBody, new TypeReference<GameCenterLeaderboardImageResponse>() {});
        
        localVarResponse.body().close();

        return new ApiResponse<GameCenterLeaderboardImageResponse>(
            localVarResponse.statusCode(),
            localVarResponse.headers().map(),
            responseValue
        );
      } finally {
      }
    } catch (IOException e) {
      throw new ApiException(e);
    }
    catch (InterruptedException e) {
      Thread.currentThread().interrupt();
      throw new ApiException(e);
    }
  }

  private HttpRequest.Builder gameCenterLeaderboardImagesUpdateInstanceRequestBuilder(@jakarta.annotation.Nonnull String id, @jakarta.annotation.Nonnull GameCenterLeaderboardImageUpdateRequest gameCenterLeaderboardImageUpdateRequest, Map<String, String> headers) throws ApiException {
    // verify the required parameter 'id' is set
    if (id == null) {
      throw new ApiException(400, "Missing the required parameter 'id' when calling gameCenterLeaderboardImagesUpdateInstance");
    }
    // verify the required parameter 'gameCenterLeaderboardImageUpdateRequest' is set
    if (gameCenterLeaderboardImageUpdateRequest == null) {
      throw new ApiException(400, "Missing the required parameter 'gameCenterLeaderboardImageUpdateRequest' when calling gameCenterLeaderboardImagesUpdateInstance");
    }

    HttpRequest.Builder localVarRequestBuilder = HttpRequest.newBuilder();

    String localVarPath = "/v1/gameCenterLeaderboardImages/{id}"
        .replace("{id}", ApiClient.urlEncode(id.toString()));

    localVarRequestBuilder.uri(URI.create(memberVarBaseUri + localVarPath));

    localVarRequestBuilder.header("Content-Type", "application/json");
    localVarRequestBuilder.header("Accept", "application/json");

    try {
      byte[] localVarPostBody = memberVarObjectMapper.writeValueAsBytes(gameCenterLeaderboardImageUpdateRequest);
      localVarRequestBuilder.method("PATCH", HttpRequest.BodyPublishers.ofByteArray(localVarPostBody));
    } catch (IOException e) {
      throw new ApiException(e);
    }
    if (memberVarReadTimeout != null) {
      localVarRequestBuilder.timeout(memberVarReadTimeout);
    }
    // Add custom headers if provided
    localVarRequestBuilder = HttpRequestBuilderExtensions.withAdditionalHeaders(localVarRequestBuilder, headers);
    if (memberVarInterceptor != null) {
      memberVarInterceptor.accept(localVarRequestBuilder);
    }
    return localVarRequestBuilder;
  }

  /**
   * 
   * 
   * @param gameCenterLeaderboardImageV2CreateRequest GameCenterLeaderboardImage representation (required)
   * @return GameCenterLeaderboardImageV2Response
   * @throws ApiException if fails to make API call
   */
  public GameCenterLeaderboardImageV2Response gameCenterLeaderboardImagesV2CreateInstance(@jakarta.annotation.Nonnull GameCenterLeaderboardImageV2CreateRequest gameCenterLeaderboardImageV2CreateRequest) throws ApiException {
    return gameCenterLeaderboardImagesV2CreateInstance(gameCenterLeaderboardImageV2CreateRequest, null);
  }

  /**
   * 
   * 
   * @param gameCenterLeaderboardImageV2CreateRequest GameCenterLeaderboardImage representation (required)
   * @param headers Optional headers to include in the request
   * @return GameCenterLeaderboardImageV2Response
   * @throws ApiException if fails to make API call
   */
  public GameCenterLeaderboardImageV2Response gameCenterLeaderboardImagesV2CreateInstance(@jakarta.annotation.Nonnull GameCenterLeaderboardImageV2CreateRequest gameCenterLeaderboardImageV2CreateRequest, Map<String, String> headers) throws ApiException {
    ApiResponse<GameCenterLeaderboardImageV2Response> localVarResponse = gameCenterLeaderboardImagesV2CreateInstanceWithHttpInfo(gameCenterLeaderboardImageV2CreateRequest, headers);
    return localVarResponse.getData();
  }

  /**
   * 
   * 
   * @param gameCenterLeaderboardImageV2CreateRequest GameCenterLeaderboardImage representation (required)
   * @return ApiResponse&lt;GameCenterLeaderboardImageV2Response&gt;
   * @throws ApiException if fails to make API call
   */
  public ApiResponse<GameCenterLeaderboardImageV2Response> gameCenterLeaderboardImagesV2CreateInstanceWithHttpInfo(@jakarta.annotation.Nonnull GameCenterLeaderboardImageV2CreateRequest gameCenterLeaderboardImageV2CreateRequest) throws ApiException {
    return gameCenterLeaderboardImagesV2CreateInstanceWithHttpInfo(gameCenterLeaderboardImageV2CreateRequest, null);
  }

  /**
   * 
   * 
   * @param gameCenterLeaderboardImageV2CreateRequest GameCenterLeaderboardImage representation (required)
   * @param headers Optional headers to include in the request
   * @return ApiResponse&lt;GameCenterLeaderboardImageV2Response&gt;
   * @throws ApiException if fails to make API call
   */
  public ApiResponse<GameCenterLeaderboardImageV2Response> gameCenterLeaderboardImagesV2CreateInstanceWithHttpInfo(@jakarta.annotation.Nonnull GameCenterLeaderboardImageV2CreateRequest gameCenterLeaderboardImageV2CreateRequest, Map<String, String> headers) throws ApiException {
    HttpRequest.Builder localVarRequestBuilder = gameCenterLeaderboardImagesV2CreateInstanceRequestBuilder(gameCenterLeaderboardImageV2CreateRequest, headers);
    try {
      HttpResponse<InputStream> localVarResponse = memberVarHttpClient.send(
          localVarRequestBuilder.build(),
          HttpResponse.BodyHandlers.ofInputStream());
      if (memberVarResponseInterceptor != null) {
        memberVarResponseInterceptor.accept(localVarResponse);
      }
      try {
        if (localVarResponse.statusCode()/ 100 != 2) {
          throw getApiException("gameCenterLeaderboardImagesV2CreateInstance", localVarResponse);
        }
        if (localVarResponse.body() == null) {
          return new ApiResponse<GameCenterLeaderboardImageV2Response>(
              localVarResponse.statusCode(),
              localVarResponse.headers().map(),
              null
          );
        }

        
        
        String responseBody = new String(localVarResponse.body().readAllBytes());
        GameCenterLeaderboardImageV2Response responseValue = responseBody.isBlank()? null: memberVarObjectMapper.readValue(responseBody, new TypeReference<GameCenterLeaderboardImageV2Response>() {});
        
        localVarResponse.body().close();

        return new ApiResponse<GameCenterLeaderboardImageV2Response>(
            localVarResponse.statusCode(),
            localVarResponse.headers().map(),
            responseValue
        );
      } finally {
      }
    } catch (IOException e) {
      throw new ApiException(e);
    }
    catch (InterruptedException e) {
      Thread.currentThread().interrupt();
      throw new ApiException(e);
    }
  }

  private HttpRequest.Builder gameCenterLeaderboardImagesV2CreateInstanceRequestBuilder(@jakarta.annotation.Nonnull GameCenterLeaderboardImageV2CreateRequest gameCenterLeaderboardImageV2CreateRequest, Map<String, String> headers) throws ApiException {
    // verify the required parameter 'gameCenterLeaderboardImageV2CreateRequest' is set
    if (gameCenterLeaderboardImageV2CreateRequest == null) {
      throw new ApiException(400, "Missing the required parameter 'gameCenterLeaderboardImageV2CreateRequest' when calling gameCenterLeaderboardImagesV2CreateInstance");
    }

    HttpRequest.Builder localVarRequestBuilder = HttpRequest.newBuilder();

    String localVarPath = "/v2/gameCenterLeaderboardImages";

    localVarRequestBuilder.uri(URI.create(memberVarBaseUri + localVarPath));

    localVarRequestBuilder.header("Content-Type", "application/json");
    localVarRequestBuilder.header("Accept", "application/json");

    try {
      byte[] localVarPostBody = memberVarObjectMapper.writeValueAsBytes(gameCenterLeaderboardImageV2CreateRequest);
      localVarRequestBuilder.method("POST", HttpRequest.BodyPublishers.ofByteArray(localVarPostBody));
    } catch (IOException e) {
      throw new ApiException(e);
    }
    if (memberVarReadTimeout != null) {
      localVarRequestBuilder.timeout(memberVarReadTimeout);
    }
    // Add custom headers if provided
    localVarRequestBuilder = HttpRequestBuilderExtensions.withAdditionalHeaders(localVarRequestBuilder, headers);
    if (memberVarInterceptor != null) {
      memberVarInterceptor.accept(localVarRequestBuilder);
    }
    return localVarRequestBuilder;
  }

  /**
   * 
   * 
   * @param id the id of the requested resource (required)
   * @throws ApiException if fails to make API call
   */
  public void gameCenterLeaderboardImagesV2DeleteInstance(@jakarta.annotation.Nonnull String id) throws ApiException {
    gameCenterLeaderboardImagesV2DeleteInstance(id, null);
  }

  /**
   * 
   * 
   * @param id the id of the requested resource (required)
   * @param headers Optional headers to include in the request
   * @throws ApiException if fails to make API call
   */
  public void gameCenterLeaderboardImagesV2DeleteInstance(@jakarta.annotation.Nonnull String id, Map<String, String> headers) throws ApiException {
    gameCenterLeaderboardImagesV2DeleteInstanceWithHttpInfo(id, headers);
  }

  /**
   * 
   * 
   * @param id the id of the requested resource (required)
   * @return ApiResponse&lt;Void&gt;
   * @throws ApiException if fails to make API call
   */
  public ApiResponse<Void> gameCenterLeaderboardImagesV2DeleteInstanceWithHttpInfo(@jakarta.annotation.Nonnull String id) throws ApiException {
    return gameCenterLeaderboardImagesV2DeleteInstanceWithHttpInfo(id, null);
  }

  /**
   * 
   * 
   * @param id the id of the requested resource (required)
   * @param headers Optional headers to include in the request
   * @return ApiResponse&lt;Void&gt;
   * @throws ApiException if fails to make API call
   */
  public ApiResponse<Void> gameCenterLeaderboardImagesV2DeleteInstanceWithHttpInfo(@jakarta.annotation.Nonnull String id, Map<String, String> headers) throws ApiException {
    HttpRequest.Builder localVarRequestBuilder = gameCenterLeaderboardImagesV2DeleteInstanceRequestBuilder(id, headers);
    try {
      HttpResponse<InputStream> localVarResponse = memberVarHttpClient.send(
          localVarRequestBuilder.build(),
          HttpResponse.BodyHandlers.ofInputStream());
      if (memberVarResponseInterceptor != null) {
        memberVarResponseInterceptor.accept(localVarResponse);
      }
      try {
        if (localVarResponse.statusCode()/ 100 != 2) {
          throw getApiException("gameCenterLeaderboardImagesV2DeleteInstance", localVarResponse);
        }
        return new ApiResponse<>(
            localVarResponse.statusCode(),
            localVarResponse.headers().map(),
            null
        );
      } finally {
        // Drain the InputStream
        while (localVarResponse.body().read() != -1) {
          // Ignore
        }
        localVarResponse.body().close();
      }
    } catch (IOException e) {
      throw new ApiException(e);
    }
    catch (InterruptedException e) {
      Thread.currentThread().interrupt();
      throw new ApiException(e);
    }
  }

  private HttpRequest.Builder gameCenterLeaderboardImagesV2DeleteInstanceRequestBuilder(@jakarta.annotation.Nonnull String id, Map<String, String> headers) throws ApiException {
    // verify the required parameter 'id' is set
    if (id == null) {
      throw new ApiException(400, "Missing the required parameter 'id' when calling gameCenterLeaderboardImagesV2DeleteInstance");
    }

    HttpRequest.Builder localVarRequestBuilder = HttpRequest.newBuilder();

    String localVarPath = "/v2/gameCenterLeaderboardImages/{id}"
        .replace("{id}", ApiClient.urlEncode(id.toString()));

    localVarRequestBuilder.uri(URI.create(memberVarBaseUri + localVarPath));

    localVarRequestBuilder.header("Accept", "application/json");

    localVarRequestBuilder.method("DELETE", HttpRequest.BodyPublishers.noBody());
    if (memberVarReadTimeout != null) {
      localVarRequestBuilder.timeout(memberVarReadTimeout);
    }
    // Add custom headers if provided
    localVarRequestBuilder = HttpRequestBuilderExtensions.withAdditionalHeaders(localVarRequestBuilder, headers);
    if (memberVarInterceptor != null) {
      memberVarInterceptor.accept(localVarRequestBuilder);
    }
    return localVarRequestBuilder;
  }

  /**
   * 
   * 
   * @param id the id of the requested resource (required)
   * @param fieldsGameCenterLeaderboardImages the fields to include for returned resources of type gameCenterLeaderboardImages (optional)
   * @param include comma-separated list of relationships to include (optional)
   * @return GameCenterLeaderboardImageV2Response
   * @throws ApiException if fails to make API call
   */
  public GameCenterLeaderboardImageV2Response gameCenterLeaderboardImagesV2GetInstance(@jakarta.annotation.Nonnull String id, @jakarta.annotation.Nullable List<String> fieldsGameCenterLeaderboardImages, @jakarta.annotation.Nullable List<String> include) throws ApiException {
    return gameCenterLeaderboardImagesV2GetInstance(id, fieldsGameCenterLeaderboardImages, include, null);
  }

  /**
   * 
   * 
   * @param id the id of the requested resource (required)
   * @param fieldsGameCenterLeaderboardImages the fields to include for returned resources of type gameCenterLeaderboardImages (optional)
   * @param include comma-separated list of relationships to include (optional)
   * @param headers Optional headers to include in the request
   * @return GameCenterLeaderboardImageV2Response
   * @throws ApiException if fails to make API call
   */
  public GameCenterLeaderboardImageV2Response gameCenterLeaderboardImagesV2GetInstance(@jakarta.annotation.Nonnull String id, @jakarta.annotation.Nullable List<String> fieldsGameCenterLeaderboardImages, @jakarta.annotation.Nullable List<String> include, Map<String, String> headers) throws ApiException {
    ApiResponse<GameCenterLeaderboardImageV2Response> localVarResponse = gameCenterLeaderboardImagesV2GetInstanceWithHttpInfo(id, fieldsGameCenterLeaderboardImages, include, headers);
    return localVarResponse.getData();
  }

  /**
   * 
   * 
   * @param id the id of the requested resource (required)
   * @param fieldsGameCenterLeaderboardImages the fields to include for returned resources of type gameCenterLeaderboardImages (optional)
   * @param include comma-separated list of relationships to include (optional)
   * @return ApiResponse&lt;GameCenterLeaderboardImageV2Response&gt;
   * @throws ApiException if fails to make API call
   */
  public ApiResponse<GameCenterLeaderboardImageV2Response> gameCenterLeaderboardImagesV2GetInstanceWithHttpInfo(@jakarta.annotation.Nonnull String id, @jakarta.annotation.Nullable List<String> fieldsGameCenterLeaderboardImages, @jakarta.annotation.Nullable List<String> include) throws ApiException {
    return gameCenterLeaderboardImagesV2GetInstanceWithHttpInfo(id, fieldsGameCenterLeaderboardImages, include, null);
  }

  /**
   * 
   * 
   * @param id the id of the requested resource (required)
   * @param fieldsGameCenterLeaderboardImages the fields to include for returned resources of type gameCenterLeaderboardImages (optional)
   * @param include comma-separated list of relationships to include (optional)
   * @param headers Optional headers to include in the request
   * @return ApiResponse&lt;GameCenterLeaderboardImageV2Response&gt;
   * @throws ApiException if fails to make API call
   */
  public ApiResponse<GameCenterLeaderboardImageV2Response> gameCenterLeaderboardImagesV2GetInstanceWithHttpInfo(@jakarta.annotation.Nonnull String id, @jakarta.annotation.Nullable List<String> fieldsGameCenterLeaderboardImages, @jakarta.annotation.Nullable List<String> include, Map<String, String> headers) throws ApiException {
    HttpRequest.Builder localVarRequestBuilder = gameCenterLeaderboardImagesV2GetInstanceRequestBuilder(id, fieldsGameCenterLeaderboardImages, include, headers);
    try {
      HttpResponse<InputStream> localVarResponse = memberVarHttpClient.send(
          localVarRequestBuilder.build(),
          HttpResponse.BodyHandlers.ofInputStream());
      if (memberVarResponseInterceptor != null) {
        memberVarResponseInterceptor.accept(localVarResponse);
      }
      try {
        if (localVarResponse.statusCode()/ 100 != 2) {
          throw getApiException("gameCenterLeaderboardImagesV2GetInstance", localVarResponse);
        }
        if (localVarResponse.body() == null) {
          return new ApiResponse<GameCenterLeaderboardImageV2Response>(
              localVarResponse.statusCode(),
              localVarResponse.headers().map(),
              null
          );
        }

        
        
        String responseBody = new String(localVarResponse.body().readAllBytes());
        GameCenterLeaderboardImageV2Response responseValue = responseBody.isBlank()? null: memberVarObjectMapper.readValue(responseBody, new TypeReference<GameCenterLeaderboardImageV2Response>() {});
        
        localVarResponse.body().close();

        return new ApiResponse<GameCenterLeaderboardImageV2Response>(
            localVarResponse.statusCode(),
            localVarResponse.headers().map(),
            responseValue
        );
      } finally {
      }
    } catch (IOException e) {
      throw new ApiException(e);
    }
    catch (InterruptedException e) {
      Thread.currentThread().interrupt();
      throw new ApiException(e);
    }
  }

  private HttpRequest.Builder gameCenterLeaderboardImagesV2GetInstanceRequestBuilder(@jakarta.annotation.Nonnull String id, @jakarta.annotation.Nullable List<String> fieldsGameCenterLeaderboardImages, @jakarta.annotation.Nullable List<String> include, Map<String, String> headers) throws ApiException {
    // verify the required parameter 'id' is set
    if (id == null) {
      throw new ApiException(400, "Missing the required parameter 'id' when calling gameCenterLeaderboardImagesV2GetInstance");
    }

    HttpRequest.Builder localVarRequestBuilder = HttpRequest.newBuilder();

    String localVarPath = "/v2/gameCenterLeaderboardImages/{id}"
        .replace("{id}", ApiClient.urlEncode(id.toString()));

    List<Pair> localVarQueryParams = new ArrayList<>();
    StringJoiner localVarQueryStringJoiner = new StringJoiner("&");
    String localVarQueryParameterBaseName;
    localVarQueryParameterBaseName = "fields[gameCenterLeaderboardImages]";
    localVarQueryParams.addAll(ApiClient.parameterToPairs("csv", "fields[gameCenterLeaderboardImages]", fieldsGameCenterLeaderboardImages));
    localVarQueryParameterBaseName = "include";
    localVarQueryParams.addAll(ApiClient.parameterToPairs("csv", "include", include));

    if (!localVarQueryParams.isEmpty() || localVarQueryStringJoiner.length() != 0) {
      StringJoiner queryJoiner = new StringJoiner("&");
      localVarQueryParams.forEach(p -> queryJoiner.add(p.getName() + '=' + p.getValue()));
      if (localVarQueryStringJoiner.length() != 0) {
        queryJoiner.add(localVarQueryStringJoiner.toString());
      }
      localVarRequestBuilder.uri(URI.create(memberVarBaseUri + localVarPath + '?' + queryJoiner.toString()));
    } else {
      localVarRequestBuilder.uri(URI.create(memberVarBaseUri + localVarPath));
    }

    localVarRequestBuilder.header("Accept", "application/json");

    localVarRequestBuilder.method("GET", HttpRequest.BodyPublishers.noBody());
    if (memberVarReadTimeout != null) {
      localVarRequestBuilder.timeout(memberVarReadTimeout);
    }
    // Add custom headers if provided
    localVarRequestBuilder = HttpRequestBuilderExtensions.withAdditionalHeaders(localVarRequestBuilder, headers);
    if (memberVarInterceptor != null) {
      memberVarInterceptor.accept(localVarRequestBuilder);
    }
    return localVarRequestBuilder;
  }

  /**
   * 
   * 
   * @param id the id of the requested resource (required)
   * @param gameCenterLeaderboardImageV2UpdateRequest GameCenterLeaderboardImage representation (required)
   * @return GameCenterLeaderboardImageV2Response
   * @throws ApiException if fails to make API call
   */
  public GameCenterLeaderboardImageV2Response gameCenterLeaderboardImagesV2UpdateInstance(@jakarta.annotation.Nonnull String id, @jakarta.annotation.Nonnull GameCenterLeaderboardImageV2UpdateRequest gameCenterLeaderboardImageV2UpdateRequest) throws ApiException {
    return gameCenterLeaderboardImagesV2UpdateInstance(id, gameCenterLeaderboardImageV2UpdateRequest, null);
  }

  /**
   * 
   * 
   * @param id the id of the requested resource (required)
   * @param gameCenterLeaderboardImageV2UpdateRequest GameCenterLeaderboardImage representation (required)
   * @param headers Optional headers to include in the request
   * @return GameCenterLeaderboardImageV2Response
   * @throws ApiException if fails to make API call
   */
  public GameCenterLeaderboardImageV2Response gameCenterLeaderboardImagesV2UpdateInstance(@jakarta.annotation.Nonnull String id, @jakarta.annotation.Nonnull GameCenterLeaderboardImageV2UpdateRequest gameCenterLeaderboardImageV2UpdateRequest, Map<String, String> headers) throws ApiException {
    ApiResponse<GameCenterLeaderboardImageV2Response> localVarResponse = gameCenterLeaderboardImagesV2UpdateInstanceWithHttpInfo(id, gameCenterLeaderboardImageV2UpdateRequest, headers);
    return localVarResponse.getData();
  }

  /**
   * 
   * 
   * @param id the id of the requested resource (required)
   * @param gameCenterLeaderboardImageV2UpdateRequest GameCenterLeaderboardImage representation (required)
   * @return ApiResponse&lt;GameCenterLeaderboardImageV2Response&gt;
   * @throws ApiException if fails to make API call
   */
  public ApiResponse<GameCenterLeaderboardImageV2Response> gameCenterLeaderboardImagesV2UpdateInstanceWithHttpInfo(@jakarta.annotation.Nonnull String id, @jakarta.annotation.Nonnull GameCenterLeaderboardImageV2UpdateRequest gameCenterLeaderboardImageV2UpdateRequest) throws ApiException {
    return gameCenterLeaderboardImagesV2UpdateInstanceWithHttpInfo(id, gameCenterLeaderboardImageV2UpdateRequest, null);
  }

  /**
   * 
   * 
   * @param id the id of the requested resource (required)
   * @param gameCenterLeaderboardImageV2UpdateRequest GameCenterLeaderboardImage representation (required)
   * @param headers Optional headers to include in the request
   * @return ApiResponse&lt;GameCenterLeaderboardImageV2Response&gt;
   * @throws ApiException if fails to make API call
   */
  public ApiResponse<GameCenterLeaderboardImageV2Response> gameCenterLeaderboardImagesV2UpdateInstanceWithHttpInfo(@jakarta.annotation.Nonnull String id, @jakarta.annotation.Nonnull GameCenterLeaderboardImageV2UpdateRequest gameCenterLeaderboardImageV2UpdateRequest, Map<String, String> headers) throws ApiException {
    HttpRequest.Builder localVarRequestBuilder = gameCenterLeaderboardImagesV2UpdateInstanceRequestBuilder(id, gameCenterLeaderboardImageV2UpdateRequest, headers);
    try {
      HttpResponse<InputStream> localVarResponse = memberVarHttpClient.send(
          localVarRequestBuilder.build(),
          HttpResponse.BodyHandlers.ofInputStream());
      if (memberVarResponseInterceptor != null) {
        memberVarResponseInterceptor.accept(localVarResponse);
      }
      try {
        if (localVarResponse.statusCode()/ 100 != 2) {
          throw getApiException("gameCenterLeaderboardImagesV2UpdateInstance", localVarResponse);
        }
        if (localVarResponse.body() == null) {
          return new ApiResponse<GameCenterLeaderboardImageV2Response>(
              localVarResponse.statusCode(),
              localVarResponse.headers().map(),
              null
          );
        }

        
        
        String responseBody = new String(localVarResponse.body().readAllBytes());
        GameCenterLeaderboardImageV2Response responseValue = responseBody.isBlank()? null: memberVarObjectMapper.readValue(responseBody, new TypeReference<GameCenterLeaderboardImageV2Response>() {});
        
        localVarResponse.body().close();

        return new ApiResponse<GameCenterLeaderboardImageV2Response>(
            localVarResponse.statusCode(),
            localVarResponse.headers().map(),
            responseValue
        );
      } finally {
      }
    } catch (IOException e) {
      throw new ApiException(e);
    }
    catch (InterruptedException e) {
      Thread.currentThread().interrupt();
      throw new ApiException(e);
    }
  }

  private HttpRequest.Builder gameCenterLeaderboardImagesV2UpdateInstanceRequestBuilder(@jakarta.annotation.Nonnull String id, @jakarta.annotation.Nonnull GameCenterLeaderboardImageV2UpdateRequest gameCenterLeaderboardImageV2UpdateRequest, Map<String, String> headers) throws ApiException {
    // verify the required parameter 'id' is set
    if (id == null) {
      throw new ApiException(400, "Missing the required parameter 'id' when calling gameCenterLeaderboardImagesV2UpdateInstance");
    }
    // verify the required parameter 'gameCenterLeaderboardImageV2UpdateRequest' is set
    if (gameCenterLeaderboardImageV2UpdateRequest == null) {
      throw new ApiException(400, "Missing the required parameter 'gameCenterLeaderboardImageV2UpdateRequest' when calling gameCenterLeaderboardImagesV2UpdateInstance");
    }

    HttpRequest.Builder localVarRequestBuilder = HttpRequest.newBuilder();

    String localVarPath = "/v2/gameCenterLeaderboardImages/{id}"
        .replace("{id}", ApiClient.urlEncode(id.toString()));

    localVarRequestBuilder.uri(URI.create(memberVarBaseUri + localVarPath));

    localVarRequestBuilder.header("Content-Type", "application/json");
    localVarRequestBuilder.header("Accept", "application/json");

    try {
      byte[] localVarPostBody = memberVarObjectMapper.writeValueAsBytes(gameCenterLeaderboardImageV2UpdateRequest);
      localVarRequestBuilder.method("PATCH", HttpRequest.BodyPublishers.ofByteArray(localVarPostBody));
    } catch (IOException e) {
      throw new ApiException(e);
    }
    if (memberVarReadTimeout != null) {
      localVarRequestBuilder.timeout(memberVarReadTimeout);
    }
    // Add custom headers if provided
    localVarRequestBuilder = HttpRequestBuilderExtensions.withAdditionalHeaders(localVarRequestBuilder, headers);
    if (memberVarInterceptor != null) {
      memberVarInterceptor.accept(localVarRequestBuilder);
    }
    return localVarRequestBuilder;
  }

}
