/*
 * App Store Connect API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 4.2
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

package com.adguard.stores.appstoreconnect.api;

import com.adguard.stores.appstoreconnect.ApiClient;
import com.adguard.stores.appstoreconnect.ApiException;
import com.adguard.stores.appstoreconnect.ApiResponse;
import com.adguard.stores.appstoreconnect.Configuration;
import com.adguard.stores.appstoreconnect.Pair;

import com.adguard.stores.appstoreconnect.model.ErrorResponse;
import com.adguard.stores.appstoreconnect.model.InAppPurchaseAvailabilityAvailableTerritoriesLinkagesResponse;
import com.adguard.stores.appstoreconnect.model.InAppPurchaseAvailabilityCreateRequest;
import com.adguard.stores.appstoreconnect.model.InAppPurchaseAvailabilityResponse;
import com.adguard.stores.appstoreconnect.model.TerritoriesResponse;

import com.fasterxml.jackson.core.type.TypeReference;
import com.fasterxml.jackson.databind.ObjectMapper;

import java.io.InputStream;
import java.io.ByteArrayInputStream;
import java.io.ByteArrayOutputStream;
import java.io.File;
import java.io.IOException;
import java.io.OutputStream;
import java.net.http.HttpRequest;
import java.nio.channels.Channels;
import java.nio.channels.Pipe;
import java.net.URI;
import java.net.http.HttpClient;
import java.net.http.HttpRequest;
import java.net.http.HttpResponse;
import java.time.Duration;

import java.util.ArrayList;
import java.util.StringJoiner;
import java.util.List;
import java.util.Map;
import java.util.Set;
import java.util.Locale;
import java.util.function.Consumer;

@jakarta.annotation.Generated(value = "org.openapitools.codegen.languages.JavaClientCodegen", comments = "Generator version: 7.17.0")
public class InAppPurchaseAvailabilitiesApi {
  /**
   * Utility class for extending HttpRequest.Builder functionality.
   */
  private static class HttpRequestBuilderExtensions {
    /**
     * Adds additional headers to the provided HttpRequest.Builder. Useful for adding method/endpoint specific headers.
     *
     * @param builder the HttpRequest.Builder to which headers will be added
     * @param headers a map of header names and values to add; may be null
     * @return the same HttpRequest.Builder instance with the additional headers set
     */
    static HttpRequest.Builder withAdditionalHeaders(HttpRequest.Builder builder, Map<String, String> headers) {
        if (headers != null) {
            for (Map.Entry<String, String> entry : headers.entrySet()) {
                builder.header(entry.getKey(), entry.getValue());
            }
        }
        return builder;
    }
  }
  private final HttpClient memberVarHttpClient;
  private final ObjectMapper memberVarObjectMapper;
  private final String memberVarBaseUri;
  private final Consumer<HttpRequest.Builder> memberVarInterceptor;
  private final Duration memberVarReadTimeout;
  private final Consumer<HttpResponse<InputStream>> memberVarResponseInterceptor;
  private final Consumer<HttpResponse<String>> memberVarAsyncResponseInterceptor;

  public InAppPurchaseAvailabilitiesApi() {
    this(Configuration.getDefaultApiClient());
  }

  public InAppPurchaseAvailabilitiesApi(ApiClient apiClient) {
    memberVarHttpClient = apiClient.getHttpClient();
    memberVarObjectMapper = apiClient.getObjectMapper();
    memberVarBaseUri = apiClient.getBaseUri();
    memberVarInterceptor = apiClient.getRequestInterceptor();
    memberVarReadTimeout = apiClient.getReadTimeout();
    memberVarResponseInterceptor = apiClient.getResponseInterceptor();
    memberVarAsyncResponseInterceptor = apiClient.getAsyncResponseInterceptor();
  }


  protected ApiException getApiException(String operationId, HttpResponse<InputStream> response) throws IOException {
    String body = response.body() == null ? null : new String(response.body().readAllBytes());
    String message = formatExceptionMessage(operationId, response.statusCode(), body);
    return new ApiException(response.statusCode(), message, response.headers(), body);
  }

  private String formatExceptionMessage(String operationId, int statusCode, String body) {
    if (body == null || body.isEmpty()) {
      body = "[no body]";
    }
    return operationId + " call failed with: " + statusCode + " - " + body;
  }

  /**
   * Download file from the given response.
   *
   * @param response Response
   * @return File
   * @throws ApiException If fail to read file content from response and write to disk
   */
  public File downloadFileFromResponse(HttpResponse<InputStream> response) throws ApiException {
    try {
      File file = prepareDownloadFile(response);
      java.nio.file.Files.copy(response.body(), file.toPath(), java.nio.file.StandardCopyOption.REPLACE_EXISTING);
      return file;
    } catch (IOException e) {
      throw new ApiException(e);
    }
  }

  /**
   * <p>Prepare the file for download from the response.</p>
   *
   * @param response a {@link java.net.http.HttpResponse} object.
   * @return a {@link java.io.File} object.
   * @throws java.io.IOException if any.
   */
  private File prepareDownloadFile(HttpResponse<InputStream> response) throws IOException {
    String filename = null;
    java.util.Optional<String> contentDisposition = response.headers().firstValue("Content-Disposition");
    if (contentDisposition.isPresent() && !"".equals(contentDisposition.get())) {
      // Get filename from the Content-Disposition header.
      java.util.regex.Pattern pattern = java.util.regex.Pattern.compile("filename=['\"]?([^'\"\\s]+)['\"]?");
      java.util.regex.Matcher matcher = pattern.matcher(contentDisposition.get());
      if (matcher.find())
        filename = matcher.group(1);
    }
    File file = null;
    if (filename != null) {
      java.nio.file.Path tempDir = java.nio.file.Files.createTempDirectory("swagger-gen-native");
      java.nio.file.Path filePath = java.nio.file.Files.createFile(tempDir.resolve(filename));
      file = filePath.toFile();
      tempDir.toFile().deleteOnExit();   // best effort cleanup
      file.deleteOnExit(); // best effort cleanup
    } else {
      file = java.nio.file.Files.createTempFile("download-", "").toFile();
      file.deleteOnExit(); // best effort cleanup
    }
    return file;
  }

  /**
   * 
   * 
   * @param id the id of the requested resource (required)
   * @param fieldsTerritories the fields to include for returned resources of type territories (optional)
   * @param limit maximum resources per page (optional)
   * @return TerritoriesResponse
   * @throws ApiException if fails to make API call
   */
  public TerritoriesResponse inAppPurchaseAvailabilitiesAvailableTerritoriesGetToManyRelated(@jakarta.annotation.Nonnull String id, @jakarta.annotation.Nullable List<String> fieldsTerritories, @jakarta.annotation.Nullable Integer limit) throws ApiException {
    return inAppPurchaseAvailabilitiesAvailableTerritoriesGetToManyRelated(id, fieldsTerritories, limit, null);
  }

  /**
   * 
   * 
   * @param id the id of the requested resource (required)
   * @param fieldsTerritories the fields to include for returned resources of type territories (optional)
   * @param limit maximum resources per page (optional)
   * @param headers Optional headers to include in the request
   * @return TerritoriesResponse
   * @throws ApiException if fails to make API call
   */
  public TerritoriesResponse inAppPurchaseAvailabilitiesAvailableTerritoriesGetToManyRelated(@jakarta.annotation.Nonnull String id, @jakarta.annotation.Nullable List<String> fieldsTerritories, @jakarta.annotation.Nullable Integer limit, Map<String, String> headers) throws ApiException {
    ApiResponse<TerritoriesResponse> localVarResponse = inAppPurchaseAvailabilitiesAvailableTerritoriesGetToManyRelatedWithHttpInfo(id, fieldsTerritories, limit, headers);
    return localVarResponse.getData();
  }

  /**
   * 
   * 
   * @param id the id of the requested resource (required)
   * @param fieldsTerritories the fields to include for returned resources of type territories (optional)
   * @param limit maximum resources per page (optional)
   * @return ApiResponse&lt;TerritoriesResponse&gt;
   * @throws ApiException if fails to make API call
   */
  public ApiResponse<TerritoriesResponse> inAppPurchaseAvailabilitiesAvailableTerritoriesGetToManyRelatedWithHttpInfo(@jakarta.annotation.Nonnull String id, @jakarta.annotation.Nullable List<String> fieldsTerritories, @jakarta.annotation.Nullable Integer limit) throws ApiException {
    return inAppPurchaseAvailabilitiesAvailableTerritoriesGetToManyRelatedWithHttpInfo(id, fieldsTerritories, limit, null);
  }

  /**
   * 
   * 
   * @param id the id of the requested resource (required)
   * @param fieldsTerritories the fields to include for returned resources of type territories (optional)
   * @param limit maximum resources per page (optional)
   * @param headers Optional headers to include in the request
   * @return ApiResponse&lt;TerritoriesResponse&gt;
   * @throws ApiException if fails to make API call
   */
  public ApiResponse<TerritoriesResponse> inAppPurchaseAvailabilitiesAvailableTerritoriesGetToManyRelatedWithHttpInfo(@jakarta.annotation.Nonnull String id, @jakarta.annotation.Nullable List<String> fieldsTerritories, @jakarta.annotation.Nullable Integer limit, Map<String, String> headers) throws ApiException {
    HttpRequest.Builder localVarRequestBuilder = inAppPurchaseAvailabilitiesAvailableTerritoriesGetToManyRelatedRequestBuilder(id, fieldsTerritories, limit, headers);
    try {
      HttpResponse<InputStream> localVarResponse = memberVarHttpClient.send(
          localVarRequestBuilder.build(),
          HttpResponse.BodyHandlers.ofInputStream());
      if (memberVarResponseInterceptor != null) {
        memberVarResponseInterceptor.accept(localVarResponse);
      }
      try {
        if (localVarResponse.statusCode()/ 100 != 2) {
          throw getApiException("inAppPurchaseAvailabilitiesAvailableTerritoriesGetToManyRelated", localVarResponse);
        }
        if (localVarResponse.body() == null) {
          return new ApiResponse<TerritoriesResponse>(
              localVarResponse.statusCode(),
              localVarResponse.headers().map(),
              null
          );
        }

        
        
        String responseBody = new String(localVarResponse.body().readAllBytes());
        TerritoriesResponse responseValue = responseBody.isBlank()? null: memberVarObjectMapper.readValue(responseBody, new TypeReference<TerritoriesResponse>() {});
        
        localVarResponse.body().close();

        return new ApiResponse<TerritoriesResponse>(
            localVarResponse.statusCode(),
            localVarResponse.headers().map(),
            responseValue
        );
      } finally {
      }
    } catch (IOException e) {
      throw new ApiException(e);
    }
    catch (InterruptedException e) {
      Thread.currentThread().interrupt();
      throw new ApiException(e);
    }
  }

  private HttpRequest.Builder inAppPurchaseAvailabilitiesAvailableTerritoriesGetToManyRelatedRequestBuilder(@jakarta.annotation.Nonnull String id, @jakarta.annotation.Nullable List<String> fieldsTerritories, @jakarta.annotation.Nullable Integer limit, Map<String, String> headers) throws ApiException {
    // verify the required parameter 'id' is set
    if (id == null) {
      throw new ApiException(400, "Missing the required parameter 'id' when calling inAppPurchaseAvailabilitiesAvailableTerritoriesGetToManyRelated");
    }

    HttpRequest.Builder localVarRequestBuilder = HttpRequest.newBuilder();

    String localVarPath = "/v1/inAppPurchaseAvailabilities/{id}/availableTerritories"
        .replace("{id}", ApiClient.urlEncode(id.toString()));

    List<Pair> localVarQueryParams = new ArrayList<>();
    StringJoiner localVarQueryStringJoiner = new StringJoiner("&");
    String localVarQueryParameterBaseName;
    localVarQueryParameterBaseName = "fields[territories]";
    localVarQueryParams.addAll(ApiClient.parameterToPairs("csv", "fields[territories]", fieldsTerritories));
    localVarQueryParameterBaseName = "limit";
    localVarQueryParams.addAll(ApiClient.parameterToPairs("limit", limit));

    if (!localVarQueryParams.isEmpty() || localVarQueryStringJoiner.length() != 0) {
      StringJoiner queryJoiner = new StringJoiner("&");
      localVarQueryParams.forEach(p -> queryJoiner.add(p.getName() + '=' + p.getValue()));
      if (localVarQueryStringJoiner.length() != 0) {
        queryJoiner.add(localVarQueryStringJoiner.toString());
      }
      localVarRequestBuilder.uri(URI.create(memberVarBaseUri + localVarPath + '?' + queryJoiner.toString()));
    } else {
      localVarRequestBuilder.uri(URI.create(memberVarBaseUri + localVarPath));
    }

    localVarRequestBuilder.header("Accept", "application/json");

    localVarRequestBuilder.method("GET", HttpRequest.BodyPublishers.noBody());
    if (memberVarReadTimeout != null) {
      localVarRequestBuilder.timeout(memberVarReadTimeout);
    }
    // Add custom headers if provided
    localVarRequestBuilder = HttpRequestBuilderExtensions.withAdditionalHeaders(localVarRequestBuilder, headers);
    if (memberVarInterceptor != null) {
      memberVarInterceptor.accept(localVarRequestBuilder);
    }
    return localVarRequestBuilder;
  }

  /**
   * 
   * 
   * @param id the id of the requested resource (required)
   * @param limit maximum resources per page (optional)
   * @return InAppPurchaseAvailabilityAvailableTerritoriesLinkagesResponse
   * @throws ApiException if fails to make API call
   */
  public InAppPurchaseAvailabilityAvailableTerritoriesLinkagesResponse inAppPurchaseAvailabilitiesAvailableTerritoriesGetToManyRelationship(@jakarta.annotation.Nonnull String id, @jakarta.annotation.Nullable Integer limit) throws ApiException {
    return inAppPurchaseAvailabilitiesAvailableTerritoriesGetToManyRelationship(id, limit, null);
  }

  /**
   * 
   * 
   * @param id the id of the requested resource (required)
   * @param limit maximum resources per page (optional)
   * @param headers Optional headers to include in the request
   * @return InAppPurchaseAvailabilityAvailableTerritoriesLinkagesResponse
   * @throws ApiException if fails to make API call
   */
  public InAppPurchaseAvailabilityAvailableTerritoriesLinkagesResponse inAppPurchaseAvailabilitiesAvailableTerritoriesGetToManyRelationship(@jakarta.annotation.Nonnull String id, @jakarta.annotation.Nullable Integer limit, Map<String, String> headers) throws ApiException {
    ApiResponse<InAppPurchaseAvailabilityAvailableTerritoriesLinkagesResponse> localVarResponse = inAppPurchaseAvailabilitiesAvailableTerritoriesGetToManyRelationshipWithHttpInfo(id, limit, headers);
    return localVarResponse.getData();
  }

  /**
   * 
   * 
   * @param id the id of the requested resource (required)
   * @param limit maximum resources per page (optional)
   * @return ApiResponse&lt;InAppPurchaseAvailabilityAvailableTerritoriesLinkagesResponse&gt;
   * @throws ApiException if fails to make API call
   */
  public ApiResponse<InAppPurchaseAvailabilityAvailableTerritoriesLinkagesResponse> inAppPurchaseAvailabilitiesAvailableTerritoriesGetToManyRelationshipWithHttpInfo(@jakarta.annotation.Nonnull String id, @jakarta.annotation.Nullable Integer limit) throws ApiException {
    return inAppPurchaseAvailabilitiesAvailableTerritoriesGetToManyRelationshipWithHttpInfo(id, limit, null);
  }

  /**
   * 
   * 
   * @param id the id of the requested resource (required)
   * @param limit maximum resources per page (optional)
   * @param headers Optional headers to include in the request
   * @return ApiResponse&lt;InAppPurchaseAvailabilityAvailableTerritoriesLinkagesResponse&gt;
   * @throws ApiException if fails to make API call
   */
  public ApiResponse<InAppPurchaseAvailabilityAvailableTerritoriesLinkagesResponse> inAppPurchaseAvailabilitiesAvailableTerritoriesGetToManyRelationshipWithHttpInfo(@jakarta.annotation.Nonnull String id, @jakarta.annotation.Nullable Integer limit, Map<String, String> headers) throws ApiException {
    HttpRequest.Builder localVarRequestBuilder = inAppPurchaseAvailabilitiesAvailableTerritoriesGetToManyRelationshipRequestBuilder(id, limit, headers);
    try {
      HttpResponse<InputStream> localVarResponse = memberVarHttpClient.send(
          localVarRequestBuilder.build(),
          HttpResponse.BodyHandlers.ofInputStream());
      if (memberVarResponseInterceptor != null) {
        memberVarResponseInterceptor.accept(localVarResponse);
      }
      try {
        if (localVarResponse.statusCode()/ 100 != 2) {
          throw getApiException("inAppPurchaseAvailabilitiesAvailableTerritoriesGetToManyRelationship", localVarResponse);
        }
        if (localVarResponse.body() == null) {
          return new ApiResponse<InAppPurchaseAvailabilityAvailableTerritoriesLinkagesResponse>(
              localVarResponse.statusCode(),
              localVarResponse.headers().map(),
              null
          );
        }

        
        
        String responseBody = new String(localVarResponse.body().readAllBytes());
        InAppPurchaseAvailabilityAvailableTerritoriesLinkagesResponse responseValue = responseBody.isBlank()? null: memberVarObjectMapper.readValue(responseBody, new TypeReference<InAppPurchaseAvailabilityAvailableTerritoriesLinkagesResponse>() {});
        
        localVarResponse.body().close();

        return new ApiResponse<InAppPurchaseAvailabilityAvailableTerritoriesLinkagesResponse>(
            localVarResponse.statusCode(),
            localVarResponse.headers().map(),
            responseValue
        );
      } finally {
      }
    } catch (IOException e) {
      throw new ApiException(e);
    }
    catch (InterruptedException e) {
      Thread.currentThread().interrupt();
      throw new ApiException(e);
    }
  }

  private HttpRequest.Builder inAppPurchaseAvailabilitiesAvailableTerritoriesGetToManyRelationshipRequestBuilder(@jakarta.annotation.Nonnull String id, @jakarta.annotation.Nullable Integer limit, Map<String, String> headers) throws ApiException {
    // verify the required parameter 'id' is set
    if (id == null) {
      throw new ApiException(400, "Missing the required parameter 'id' when calling inAppPurchaseAvailabilitiesAvailableTerritoriesGetToManyRelationship");
    }

    HttpRequest.Builder localVarRequestBuilder = HttpRequest.newBuilder();

    String localVarPath = "/v1/inAppPurchaseAvailabilities/{id}/relationships/availableTerritories"
        .replace("{id}", ApiClient.urlEncode(id.toString()));

    List<Pair> localVarQueryParams = new ArrayList<>();
    StringJoiner localVarQueryStringJoiner = new StringJoiner("&");
    String localVarQueryParameterBaseName;
    localVarQueryParameterBaseName = "limit";
    localVarQueryParams.addAll(ApiClient.parameterToPairs("limit", limit));

    if (!localVarQueryParams.isEmpty() || localVarQueryStringJoiner.length() != 0) {
      StringJoiner queryJoiner = new StringJoiner("&");
      localVarQueryParams.forEach(p -> queryJoiner.add(p.getName() + '=' + p.getValue()));
      if (localVarQueryStringJoiner.length() != 0) {
        queryJoiner.add(localVarQueryStringJoiner.toString());
      }
      localVarRequestBuilder.uri(URI.create(memberVarBaseUri + localVarPath + '?' + queryJoiner.toString()));
    } else {
      localVarRequestBuilder.uri(URI.create(memberVarBaseUri + localVarPath));
    }

    localVarRequestBuilder.header("Accept", "application/json");

    localVarRequestBuilder.method("GET", HttpRequest.BodyPublishers.noBody());
    if (memberVarReadTimeout != null) {
      localVarRequestBuilder.timeout(memberVarReadTimeout);
    }
    // Add custom headers if provided
    localVarRequestBuilder = HttpRequestBuilderExtensions.withAdditionalHeaders(localVarRequestBuilder, headers);
    if (memberVarInterceptor != null) {
      memberVarInterceptor.accept(localVarRequestBuilder);
    }
    return localVarRequestBuilder;
  }

  /**
   * 
   * 
   * @param inAppPurchaseAvailabilityCreateRequest InAppPurchaseAvailability representation (required)
   * @return InAppPurchaseAvailabilityResponse
   * @throws ApiException if fails to make API call
   */
  public InAppPurchaseAvailabilityResponse inAppPurchaseAvailabilitiesCreateInstance(@jakarta.annotation.Nonnull InAppPurchaseAvailabilityCreateRequest inAppPurchaseAvailabilityCreateRequest) throws ApiException {
    return inAppPurchaseAvailabilitiesCreateInstance(inAppPurchaseAvailabilityCreateRequest, null);
  }

  /**
   * 
   * 
   * @param inAppPurchaseAvailabilityCreateRequest InAppPurchaseAvailability representation (required)
   * @param headers Optional headers to include in the request
   * @return InAppPurchaseAvailabilityResponse
   * @throws ApiException if fails to make API call
   */
  public InAppPurchaseAvailabilityResponse inAppPurchaseAvailabilitiesCreateInstance(@jakarta.annotation.Nonnull InAppPurchaseAvailabilityCreateRequest inAppPurchaseAvailabilityCreateRequest, Map<String, String> headers) throws ApiException {
    ApiResponse<InAppPurchaseAvailabilityResponse> localVarResponse = inAppPurchaseAvailabilitiesCreateInstanceWithHttpInfo(inAppPurchaseAvailabilityCreateRequest, headers);
    return localVarResponse.getData();
  }

  /**
   * 
   * 
   * @param inAppPurchaseAvailabilityCreateRequest InAppPurchaseAvailability representation (required)
   * @return ApiResponse&lt;InAppPurchaseAvailabilityResponse&gt;
   * @throws ApiException if fails to make API call
   */
  public ApiResponse<InAppPurchaseAvailabilityResponse> inAppPurchaseAvailabilitiesCreateInstanceWithHttpInfo(@jakarta.annotation.Nonnull InAppPurchaseAvailabilityCreateRequest inAppPurchaseAvailabilityCreateRequest) throws ApiException {
    return inAppPurchaseAvailabilitiesCreateInstanceWithHttpInfo(inAppPurchaseAvailabilityCreateRequest, null);
  }

  /**
   * 
   * 
   * @param inAppPurchaseAvailabilityCreateRequest InAppPurchaseAvailability representation (required)
   * @param headers Optional headers to include in the request
   * @return ApiResponse&lt;InAppPurchaseAvailabilityResponse&gt;
   * @throws ApiException if fails to make API call
   */
  public ApiResponse<InAppPurchaseAvailabilityResponse> inAppPurchaseAvailabilitiesCreateInstanceWithHttpInfo(@jakarta.annotation.Nonnull InAppPurchaseAvailabilityCreateRequest inAppPurchaseAvailabilityCreateRequest, Map<String, String> headers) throws ApiException {
    HttpRequest.Builder localVarRequestBuilder = inAppPurchaseAvailabilitiesCreateInstanceRequestBuilder(inAppPurchaseAvailabilityCreateRequest, headers);
    try {
      HttpResponse<InputStream> localVarResponse = memberVarHttpClient.send(
          localVarRequestBuilder.build(),
          HttpResponse.BodyHandlers.ofInputStream());
      if (memberVarResponseInterceptor != null) {
        memberVarResponseInterceptor.accept(localVarResponse);
      }
      try {
        if (localVarResponse.statusCode()/ 100 != 2) {
          throw getApiException("inAppPurchaseAvailabilitiesCreateInstance", localVarResponse);
        }
        if (localVarResponse.body() == null) {
          return new ApiResponse<InAppPurchaseAvailabilityResponse>(
              localVarResponse.statusCode(),
              localVarResponse.headers().map(),
              null
          );
        }

        
        
        String responseBody = new String(localVarResponse.body().readAllBytes());
        InAppPurchaseAvailabilityResponse responseValue = responseBody.isBlank()? null: memberVarObjectMapper.readValue(responseBody, new TypeReference<InAppPurchaseAvailabilityResponse>() {});
        
        localVarResponse.body().close();

        return new ApiResponse<InAppPurchaseAvailabilityResponse>(
            localVarResponse.statusCode(),
            localVarResponse.headers().map(),
            responseValue
        );
      } finally {
      }
    } catch (IOException e) {
      throw new ApiException(e);
    }
    catch (InterruptedException e) {
      Thread.currentThread().interrupt();
      throw new ApiException(e);
    }
  }

  private HttpRequest.Builder inAppPurchaseAvailabilitiesCreateInstanceRequestBuilder(@jakarta.annotation.Nonnull InAppPurchaseAvailabilityCreateRequest inAppPurchaseAvailabilityCreateRequest, Map<String, String> headers) throws ApiException {
    // verify the required parameter 'inAppPurchaseAvailabilityCreateRequest' is set
    if (inAppPurchaseAvailabilityCreateRequest == null) {
      throw new ApiException(400, "Missing the required parameter 'inAppPurchaseAvailabilityCreateRequest' when calling inAppPurchaseAvailabilitiesCreateInstance");
    }

    HttpRequest.Builder localVarRequestBuilder = HttpRequest.newBuilder();

    String localVarPath = "/v1/inAppPurchaseAvailabilities";

    localVarRequestBuilder.uri(URI.create(memberVarBaseUri + localVarPath));

    localVarRequestBuilder.header("Content-Type", "application/json");
    localVarRequestBuilder.header("Accept", "application/json");

    try {
      byte[] localVarPostBody = memberVarObjectMapper.writeValueAsBytes(inAppPurchaseAvailabilityCreateRequest);
      localVarRequestBuilder.method("POST", HttpRequest.BodyPublishers.ofByteArray(localVarPostBody));
    } catch (IOException e) {
      throw new ApiException(e);
    }
    if (memberVarReadTimeout != null) {
      localVarRequestBuilder.timeout(memberVarReadTimeout);
    }
    // Add custom headers if provided
    localVarRequestBuilder = HttpRequestBuilderExtensions.withAdditionalHeaders(localVarRequestBuilder, headers);
    if (memberVarInterceptor != null) {
      memberVarInterceptor.accept(localVarRequestBuilder);
    }
    return localVarRequestBuilder;
  }

  /**
   * 
   * 
   * @param id the id of the requested resource (required)
   * @param fieldsInAppPurchaseAvailabilities the fields to include for returned resources of type inAppPurchaseAvailabilities (optional)
   * @param fieldsTerritories the fields to include for returned resources of type territories (optional)
   * @param include comma-separated list of relationships to include (optional)
   * @param limitAvailableTerritories maximum number of related availableTerritories returned (when they are included) (optional)
   * @return InAppPurchaseAvailabilityResponse
   * @throws ApiException if fails to make API call
   */
  public InAppPurchaseAvailabilityResponse inAppPurchaseAvailabilitiesGetInstance(@jakarta.annotation.Nonnull String id, @jakarta.annotation.Nullable List<String> fieldsInAppPurchaseAvailabilities, @jakarta.annotation.Nullable List<String> fieldsTerritories, @jakarta.annotation.Nullable List<String> include, @jakarta.annotation.Nullable Integer limitAvailableTerritories) throws ApiException {
    return inAppPurchaseAvailabilitiesGetInstance(id, fieldsInAppPurchaseAvailabilities, fieldsTerritories, include, limitAvailableTerritories, null);
  }

  /**
   * 
   * 
   * @param id the id of the requested resource (required)
   * @param fieldsInAppPurchaseAvailabilities the fields to include for returned resources of type inAppPurchaseAvailabilities (optional)
   * @param fieldsTerritories the fields to include for returned resources of type territories (optional)
   * @param include comma-separated list of relationships to include (optional)
   * @param limitAvailableTerritories maximum number of related availableTerritories returned (when they are included) (optional)
   * @param headers Optional headers to include in the request
   * @return InAppPurchaseAvailabilityResponse
   * @throws ApiException if fails to make API call
   */
  public InAppPurchaseAvailabilityResponse inAppPurchaseAvailabilitiesGetInstance(@jakarta.annotation.Nonnull String id, @jakarta.annotation.Nullable List<String> fieldsInAppPurchaseAvailabilities, @jakarta.annotation.Nullable List<String> fieldsTerritories, @jakarta.annotation.Nullable List<String> include, @jakarta.annotation.Nullable Integer limitAvailableTerritories, Map<String, String> headers) throws ApiException {
    ApiResponse<InAppPurchaseAvailabilityResponse> localVarResponse = inAppPurchaseAvailabilitiesGetInstanceWithHttpInfo(id, fieldsInAppPurchaseAvailabilities, fieldsTerritories, include, limitAvailableTerritories, headers);
    return localVarResponse.getData();
  }

  /**
   * 
   * 
   * @param id the id of the requested resource (required)
   * @param fieldsInAppPurchaseAvailabilities the fields to include for returned resources of type inAppPurchaseAvailabilities (optional)
   * @param fieldsTerritories the fields to include for returned resources of type territories (optional)
   * @param include comma-separated list of relationships to include (optional)
   * @param limitAvailableTerritories maximum number of related availableTerritories returned (when they are included) (optional)
   * @return ApiResponse&lt;InAppPurchaseAvailabilityResponse&gt;
   * @throws ApiException if fails to make API call
   */
  public ApiResponse<InAppPurchaseAvailabilityResponse> inAppPurchaseAvailabilitiesGetInstanceWithHttpInfo(@jakarta.annotation.Nonnull String id, @jakarta.annotation.Nullable List<String> fieldsInAppPurchaseAvailabilities, @jakarta.annotation.Nullable List<String> fieldsTerritories, @jakarta.annotation.Nullable List<String> include, @jakarta.annotation.Nullable Integer limitAvailableTerritories) throws ApiException {
    return inAppPurchaseAvailabilitiesGetInstanceWithHttpInfo(id, fieldsInAppPurchaseAvailabilities, fieldsTerritories, include, limitAvailableTerritories, null);
  }

  /**
   * 
   * 
   * @param id the id of the requested resource (required)
   * @param fieldsInAppPurchaseAvailabilities the fields to include for returned resources of type inAppPurchaseAvailabilities (optional)
   * @param fieldsTerritories the fields to include for returned resources of type territories (optional)
   * @param include comma-separated list of relationships to include (optional)
   * @param limitAvailableTerritories maximum number of related availableTerritories returned (when they are included) (optional)
   * @param headers Optional headers to include in the request
   * @return ApiResponse&lt;InAppPurchaseAvailabilityResponse&gt;
   * @throws ApiException if fails to make API call
   */
  public ApiResponse<InAppPurchaseAvailabilityResponse> inAppPurchaseAvailabilitiesGetInstanceWithHttpInfo(@jakarta.annotation.Nonnull String id, @jakarta.annotation.Nullable List<String> fieldsInAppPurchaseAvailabilities, @jakarta.annotation.Nullable List<String> fieldsTerritories, @jakarta.annotation.Nullable List<String> include, @jakarta.annotation.Nullable Integer limitAvailableTerritories, Map<String, String> headers) throws ApiException {
    HttpRequest.Builder localVarRequestBuilder = inAppPurchaseAvailabilitiesGetInstanceRequestBuilder(id, fieldsInAppPurchaseAvailabilities, fieldsTerritories, include, limitAvailableTerritories, headers);
    try {
      HttpResponse<InputStream> localVarResponse = memberVarHttpClient.send(
          localVarRequestBuilder.build(),
          HttpResponse.BodyHandlers.ofInputStream());
      if (memberVarResponseInterceptor != null) {
        memberVarResponseInterceptor.accept(localVarResponse);
      }
      try {
        if (localVarResponse.statusCode()/ 100 != 2) {
          throw getApiException("inAppPurchaseAvailabilitiesGetInstance", localVarResponse);
        }
        if (localVarResponse.body() == null) {
          return new ApiResponse<InAppPurchaseAvailabilityResponse>(
              localVarResponse.statusCode(),
              localVarResponse.headers().map(),
              null
          );
        }

        
        
        String responseBody = new String(localVarResponse.body().readAllBytes());
        InAppPurchaseAvailabilityResponse responseValue = responseBody.isBlank()? null: memberVarObjectMapper.readValue(responseBody, new TypeReference<InAppPurchaseAvailabilityResponse>() {});
        
        localVarResponse.body().close();

        return new ApiResponse<InAppPurchaseAvailabilityResponse>(
            localVarResponse.statusCode(),
            localVarResponse.headers().map(),
            responseValue
        );
      } finally {
      }
    } catch (IOException e) {
      throw new ApiException(e);
    }
    catch (InterruptedException e) {
      Thread.currentThread().interrupt();
      throw new ApiException(e);
    }
  }

  private HttpRequest.Builder inAppPurchaseAvailabilitiesGetInstanceRequestBuilder(@jakarta.annotation.Nonnull String id, @jakarta.annotation.Nullable List<String> fieldsInAppPurchaseAvailabilities, @jakarta.annotation.Nullable List<String> fieldsTerritories, @jakarta.annotation.Nullable List<String> include, @jakarta.annotation.Nullable Integer limitAvailableTerritories, Map<String, String> headers) throws ApiException {
    // verify the required parameter 'id' is set
    if (id == null) {
      throw new ApiException(400, "Missing the required parameter 'id' when calling inAppPurchaseAvailabilitiesGetInstance");
    }

    HttpRequest.Builder localVarRequestBuilder = HttpRequest.newBuilder();

    String localVarPath = "/v1/inAppPurchaseAvailabilities/{id}"
        .replace("{id}", ApiClient.urlEncode(id.toString()));

    List<Pair> localVarQueryParams = new ArrayList<>();
    StringJoiner localVarQueryStringJoiner = new StringJoiner("&");
    String localVarQueryParameterBaseName;
    localVarQueryParameterBaseName = "fields[inAppPurchaseAvailabilities]";
    localVarQueryParams.addAll(ApiClient.parameterToPairs("csv", "fields[inAppPurchaseAvailabilities]", fieldsInAppPurchaseAvailabilities));
    localVarQueryParameterBaseName = "fields[territories]";
    localVarQueryParams.addAll(ApiClient.parameterToPairs("csv", "fields[territories]", fieldsTerritories));
    localVarQueryParameterBaseName = "include";
    localVarQueryParams.addAll(ApiClient.parameterToPairs("csv", "include", include));
    localVarQueryParameterBaseName = "limit[availableTerritories]";
    localVarQueryParams.addAll(ApiClient.parameterToPairs("limit[availableTerritories]", limitAvailableTerritories));

    if (!localVarQueryParams.isEmpty() || localVarQueryStringJoiner.length() != 0) {
      StringJoiner queryJoiner = new StringJoiner("&");
      localVarQueryParams.forEach(p -> queryJoiner.add(p.getName() + '=' + p.getValue()));
      if (localVarQueryStringJoiner.length() != 0) {
        queryJoiner.add(localVarQueryStringJoiner.toString());
      }
      localVarRequestBuilder.uri(URI.create(memberVarBaseUri + localVarPath + '?' + queryJoiner.toString()));
    } else {
      localVarRequestBuilder.uri(URI.create(memberVarBaseUri + localVarPath));
    }

    localVarRequestBuilder.header("Accept", "application/json");

    localVarRequestBuilder.method("GET", HttpRequest.BodyPublishers.noBody());
    if (memberVarReadTimeout != null) {
      localVarRequestBuilder.timeout(memberVarReadTimeout);
    }
    // Add custom headers if provided
    localVarRequestBuilder = HttpRequestBuilderExtensions.withAdditionalHeaders(localVarRequestBuilder, headers);
    if (memberVarInterceptor != null) {
      memberVarInterceptor.accept(localVarRequestBuilder);
    }
    return localVarRequestBuilder;
  }

}
