/*
 * App Store Connect API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 4.2
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

package com.adguard.stores.appstoreconnect.api;

import com.adguard.stores.appstoreconnect.ApiClient;
import com.adguard.stores.appstoreconnect.ApiException;
import com.adguard.stores.appstoreconnect.ApiResponse;
import com.adguard.stores.appstoreconnect.Configuration;
import com.adguard.stores.appstoreconnect.Pair;

import com.adguard.stores.appstoreconnect.model.CertificatesResponse;
import com.adguard.stores.appstoreconnect.model.ErrorResponse;
import com.adguard.stores.appstoreconnect.model.MerchantIdCertificatesLinkagesResponse;
import com.adguard.stores.appstoreconnect.model.MerchantIdCreateRequest;
import com.adguard.stores.appstoreconnect.model.MerchantIdResponse;
import com.adguard.stores.appstoreconnect.model.MerchantIdUpdateRequest;
import com.adguard.stores.appstoreconnect.model.MerchantIdsResponse;

import com.fasterxml.jackson.core.type.TypeReference;
import com.fasterxml.jackson.databind.ObjectMapper;

import java.io.InputStream;
import java.io.ByteArrayInputStream;
import java.io.ByteArrayOutputStream;
import java.io.File;
import java.io.IOException;
import java.io.OutputStream;
import java.net.http.HttpRequest;
import java.nio.channels.Channels;
import java.nio.channels.Pipe;
import java.net.URI;
import java.net.http.HttpClient;
import java.net.http.HttpRequest;
import java.net.http.HttpResponse;
import java.time.Duration;

import java.util.ArrayList;
import java.util.StringJoiner;
import java.util.List;
import java.util.Map;
import java.util.Set;
import java.util.Locale;
import java.util.function.Consumer;

@jakarta.annotation.Generated(value = "org.openapitools.codegen.languages.JavaClientCodegen", comments = "Generator version: 7.17.0")
public class MerchantIdsApi {
  /**
   * Utility class for extending HttpRequest.Builder functionality.
   */
  private static class HttpRequestBuilderExtensions {
    /**
     * Adds additional headers to the provided HttpRequest.Builder. Useful for adding method/endpoint specific headers.
     *
     * @param builder the HttpRequest.Builder to which headers will be added
     * @param headers a map of header names and values to add; may be null
     * @return the same HttpRequest.Builder instance with the additional headers set
     */
    static HttpRequest.Builder withAdditionalHeaders(HttpRequest.Builder builder, Map<String, String> headers) {
        if (headers != null) {
            for (Map.Entry<String, String> entry : headers.entrySet()) {
                builder.header(entry.getKey(), entry.getValue());
            }
        }
        return builder;
    }
  }
  private final HttpClient memberVarHttpClient;
  private final ObjectMapper memberVarObjectMapper;
  private final String memberVarBaseUri;
  private final Consumer<HttpRequest.Builder> memberVarInterceptor;
  private final Duration memberVarReadTimeout;
  private final Consumer<HttpResponse<InputStream>> memberVarResponseInterceptor;
  private final Consumer<HttpResponse<String>> memberVarAsyncResponseInterceptor;

  public MerchantIdsApi() {
    this(Configuration.getDefaultApiClient());
  }

  public MerchantIdsApi(ApiClient apiClient) {
    memberVarHttpClient = apiClient.getHttpClient();
    memberVarObjectMapper = apiClient.getObjectMapper();
    memberVarBaseUri = apiClient.getBaseUri();
    memberVarInterceptor = apiClient.getRequestInterceptor();
    memberVarReadTimeout = apiClient.getReadTimeout();
    memberVarResponseInterceptor = apiClient.getResponseInterceptor();
    memberVarAsyncResponseInterceptor = apiClient.getAsyncResponseInterceptor();
  }


  protected ApiException getApiException(String operationId, HttpResponse<InputStream> response) throws IOException {
    String body = response.body() == null ? null : new String(response.body().readAllBytes());
    String message = formatExceptionMessage(operationId, response.statusCode(), body);
    return new ApiException(response.statusCode(), message, response.headers(), body);
  }

  private String formatExceptionMessage(String operationId, int statusCode, String body) {
    if (body == null || body.isEmpty()) {
      body = "[no body]";
    }
    return operationId + " call failed with: " + statusCode + " - " + body;
  }

  /**
   * Download file from the given response.
   *
   * @param response Response
   * @return File
   * @throws ApiException If fail to read file content from response and write to disk
   */
  public File downloadFileFromResponse(HttpResponse<InputStream> response) throws ApiException {
    try {
      File file = prepareDownloadFile(response);
      java.nio.file.Files.copy(response.body(), file.toPath(), java.nio.file.StandardCopyOption.REPLACE_EXISTING);
      return file;
    } catch (IOException e) {
      throw new ApiException(e);
    }
  }

  /**
   * <p>Prepare the file for download from the response.</p>
   *
   * @param response a {@link java.net.http.HttpResponse} object.
   * @return a {@link java.io.File} object.
   * @throws java.io.IOException if any.
   */
  private File prepareDownloadFile(HttpResponse<InputStream> response) throws IOException {
    String filename = null;
    java.util.Optional<String> contentDisposition = response.headers().firstValue("Content-Disposition");
    if (contentDisposition.isPresent() && !"".equals(contentDisposition.get())) {
      // Get filename from the Content-Disposition header.
      java.util.regex.Pattern pattern = java.util.regex.Pattern.compile("filename=['\"]?([^'\"\\s]+)['\"]?");
      java.util.regex.Matcher matcher = pattern.matcher(contentDisposition.get());
      if (matcher.find())
        filename = matcher.group(1);
    }
    File file = null;
    if (filename != null) {
      java.nio.file.Path tempDir = java.nio.file.Files.createTempDirectory("swagger-gen-native");
      java.nio.file.Path filePath = java.nio.file.Files.createFile(tempDir.resolve(filename));
      file = filePath.toFile();
      tempDir.toFile().deleteOnExit();   // best effort cleanup
      file.deleteOnExit(); // best effort cleanup
    } else {
      file = java.nio.file.Files.createTempFile("download-", "").toFile();
      file.deleteOnExit(); // best effort cleanup
    }
    return file;
  }

  /**
   * 
   * 
   * @param id the id of the requested resource (required)
   * @param filterDisplayName filter by attribute &#39;displayName&#39; (optional)
   * @param filterCertificateType filter by attribute &#39;certificateType&#39; (optional)
   * @param filterSerialNumber filter by attribute &#39;serialNumber&#39; (optional)
   * @param filterId filter by id(s) (optional)
   * @param sort comma-separated list of sort expressions; resources will be sorted as specified (optional)
   * @param fieldsCertificates the fields to include for returned resources of type certificates (optional)
   * @param fieldsPassTypeIds the fields to include for returned resources of type passTypeIds (optional)
   * @param limit maximum resources per page (optional)
   * @param include comma-separated list of relationships to include (optional)
   * @return CertificatesResponse
   * @throws ApiException if fails to make API call
   */
  public CertificatesResponse merchantIdsCertificatesGetToManyRelated(@jakarta.annotation.Nonnull String id, @jakarta.annotation.Nullable List<String> filterDisplayName, @jakarta.annotation.Nullable List<String> filterCertificateType, @jakarta.annotation.Nullable List<String> filterSerialNumber, @jakarta.annotation.Nullable List<String> filterId, @jakarta.annotation.Nullable List<String> sort, @jakarta.annotation.Nullable List<String> fieldsCertificates, @jakarta.annotation.Nullable List<String> fieldsPassTypeIds, @jakarta.annotation.Nullable Integer limit, @jakarta.annotation.Nullable List<String> include) throws ApiException {
    return merchantIdsCertificatesGetToManyRelated(id, filterDisplayName, filterCertificateType, filterSerialNumber, filterId, sort, fieldsCertificates, fieldsPassTypeIds, limit, include, null);
  }

  /**
   * 
   * 
   * @param id the id of the requested resource (required)
   * @param filterDisplayName filter by attribute &#39;displayName&#39; (optional)
   * @param filterCertificateType filter by attribute &#39;certificateType&#39; (optional)
   * @param filterSerialNumber filter by attribute &#39;serialNumber&#39; (optional)
   * @param filterId filter by id(s) (optional)
   * @param sort comma-separated list of sort expressions; resources will be sorted as specified (optional)
   * @param fieldsCertificates the fields to include for returned resources of type certificates (optional)
   * @param fieldsPassTypeIds the fields to include for returned resources of type passTypeIds (optional)
   * @param limit maximum resources per page (optional)
   * @param include comma-separated list of relationships to include (optional)
   * @param headers Optional headers to include in the request
   * @return CertificatesResponse
   * @throws ApiException if fails to make API call
   */
  public CertificatesResponse merchantIdsCertificatesGetToManyRelated(@jakarta.annotation.Nonnull String id, @jakarta.annotation.Nullable List<String> filterDisplayName, @jakarta.annotation.Nullable List<String> filterCertificateType, @jakarta.annotation.Nullable List<String> filterSerialNumber, @jakarta.annotation.Nullable List<String> filterId, @jakarta.annotation.Nullable List<String> sort, @jakarta.annotation.Nullable List<String> fieldsCertificates, @jakarta.annotation.Nullable List<String> fieldsPassTypeIds, @jakarta.annotation.Nullable Integer limit, @jakarta.annotation.Nullable List<String> include, Map<String, String> headers) throws ApiException {
    ApiResponse<CertificatesResponse> localVarResponse = merchantIdsCertificatesGetToManyRelatedWithHttpInfo(id, filterDisplayName, filterCertificateType, filterSerialNumber, filterId, sort, fieldsCertificates, fieldsPassTypeIds, limit, include, headers);
    return localVarResponse.getData();
  }

  /**
   * 
   * 
   * @param id the id of the requested resource (required)
   * @param filterDisplayName filter by attribute &#39;displayName&#39; (optional)
   * @param filterCertificateType filter by attribute &#39;certificateType&#39; (optional)
   * @param filterSerialNumber filter by attribute &#39;serialNumber&#39; (optional)
   * @param filterId filter by id(s) (optional)
   * @param sort comma-separated list of sort expressions; resources will be sorted as specified (optional)
   * @param fieldsCertificates the fields to include for returned resources of type certificates (optional)
   * @param fieldsPassTypeIds the fields to include for returned resources of type passTypeIds (optional)
   * @param limit maximum resources per page (optional)
   * @param include comma-separated list of relationships to include (optional)
   * @return ApiResponse&lt;CertificatesResponse&gt;
   * @throws ApiException if fails to make API call
   */
  public ApiResponse<CertificatesResponse> merchantIdsCertificatesGetToManyRelatedWithHttpInfo(@jakarta.annotation.Nonnull String id, @jakarta.annotation.Nullable List<String> filterDisplayName, @jakarta.annotation.Nullable List<String> filterCertificateType, @jakarta.annotation.Nullable List<String> filterSerialNumber, @jakarta.annotation.Nullable List<String> filterId, @jakarta.annotation.Nullable List<String> sort, @jakarta.annotation.Nullable List<String> fieldsCertificates, @jakarta.annotation.Nullable List<String> fieldsPassTypeIds, @jakarta.annotation.Nullable Integer limit, @jakarta.annotation.Nullable List<String> include) throws ApiException {
    return merchantIdsCertificatesGetToManyRelatedWithHttpInfo(id, filterDisplayName, filterCertificateType, filterSerialNumber, filterId, sort, fieldsCertificates, fieldsPassTypeIds, limit, include, null);
  }

  /**
   * 
   * 
   * @param id the id of the requested resource (required)
   * @param filterDisplayName filter by attribute &#39;displayName&#39; (optional)
   * @param filterCertificateType filter by attribute &#39;certificateType&#39; (optional)
   * @param filterSerialNumber filter by attribute &#39;serialNumber&#39; (optional)
   * @param filterId filter by id(s) (optional)
   * @param sort comma-separated list of sort expressions; resources will be sorted as specified (optional)
   * @param fieldsCertificates the fields to include for returned resources of type certificates (optional)
   * @param fieldsPassTypeIds the fields to include for returned resources of type passTypeIds (optional)
   * @param limit maximum resources per page (optional)
   * @param include comma-separated list of relationships to include (optional)
   * @param headers Optional headers to include in the request
   * @return ApiResponse&lt;CertificatesResponse&gt;
   * @throws ApiException if fails to make API call
   */
  public ApiResponse<CertificatesResponse> merchantIdsCertificatesGetToManyRelatedWithHttpInfo(@jakarta.annotation.Nonnull String id, @jakarta.annotation.Nullable List<String> filterDisplayName, @jakarta.annotation.Nullable List<String> filterCertificateType, @jakarta.annotation.Nullable List<String> filterSerialNumber, @jakarta.annotation.Nullable List<String> filterId, @jakarta.annotation.Nullable List<String> sort, @jakarta.annotation.Nullable List<String> fieldsCertificates, @jakarta.annotation.Nullable List<String> fieldsPassTypeIds, @jakarta.annotation.Nullable Integer limit, @jakarta.annotation.Nullable List<String> include, Map<String, String> headers) throws ApiException {
    HttpRequest.Builder localVarRequestBuilder = merchantIdsCertificatesGetToManyRelatedRequestBuilder(id, filterDisplayName, filterCertificateType, filterSerialNumber, filterId, sort, fieldsCertificates, fieldsPassTypeIds, limit, include, headers);
    try {
      HttpResponse<InputStream> localVarResponse = memberVarHttpClient.send(
          localVarRequestBuilder.build(),
          HttpResponse.BodyHandlers.ofInputStream());
      if (memberVarResponseInterceptor != null) {
        memberVarResponseInterceptor.accept(localVarResponse);
      }
      try {
        if (localVarResponse.statusCode()/ 100 != 2) {
          throw getApiException("merchantIdsCertificatesGetToManyRelated", localVarResponse);
        }
        if (localVarResponse.body() == null) {
          return new ApiResponse<CertificatesResponse>(
              localVarResponse.statusCode(),
              localVarResponse.headers().map(),
              null
          );
        }

        
        
        String responseBody = new String(localVarResponse.body().readAllBytes());
        CertificatesResponse responseValue = responseBody.isBlank()? null: memberVarObjectMapper.readValue(responseBody, new TypeReference<CertificatesResponse>() {});
        
        localVarResponse.body().close();

        return new ApiResponse<CertificatesResponse>(
            localVarResponse.statusCode(),
            localVarResponse.headers().map(),
            responseValue
        );
      } finally {
      }
    } catch (IOException e) {
      throw new ApiException(e);
    }
    catch (InterruptedException e) {
      Thread.currentThread().interrupt();
      throw new ApiException(e);
    }
  }

  private HttpRequest.Builder merchantIdsCertificatesGetToManyRelatedRequestBuilder(@jakarta.annotation.Nonnull String id, @jakarta.annotation.Nullable List<String> filterDisplayName, @jakarta.annotation.Nullable List<String> filterCertificateType, @jakarta.annotation.Nullable List<String> filterSerialNumber, @jakarta.annotation.Nullable List<String> filterId, @jakarta.annotation.Nullable List<String> sort, @jakarta.annotation.Nullable List<String> fieldsCertificates, @jakarta.annotation.Nullable List<String> fieldsPassTypeIds, @jakarta.annotation.Nullable Integer limit, @jakarta.annotation.Nullable List<String> include, Map<String, String> headers) throws ApiException {
    // verify the required parameter 'id' is set
    if (id == null) {
      throw new ApiException(400, "Missing the required parameter 'id' when calling merchantIdsCertificatesGetToManyRelated");
    }

    HttpRequest.Builder localVarRequestBuilder = HttpRequest.newBuilder();

    String localVarPath = "/v1/merchantIds/{id}/certificates"
        .replace("{id}", ApiClient.urlEncode(id.toString()));

    List<Pair> localVarQueryParams = new ArrayList<>();
    StringJoiner localVarQueryStringJoiner = new StringJoiner("&");
    String localVarQueryParameterBaseName;
    localVarQueryParameterBaseName = "filter[displayName]";
    localVarQueryParams.addAll(ApiClient.parameterToPairs("csv", "filter[displayName]", filterDisplayName));
    localVarQueryParameterBaseName = "filter[certificateType]";
    localVarQueryParams.addAll(ApiClient.parameterToPairs("csv", "filter[certificateType]", filterCertificateType));
    localVarQueryParameterBaseName = "filter[serialNumber]";
    localVarQueryParams.addAll(ApiClient.parameterToPairs("csv", "filter[serialNumber]", filterSerialNumber));
    localVarQueryParameterBaseName = "filter[id]";
    localVarQueryParams.addAll(ApiClient.parameterToPairs("csv", "filter[id]", filterId));
    localVarQueryParameterBaseName = "sort";
    localVarQueryParams.addAll(ApiClient.parameterToPairs("csv", "sort", sort));
    localVarQueryParameterBaseName = "fields[certificates]";
    localVarQueryParams.addAll(ApiClient.parameterToPairs("csv", "fields[certificates]", fieldsCertificates));
    localVarQueryParameterBaseName = "fields[passTypeIds]";
    localVarQueryParams.addAll(ApiClient.parameterToPairs("csv", "fields[passTypeIds]", fieldsPassTypeIds));
    localVarQueryParameterBaseName = "limit";
    localVarQueryParams.addAll(ApiClient.parameterToPairs("limit", limit));
    localVarQueryParameterBaseName = "include";
    localVarQueryParams.addAll(ApiClient.parameterToPairs("csv", "include", include));

    if (!localVarQueryParams.isEmpty() || localVarQueryStringJoiner.length() != 0) {
      StringJoiner queryJoiner = new StringJoiner("&");
      localVarQueryParams.forEach(p -> queryJoiner.add(p.getName() + '=' + p.getValue()));
      if (localVarQueryStringJoiner.length() != 0) {
        queryJoiner.add(localVarQueryStringJoiner.toString());
      }
      localVarRequestBuilder.uri(URI.create(memberVarBaseUri + localVarPath + '?' + queryJoiner.toString()));
    } else {
      localVarRequestBuilder.uri(URI.create(memberVarBaseUri + localVarPath));
    }

    localVarRequestBuilder.header("Accept", "application/json");

    localVarRequestBuilder.method("GET", HttpRequest.BodyPublishers.noBody());
    if (memberVarReadTimeout != null) {
      localVarRequestBuilder.timeout(memberVarReadTimeout);
    }
    // Add custom headers if provided
    localVarRequestBuilder = HttpRequestBuilderExtensions.withAdditionalHeaders(localVarRequestBuilder, headers);
    if (memberVarInterceptor != null) {
      memberVarInterceptor.accept(localVarRequestBuilder);
    }
    return localVarRequestBuilder;
  }

  /**
   * 
   * 
   * @param id the id of the requested resource (required)
   * @param limit maximum resources per page (optional)
   * @return MerchantIdCertificatesLinkagesResponse
   * @throws ApiException if fails to make API call
   */
  public MerchantIdCertificatesLinkagesResponse merchantIdsCertificatesGetToManyRelationship(@jakarta.annotation.Nonnull String id, @jakarta.annotation.Nullable Integer limit) throws ApiException {
    return merchantIdsCertificatesGetToManyRelationship(id, limit, null);
  }

  /**
   * 
   * 
   * @param id the id of the requested resource (required)
   * @param limit maximum resources per page (optional)
   * @param headers Optional headers to include in the request
   * @return MerchantIdCertificatesLinkagesResponse
   * @throws ApiException if fails to make API call
   */
  public MerchantIdCertificatesLinkagesResponse merchantIdsCertificatesGetToManyRelationship(@jakarta.annotation.Nonnull String id, @jakarta.annotation.Nullable Integer limit, Map<String, String> headers) throws ApiException {
    ApiResponse<MerchantIdCertificatesLinkagesResponse> localVarResponse = merchantIdsCertificatesGetToManyRelationshipWithHttpInfo(id, limit, headers);
    return localVarResponse.getData();
  }

  /**
   * 
   * 
   * @param id the id of the requested resource (required)
   * @param limit maximum resources per page (optional)
   * @return ApiResponse&lt;MerchantIdCertificatesLinkagesResponse&gt;
   * @throws ApiException if fails to make API call
   */
  public ApiResponse<MerchantIdCertificatesLinkagesResponse> merchantIdsCertificatesGetToManyRelationshipWithHttpInfo(@jakarta.annotation.Nonnull String id, @jakarta.annotation.Nullable Integer limit) throws ApiException {
    return merchantIdsCertificatesGetToManyRelationshipWithHttpInfo(id, limit, null);
  }

  /**
   * 
   * 
   * @param id the id of the requested resource (required)
   * @param limit maximum resources per page (optional)
   * @param headers Optional headers to include in the request
   * @return ApiResponse&lt;MerchantIdCertificatesLinkagesResponse&gt;
   * @throws ApiException if fails to make API call
   */
  public ApiResponse<MerchantIdCertificatesLinkagesResponse> merchantIdsCertificatesGetToManyRelationshipWithHttpInfo(@jakarta.annotation.Nonnull String id, @jakarta.annotation.Nullable Integer limit, Map<String, String> headers) throws ApiException {
    HttpRequest.Builder localVarRequestBuilder = merchantIdsCertificatesGetToManyRelationshipRequestBuilder(id, limit, headers);
    try {
      HttpResponse<InputStream> localVarResponse = memberVarHttpClient.send(
          localVarRequestBuilder.build(),
          HttpResponse.BodyHandlers.ofInputStream());
      if (memberVarResponseInterceptor != null) {
        memberVarResponseInterceptor.accept(localVarResponse);
      }
      try {
        if (localVarResponse.statusCode()/ 100 != 2) {
          throw getApiException("merchantIdsCertificatesGetToManyRelationship", localVarResponse);
        }
        if (localVarResponse.body() == null) {
          return new ApiResponse<MerchantIdCertificatesLinkagesResponse>(
              localVarResponse.statusCode(),
              localVarResponse.headers().map(),
              null
          );
        }

        
        
        String responseBody = new String(localVarResponse.body().readAllBytes());
        MerchantIdCertificatesLinkagesResponse responseValue = responseBody.isBlank()? null: memberVarObjectMapper.readValue(responseBody, new TypeReference<MerchantIdCertificatesLinkagesResponse>() {});
        
        localVarResponse.body().close();

        return new ApiResponse<MerchantIdCertificatesLinkagesResponse>(
            localVarResponse.statusCode(),
            localVarResponse.headers().map(),
            responseValue
        );
      } finally {
      }
    } catch (IOException e) {
      throw new ApiException(e);
    }
    catch (InterruptedException e) {
      Thread.currentThread().interrupt();
      throw new ApiException(e);
    }
  }

  private HttpRequest.Builder merchantIdsCertificatesGetToManyRelationshipRequestBuilder(@jakarta.annotation.Nonnull String id, @jakarta.annotation.Nullable Integer limit, Map<String, String> headers) throws ApiException {
    // verify the required parameter 'id' is set
    if (id == null) {
      throw new ApiException(400, "Missing the required parameter 'id' when calling merchantIdsCertificatesGetToManyRelationship");
    }

    HttpRequest.Builder localVarRequestBuilder = HttpRequest.newBuilder();

    String localVarPath = "/v1/merchantIds/{id}/relationships/certificates"
        .replace("{id}", ApiClient.urlEncode(id.toString()));

    List<Pair> localVarQueryParams = new ArrayList<>();
    StringJoiner localVarQueryStringJoiner = new StringJoiner("&");
    String localVarQueryParameterBaseName;
    localVarQueryParameterBaseName = "limit";
    localVarQueryParams.addAll(ApiClient.parameterToPairs("limit", limit));

    if (!localVarQueryParams.isEmpty() || localVarQueryStringJoiner.length() != 0) {
      StringJoiner queryJoiner = new StringJoiner("&");
      localVarQueryParams.forEach(p -> queryJoiner.add(p.getName() + '=' + p.getValue()));
      if (localVarQueryStringJoiner.length() != 0) {
        queryJoiner.add(localVarQueryStringJoiner.toString());
      }
      localVarRequestBuilder.uri(URI.create(memberVarBaseUri + localVarPath + '?' + queryJoiner.toString()));
    } else {
      localVarRequestBuilder.uri(URI.create(memberVarBaseUri + localVarPath));
    }

    localVarRequestBuilder.header("Accept", "application/json");

    localVarRequestBuilder.method("GET", HttpRequest.BodyPublishers.noBody());
    if (memberVarReadTimeout != null) {
      localVarRequestBuilder.timeout(memberVarReadTimeout);
    }
    // Add custom headers if provided
    localVarRequestBuilder = HttpRequestBuilderExtensions.withAdditionalHeaders(localVarRequestBuilder, headers);
    if (memberVarInterceptor != null) {
      memberVarInterceptor.accept(localVarRequestBuilder);
    }
    return localVarRequestBuilder;
  }

  /**
   * 
   * 
   * @param merchantIdCreateRequest MerchantId representation (required)
   * @return MerchantIdResponse
   * @throws ApiException if fails to make API call
   */
  public MerchantIdResponse merchantIdsCreateInstance(@jakarta.annotation.Nonnull MerchantIdCreateRequest merchantIdCreateRequest) throws ApiException {
    return merchantIdsCreateInstance(merchantIdCreateRequest, null);
  }

  /**
   * 
   * 
   * @param merchantIdCreateRequest MerchantId representation (required)
   * @param headers Optional headers to include in the request
   * @return MerchantIdResponse
   * @throws ApiException if fails to make API call
   */
  public MerchantIdResponse merchantIdsCreateInstance(@jakarta.annotation.Nonnull MerchantIdCreateRequest merchantIdCreateRequest, Map<String, String> headers) throws ApiException {
    ApiResponse<MerchantIdResponse> localVarResponse = merchantIdsCreateInstanceWithHttpInfo(merchantIdCreateRequest, headers);
    return localVarResponse.getData();
  }

  /**
   * 
   * 
   * @param merchantIdCreateRequest MerchantId representation (required)
   * @return ApiResponse&lt;MerchantIdResponse&gt;
   * @throws ApiException if fails to make API call
   */
  public ApiResponse<MerchantIdResponse> merchantIdsCreateInstanceWithHttpInfo(@jakarta.annotation.Nonnull MerchantIdCreateRequest merchantIdCreateRequest) throws ApiException {
    return merchantIdsCreateInstanceWithHttpInfo(merchantIdCreateRequest, null);
  }

  /**
   * 
   * 
   * @param merchantIdCreateRequest MerchantId representation (required)
   * @param headers Optional headers to include in the request
   * @return ApiResponse&lt;MerchantIdResponse&gt;
   * @throws ApiException if fails to make API call
   */
  public ApiResponse<MerchantIdResponse> merchantIdsCreateInstanceWithHttpInfo(@jakarta.annotation.Nonnull MerchantIdCreateRequest merchantIdCreateRequest, Map<String, String> headers) throws ApiException {
    HttpRequest.Builder localVarRequestBuilder = merchantIdsCreateInstanceRequestBuilder(merchantIdCreateRequest, headers);
    try {
      HttpResponse<InputStream> localVarResponse = memberVarHttpClient.send(
          localVarRequestBuilder.build(),
          HttpResponse.BodyHandlers.ofInputStream());
      if (memberVarResponseInterceptor != null) {
        memberVarResponseInterceptor.accept(localVarResponse);
      }
      try {
        if (localVarResponse.statusCode()/ 100 != 2) {
          throw getApiException("merchantIdsCreateInstance", localVarResponse);
        }
        if (localVarResponse.body() == null) {
          return new ApiResponse<MerchantIdResponse>(
              localVarResponse.statusCode(),
              localVarResponse.headers().map(),
              null
          );
        }

        
        
        String responseBody = new String(localVarResponse.body().readAllBytes());
        MerchantIdResponse responseValue = responseBody.isBlank()? null: memberVarObjectMapper.readValue(responseBody, new TypeReference<MerchantIdResponse>() {});
        
        localVarResponse.body().close();

        return new ApiResponse<MerchantIdResponse>(
            localVarResponse.statusCode(),
            localVarResponse.headers().map(),
            responseValue
        );
      } finally {
      }
    } catch (IOException e) {
      throw new ApiException(e);
    }
    catch (InterruptedException e) {
      Thread.currentThread().interrupt();
      throw new ApiException(e);
    }
  }

  private HttpRequest.Builder merchantIdsCreateInstanceRequestBuilder(@jakarta.annotation.Nonnull MerchantIdCreateRequest merchantIdCreateRequest, Map<String, String> headers) throws ApiException {
    // verify the required parameter 'merchantIdCreateRequest' is set
    if (merchantIdCreateRequest == null) {
      throw new ApiException(400, "Missing the required parameter 'merchantIdCreateRequest' when calling merchantIdsCreateInstance");
    }

    HttpRequest.Builder localVarRequestBuilder = HttpRequest.newBuilder();

    String localVarPath = "/v1/merchantIds";

    localVarRequestBuilder.uri(URI.create(memberVarBaseUri + localVarPath));

    localVarRequestBuilder.header("Content-Type", "application/json");
    localVarRequestBuilder.header("Accept", "application/json");

    try {
      byte[] localVarPostBody = memberVarObjectMapper.writeValueAsBytes(merchantIdCreateRequest);
      localVarRequestBuilder.method("POST", HttpRequest.BodyPublishers.ofByteArray(localVarPostBody));
    } catch (IOException e) {
      throw new ApiException(e);
    }
    if (memberVarReadTimeout != null) {
      localVarRequestBuilder.timeout(memberVarReadTimeout);
    }
    // Add custom headers if provided
    localVarRequestBuilder = HttpRequestBuilderExtensions.withAdditionalHeaders(localVarRequestBuilder, headers);
    if (memberVarInterceptor != null) {
      memberVarInterceptor.accept(localVarRequestBuilder);
    }
    return localVarRequestBuilder;
  }

  /**
   * 
   * 
   * @param id the id of the requested resource (required)
   * @throws ApiException if fails to make API call
   */
  public void merchantIdsDeleteInstance(@jakarta.annotation.Nonnull String id) throws ApiException {
    merchantIdsDeleteInstance(id, null);
  }

  /**
   * 
   * 
   * @param id the id of the requested resource (required)
   * @param headers Optional headers to include in the request
   * @throws ApiException if fails to make API call
   */
  public void merchantIdsDeleteInstance(@jakarta.annotation.Nonnull String id, Map<String, String> headers) throws ApiException {
    merchantIdsDeleteInstanceWithHttpInfo(id, headers);
  }

  /**
   * 
   * 
   * @param id the id of the requested resource (required)
   * @return ApiResponse&lt;Void&gt;
   * @throws ApiException if fails to make API call
   */
  public ApiResponse<Void> merchantIdsDeleteInstanceWithHttpInfo(@jakarta.annotation.Nonnull String id) throws ApiException {
    return merchantIdsDeleteInstanceWithHttpInfo(id, null);
  }

  /**
   * 
   * 
   * @param id the id of the requested resource (required)
   * @param headers Optional headers to include in the request
   * @return ApiResponse&lt;Void&gt;
   * @throws ApiException if fails to make API call
   */
  public ApiResponse<Void> merchantIdsDeleteInstanceWithHttpInfo(@jakarta.annotation.Nonnull String id, Map<String, String> headers) throws ApiException {
    HttpRequest.Builder localVarRequestBuilder = merchantIdsDeleteInstanceRequestBuilder(id, headers);
    try {
      HttpResponse<InputStream> localVarResponse = memberVarHttpClient.send(
          localVarRequestBuilder.build(),
          HttpResponse.BodyHandlers.ofInputStream());
      if (memberVarResponseInterceptor != null) {
        memberVarResponseInterceptor.accept(localVarResponse);
      }
      try {
        if (localVarResponse.statusCode()/ 100 != 2) {
          throw getApiException("merchantIdsDeleteInstance", localVarResponse);
        }
        return new ApiResponse<>(
            localVarResponse.statusCode(),
            localVarResponse.headers().map(),
            null
        );
      } finally {
        // Drain the InputStream
        while (localVarResponse.body().read() != -1) {
          // Ignore
        }
        localVarResponse.body().close();
      }
    } catch (IOException e) {
      throw new ApiException(e);
    }
    catch (InterruptedException e) {
      Thread.currentThread().interrupt();
      throw new ApiException(e);
    }
  }

  private HttpRequest.Builder merchantIdsDeleteInstanceRequestBuilder(@jakarta.annotation.Nonnull String id, Map<String, String> headers) throws ApiException {
    // verify the required parameter 'id' is set
    if (id == null) {
      throw new ApiException(400, "Missing the required parameter 'id' when calling merchantIdsDeleteInstance");
    }

    HttpRequest.Builder localVarRequestBuilder = HttpRequest.newBuilder();

    String localVarPath = "/v1/merchantIds/{id}"
        .replace("{id}", ApiClient.urlEncode(id.toString()));

    localVarRequestBuilder.uri(URI.create(memberVarBaseUri + localVarPath));

    localVarRequestBuilder.header("Accept", "application/json");

    localVarRequestBuilder.method("DELETE", HttpRequest.BodyPublishers.noBody());
    if (memberVarReadTimeout != null) {
      localVarRequestBuilder.timeout(memberVarReadTimeout);
    }
    // Add custom headers if provided
    localVarRequestBuilder = HttpRequestBuilderExtensions.withAdditionalHeaders(localVarRequestBuilder, headers);
    if (memberVarInterceptor != null) {
      memberVarInterceptor.accept(localVarRequestBuilder);
    }
    return localVarRequestBuilder;
  }

  /**
   * 
   * 
   * @param filterName filter by attribute &#39;name&#39; (optional)
   * @param filterIdentifier filter by attribute &#39;identifier&#39; (optional)
   * @param sort comma-separated list of sort expressions; resources will be sorted as specified (optional)
   * @param fieldsMerchantIds the fields to include for returned resources of type merchantIds (optional)
   * @param fieldsCertificates the fields to include for returned resources of type certificates (optional)
   * @param limit maximum resources per page (optional)
   * @param include comma-separated list of relationships to include (optional)
   * @param limitCertificates maximum number of related certificates returned (when they are included) (optional)
   * @return MerchantIdsResponse
   * @throws ApiException if fails to make API call
   */
  public MerchantIdsResponse merchantIdsGetCollection(@jakarta.annotation.Nullable List<String> filterName, @jakarta.annotation.Nullable List<String> filterIdentifier, @jakarta.annotation.Nullable List<String> sort, @jakarta.annotation.Nullable List<String> fieldsMerchantIds, @jakarta.annotation.Nullable List<String> fieldsCertificates, @jakarta.annotation.Nullable Integer limit, @jakarta.annotation.Nullable List<String> include, @jakarta.annotation.Nullable Integer limitCertificates) throws ApiException {
    return merchantIdsGetCollection(filterName, filterIdentifier, sort, fieldsMerchantIds, fieldsCertificates, limit, include, limitCertificates, null);
  }

  /**
   * 
   * 
   * @param filterName filter by attribute &#39;name&#39; (optional)
   * @param filterIdentifier filter by attribute &#39;identifier&#39; (optional)
   * @param sort comma-separated list of sort expressions; resources will be sorted as specified (optional)
   * @param fieldsMerchantIds the fields to include for returned resources of type merchantIds (optional)
   * @param fieldsCertificates the fields to include for returned resources of type certificates (optional)
   * @param limit maximum resources per page (optional)
   * @param include comma-separated list of relationships to include (optional)
   * @param limitCertificates maximum number of related certificates returned (when they are included) (optional)
   * @param headers Optional headers to include in the request
   * @return MerchantIdsResponse
   * @throws ApiException if fails to make API call
   */
  public MerchantIdsResponse merchantIdsGetCollection(@jakarta.annotation.Nullable List<String> filterName, @jakarta.annotation.Nullable List<String> filterIdentifier, @jakarta.annotation.Nullable List<String> sort, @jakarta.annotation.Nullable List<String> fieldsMerchantIds, @jakarta.annotation.Nullable List<String> fieldsCertificates, @jakarta.annotation.Nullable Integer limit, @jakarta.annotation.Nullable List<String> include, @jakarta.annotation.Nullable Integer limitCertificates, Map<String, String> headers) throws ApiException {
    ApiResponse<MerchantIdsResponse> localVarResponse = merchantIdsGetCollectionWithHttpInfo(filterName, filterIdentifier, sort, fieldsMerchantIds, fieldsCertificates, limit, include, limitCertificates, headers);
    return localVarResponse.getData();
  }

  /**
   * 
   * 
   * @param filterName filter by attribute &#39;name&#39; (optional)
   * @param filterIdentifier filter by attribute &#39;identifier&#39; (optional)
   * @param sort comma-separated list of sort expressions; resources will be sorted as specified (optional)
   * @param fieldsMerchantIds the fields to include for returned resources of type merchantIds (optional)
   * @param fieldsCertificates the fields to include for returned resources of type certificates (optional)
   * @param limit maximum resources per page (optional)
   * @param include comma-separated list of relationships to include (optional)
   * @param limitCertificates maximum number of related certificates returned (when they are included) (optional)
   * @return ApiResponse&lt;MerchantIdsResponse&gt;
   * @throws ApiException if fails to make API call
   */
  public ApiResponse<MerchantIdsResponse> merchantIdsGetCollectionWithHttpInfo(@jakarta.annotation.Nullable List<String> filterName, @jakarta.annotation.Nullable List<String> filterIdentifier, @jakarta.annotation.Nullable List<String> sort, @jakarta.annotation.Nullable List<String> fieldsMerchantIds, @jakarta.annotation.Nullable List<String> fieldsCertificates, @jakarta.annotation.Nullable Integer limit, @jakarta.annotation.Nullable List<String> include, @jakarta.annotation.Nullable Integer limitCertificates) throws ApiException {
    return merchantIdsGetCollectionWithHttpInfo(filterName, filterIdentifier, sort, fieldsMerchantIds, fieldsCertificates, limit, include, limitCertificates, null);
  }

  /**
   * 
   * 
   * @param filterName filter by attribute &#39;name&#39; (optional)
   * @param filterIdentifier filter by attribute &#39;identifier&#39; (optional)
   * @param sort comma-separated list of sort expressions; resources will be sorted as specified (optional)
   * @param fieldsMerchantIds the fields to include for returned resources of type merchantIds (optional)
   * @param fieldsCertificates the fields to include for returned resources of type certificates (optional)
   * @param limit maximum resources per page (optional)
   * @param include comma-separated list of relationships to include (optional)
   * @param limitCertificates maximum number of related certificates returned (when they are included) (optional)
   * @param headers Optional headers to include in the request
   * @return ApiResponse&lt;MerchantIdsResponse&gt;
   * @throws ApiException if fails to make API call
   */
  public ApiResponse<MerchantIdsResponse> merchantIdsGetCollectionWithHttpInfo(@jakarta.annotation.Nullable List<String> filterName, @jakarta.annotation.Nullable List<String> filterIdentifier, @jakarta.annotation.Nullable List<String> sort, @jakarta.annotation.Nullable List<String> fieldsMerchantIds, @jakarta.annotation.Nullable List<String> fieldsCertificates, @jakarta.annotation.Nullable Integer limit, @jakarta.annotation.Nullable List<String> include, @jakarta.annotation.Nullable Integer limitCertificates, Map<String, String> headers) throws ApiException {
    HttpRequest.Builder localVarRequestBuilder = merchantIdsGetCollectionRequestBuilder(filterName, filterIdentifier, sort, fieldsMerchantIds, fieldsCertificates, limit, include, limitCertificates, headers);
    try {
      HttpResponse<InputStream> localVarResponse = memberVarHttpClient.send(
          localVarRequestBuilder.build(),
          HttpResponse.BodyHandlers.ofInputStream());
      if (memberVarResponseInterceptor != null) {
        memberVarResponseInterceptor.accept(localVarResponse);
      }
      try {
        if (localVarResponse.statusCode()/ 100 != 2) {
          throw getApiException("merchantIdsGetCollection", localVarResponse);
        }
        if (localVarResponse.body() == null) {
          return new ApiResponse<MerchantIdsResponse>(
              localVarResponse.statusCode(),
              localVarResponse.headers().map(),
              null
          );
        }

        
        
        String responseBody = new String(localVarResponse.body().readAllBytes());
        MerchantIdsResponse responseValue = responseBody.isBlank()? null: memberVarObjectMapper.readValue(responseBody, new TypeReference<MerchantIdsResponse>() {});
        
        localVarResponse.body().close();

        return new ApiResponse<MerchantIdsResponse>(
            localVarResponse.statusCode(),
            localVarResponse.headers().map(),
            responseValue
        );
      } finally {
      }
    } catch (IOException e) {
      throw new ApiException(e);
    }
    catch (InterruptedException e) {
      Thread.currentThread().interrupt();
      throw new ApiException(e);
    }
  }

  private HttpRequest.Builder merchantIdsGetCollectionRequestBuilder(@jakarta.annotation.Nullable List<String> filterName, @jakarta.annotation.Nullable List<String> filterIdentifier, @jakarta.annotation.Nullable List<String> sort, @jakarta.annotation.Nullable List<String> fieldsMerchantIds, @jakarta.annotation.Nullable List<String> fieldsCertificates, @jakarta.annotation.Nullable Integer limit, @jakarta.annotation.Nullable List<String> include, @jakarta.annotation.Nullable Integer limitCertificates, Map<String, String> headers) throws ApiException {

    HttpRequest.Builder localVarRequestBuilder = HttpRequest.newBuilder();

    String localVarPath = "/v1/merchantIds";

    List<Pair> localVarQueryParams = new ArrayList<>();
    StringJoiner localVarQueryStringJoiner = new StringJoiner("&");
    String localVarQueryParameterBaseName;
    localVarQueryParameterBaseName = "filter[name]";
    localVarQueryParams.addAll(ApiClient.parameterToPairs("csv", "filter[name]", filterName));
    localVarQueryParameterBaseName = "filter[identifier]";
    localVarQueryParams.addAll(ApiClient.parameterToPairs("csv", "filter[identifier]", filterIdentifier));
    localVarQueryParameterBaseName = "sort";
    localVarQueryParams.addAll(ApiClient.parameterToPairs("csv", "sort", sort));
    localVarQueryParameterBaseName = "fields[merchantIds]";
    localVarQueryParams.addAll(ApiClient.parameterToPairs("csv", "fields[merchantIds]", fieldsMerchantIds));
    localVarQueryParameterBaseName = "fields[certificates]";
    localVarQueryParams.addAll(ApiClient.parameterToPairs("csv", "fields[certificates]", fieldsCertificates));
    localVarQueryParameterBaseName = "limit";
    localVarQueryParams.addAll(ApiClient.parameterToPairs("limit", limit));
    localVarQueryParameterBaseName = "include";
    localVarQueryParams.addAll(ApiClient.parameterToPairs("csv", "include", include));
    localVarQueryParameterBaseName = "limit[certificates]";
    localVarQueryParams.addAll(ApiClient.parameterToPairs("limit[certificates]", limitCertificates));

    if (!localVarQueryParams.isEmpty() || localVarQueryStringJoiner.length() != 0) {
      StringJoiner queryJoiner = new StringJoiner("&");
      localVarQueryParams.forEach(p -> queryJoiner.add(p.getName() + '=' + p.getValue()));
      if (localVarQueryStringJoiner.length() != 0) {
        queryJoiner.add(localVarQueryStringJoiner.toString());
      }
      localVarRequestBuilder.uri(URI.create(memberVarBaseUri + localVarPath + '?' + queryJoiner.toString()));
    } else {
      localVarRequestBuilder.uri(URI.create(memberVarBaseUri + localVarPath));
    }

    localVarRequestBuilder.header("Accept", "application/json");

    localVarRequestBuilder.method("GET", HttpRequest.BodyPublishers.noBody());
    if (memberVarReadTimeout != null) {
      localVarRequestBuilder.timeout(memberVarReadTimeout);
    }
    // Add custom headers if provided
    localVarRequestBuilder = HttpRequestBuilderExtensions.withAdditionalHeaders(localVarRequestBuilder, headers);
    if (memberVarInterceptor != null) {
      memberVarInterceptor.accept(localVarRequestBuilder);
    }
    return localVarRequestBuilder;
  }

  /**
   * 
   * 
   * @param id the id of the requested resource (required)
   * @param fieldsMerchantIds the fields to include for returned resources of type merchantIds (optional)
   * @param fieldsCertificates the fields to include for returned resources of type certificates (optional)
   * @param include comma-separated list of relationships to include (optional)
   * @param limitCertificates maximum number of related certificates returned (when they are included) (optional)
   * @return MerchantIdResponse
   * @throws ApiException if fails to make API call
   */
  public MerchantIdResponse merchantIdsGetInstance(@jakarta.annotation.Nonnull String id, @jakarta.annotation.Nullable List<String> fieldsMerchantIds, @jakarta.annotation.Nullable List<String> fieldsCertificates, @jakarta.annotation.Nullable List<String> include, @jakarta.annotation.Nullable Integer limitCertificates) throws ApiException {
    return merchantIdsGetInstance(id, fieldsMerchantIds, fieldsCertificates, include, limitCertificates, null);
  }

  /**
   * 
   * 
   * @param id the id of the requested resource (required)
   * @param fieldsMerchantIds the fields to include for returned resources of type merchantIds (optional)
   * @param fieldsCertificates the fields to include for returned resources of type certificates (optional)
   * @param include comma-separated list of relationships to include (optional)
   * @param limitCertificates maximum number of related certificates returned (when they are included) (optional)
   * @param headers Optional headers to include in the request
   * @return MerchantIdResponse
   * @throws ApiException if fails to make API call
   */
  public MerchantIdResponse merchantIdsGetInstance(@jakarta.annotation.Nonnull String id, @jakarta.annotation.Nullable List<String> fieldsMerchantIds, @jakarta.annotation.Nullable List<String> fieldsCertificates, @jakarta.annotation.Nullable List<String> include, @jakarta.annotation.Nullable Integer limitCertificates, Map<String, String> headers) throws ApiException {
    ApiResponse<MerchantIdResponse> localVarResponse = merchantIdsGetInstanceWithHttpInfo(id, fieldsMerchantIds, fieldsCertificates, include, limitCertificates, headers);
    return localVarResponse.getData();
  }

  /**
   * 
   * 
   * @param id the id of the requested resource (required)
   * @param fieldsMerchantIds the fields to include for returned resources of type merchantIds (optional)
   * @param fieldsCertificates the fields to include for returned resources of type certificates (optional)
   * @param include comma-separated list of relationships to include (optional)
   * @param limitCertificates maximum number of related certificates returned (when they are included) (optional)
   * @return ApiResponse&lt;MerchantIdResponse&gt;
   * @throws ApiException if fails to make API call
   */
  public ApiResponse<MerchantIdResponse> merchantIdsGetInstanceWithHttpInfo(@jakarta.annotation.Nonnull String id, @jakarta.annotation.Nullable List<String> fieldsMerchantIds, @jakarta.annotation.Nullable List<String> fieldsCertificates, @jakarta.annotation.Nullable List<String> include, @jakarta.annotation.Nullable Integer limitCertificates) throws ApiException {
    return merchantIdsGetInstanceWithHttpInfo(id, fieldsMerchantIds, fieldsCertificates, include, limitCertificates, null);
  }

  /**
   * 
   * 
   * @param id the id of the requested resource (required)
   * @param fieldsMerchantIds the fields to include for returned resources of type merchantIds (optional)
   * @param fieldsCertificates the fields to include for returned resources of type certificates (optional)
   * @param include comma-separated list of relationships to include (optional)
   * @param limitCertificates maximum number of related certificates returned (when they are included) (optional)
   * @param headers Optional headers to include in the request
   * @return ApiResponse&lt;MerchantIdResponse&gt;
   * @throws ApiException if fails to make API call
   */
  public ApiResponse<MerchantIdResponse> merchantIdsGetInstanceWithHttpInfo(@jakarta.annotation.Nonnull String id, @jakarta.annotation.Nullable List<String> fieldsMerchantIds, @jakarta.annotation.Nullable List<String> fieldsCertificates, @jakarta.annotation.Nullable List<String> include, @jakarta.annotation.Nullable Integer limitCertificates, Map<String, String> headers) throws ApiException {
    HttpRequest.Builder localVarRequestBuilder = merchantIdsGetInstanceRequestBuilder(id, fieldsMerchantIds, fieldsCertificates, include, limitCertificates, headers);
    try {
      HttpResponse<InputStream> localVarResponse = memberVarHttpClient.send(
          localVarRequestBuilder.build(),
          HttpResponse.BodyHandlers.ofInputStream());
      if (memberVarResponseInterceptor != null) {
        memberVarResponseInterceptor.accept(localVarResponse);
      }
      try {
        if (localVarResponse.statusCode()/ 100 != 2) {
          throw getApiException("merchantIdsGetInstance", localVarResponse);
        }
        if (localVarResponse.body() == null) {
          return new ApiResponse<MerchantIdResponse>(
              localVarResponse.statusCode(),
              localVarResponse.headers().map(),
              null
          );
        }

        
        
        String responseBody = new String(localVarResponse.body().readAllBytes());
        MerchantIdResponse responseValue = responseBody.isBlank()? null: memberVarObjectMapper.readValue(responseBody, new TypeReference<MerchantIdResponse>() {});
        
        localVarResponse.body().close();

        return new ApiResponse<MerchantIdResponse>(
            localVarResponse.statusCode(),
            localVarResponse.headers().map(),
            responseValue
        );
      } finally {
      }
    } catch (IOException e) {
      throw new ApiException(e);
    }
    catch (InterruptedException e) {
      Thread.currentThread().interrupt();
      throw new ApiException(e);
    }
  }

  private HttpRequest.Builder merchantIdsGetInstanceRequestBuilder(@jakarta.annotation.Nonnull String id, @jakarta.annotation.Nullable List<String> fieldsMerchantIds, @jakarta.annotation.Nullable List<String> fieldsCertificates, @jakarta.annotation.Nullable List<String> include, @jakarta.annotation.Nullable Integer limitCertificates, Map<String, String> headers) throws ApiException {
    // verify the required parameter 'id' is set
    if (id == null) {
      throw new ApiException(400, "Missing the required parameter 'id' when calling merchantIdsGetInstance");
    }

    HttpRequest.Builder localVarRequestBuilder = HttpRequest.newBuilder();

    String localVarPath = "/v1/merchantIds/{id}"
        .replace("{id}", ApiClient.urlEncode(id.toString()));

    List<Pair> localVarQueryParams = new ArrayList<>();
    StringJoiner localVarQueryStringJoiner = new StringJoiner("&");
    String localVarQueryParameterBaseName;
    localVarQueryParameterBaseName = "fields[merchantIds]";
    localVarQueryParams.addAll(ApiClient.parameterToPairs("csv", "fields[merchantIds]", fieldsMerchantIds));
    localVarQueryParameterBaseName = "fields[certificates]";
    localVarQueryParams.addAll(ApiClient.parameterToPairs("csv", "fields[certificates]", fieldsCertificates));
    localVarQueryParameterBaseName = "include";
    localVarQueryParams.addAll(ApiClient.parameterToPairs("csv", "include", include));
    localVarQueryParameterBaseName = "limit[certificates]";
    localVarQueryParams.addAll(ApiClient.parameterToPairs("limit[certificates]", limitCertificates));

    if (!localVarQueryParams.isEmpty() || localVarQueryStringJoiner.length() != 0) {
      StringJoiner queryJoiner = new StringJoiner("&");
      localVarQueryParams.forEach(p -> queryJoiner.add(p.getName() + '=' + p.getValue()));
      if (localVarQueryStringJoiner.length() != 0) {
        queryJoiner.add(localVarQueryStringJoiner.toString());
      }
      localVarRequestBuilder.uri(URI.create(memberVarBaseUri + localVarPath + '?' + queryJoiner.toString()));
    } else {
      localVarRequestBuilder.uri(URI.create(memberVarBaseUri + localVarPath));
    }

    localVarRequestBuilder.header("Accept", "application/json");

    localVarRequestBuilder.method("GET", HttpRequest.BodyPublishers.noBody());
    if (memberVarReadTimeout != null) {
      localVarRequestBuilder.timeout(memberVarReadTimeout);
    }
    // Add custom headers if provided
    localVarRequestBuilder = HttpRequestBuilderExtensions.withAdditionalHeaders(localVarRequestBuilder, headers);
    if (memberVarInterceptor != null) {
      memberVarInterceptor.accept(localVarRequestBuilder);
    }
    return localVarRequestBuilder;
  }

  /**
   * 
   * 
   * @param id the id of the requested resource (required)
   * @param merchantIdUpdateRequest MerchantId representation (required)
   * @return MerchantIdResponse
   * @throws ApiException if fails to make API call
   */
  public MerchantIdResponse merchantIdsUpdateInstance(@jakarta.annotation.Nonnull String id, @jakarta.annotation.Nonnull MerchantIdUpdateRequest merchantIdUpdateRequest) throws ApiException {
    return merchantIdsUpdateInstance(id, merchantIdUpdateRequest, null);
  }

  /**
   * 
   * 
   * @param id the id of the requested resource (required)
   * @param merchantIdUpdateRequest MerchantId representation (required)
   * @param headers Optional headers to include in the request
   * @return MerchantIdResponse
   * @throws ApiException if fails to make API call
   */
  public MerchantIdResponse merchantIdsUpdateInstance(@jakarta.annotation.Nonnull String id, @jakarta.annotation.Nonnull MerchantIdUpdateRequest merchantIdUpdateRequest, Map<String, String> headers) throws ApiException {
    ApiResponse<MerchantIdResponse> localVarResponse = merchantIdsUpdateInstanceWithHttpInfo(id, merchantIdUpdateRequest, headers);
    return localVarResponse.getData();
  }

  /**
   * 
   * 
   * @param id the id of the requested resource (required)
   * @param merchantIdUpdateRequest MerchantId representation (required)
   * @return ApiResponse&lt;MerchantIdResponse&gt;
   * @throws ApiException if fails to make API call
   */
  public ApiResponse<MerchantIdResponse> merchantIdsUpdateInstanceWithHttpInfo(@jakarta.annotation.Nonnull String id, @jakarta.annotation.Nonnull MerchantIdUpdateRequest merchantIdUpdateRequest) throws ApiException {
    return merchantIdsUpdateInstanceWithHttpInfo(id, merchantIdUpdateRequest, null);
  }

  /**
   * 
   * 
   * @param id the id of the requested resource (required)
   * @param merchantIdUpdateRequest MerchantId representation (required)
   * @param headers Optional headers to include in the request
   * @return ApiResponse&lt;MerchantIdResponse&gt;
   * @throws ApiException if fails to make API call
   */
  public ApiResponse<MerchantIdResponse> merchantIdsUpdateInstanceWithHttpInfo(@jakarta.annotation.Nonnull String id, @jakarta.annotation.Nonnull MerchantIdUpdateRequest merchantIdUpdateRequest, Map<String, String> headers) throws ApiException {
    HttpRequest.Builder localVarRequestBuilder = merchantIdsUpdateInstanceRequestBuilder(id, merchantIdUpdateRequest, headers);
    try {
      HttpResponse<InputStream> localVarResponse = memberVarHttpClient.send(
          localVarRequestBuilder.build(),
          HttpResponse.BodyHandlers.ofInputStream());
      if (memberVarResponseInterceptor != null) {
        memberVarResponseInterceptor.accept(localVarResponse);
      }
      try {
        if (localVarResponse.statusCode()/ 100 != 2) {
          throw getApiException("merchantIdsUpdateInstance", localVarResponse);
        }
        if (localVarResponse.body() == null) {
          return new ApiResponse<MerchantIdResponse>(
              localVarResponse.statusCode(),
              localVarResponse.headers().map(),
              null
          );
        }

        
        
        String responseBody = new String(localVarResponse.body().readAllBytes());
        MerchantIdResponse responseValue = responseBody.isBlank()? null: memberVarObjectMapper.readValue(responseBody, new TypeReference<MerchantIdResponse>() {});
        
        localVarResponse.body().close();

        return new ApiResponse<MerchantIdResponse>(
            localVarResponse.statusCode(),
            localVarResponse.headers().map(),
            responseValue
        );
      } finally {
      }
    } catch (IOException e) {
      throw new ApiException(e);
    }
    catch (InterruptedException e) {
      Thread.currentThread().interrupt();
      throw new ApiException(e);
    }
  }

  private HttpRequest.Builder merchantIdsUpdateInstanceRequestBuilder(@jakarta.annotation.Nonnull String id, @jakarta.annotation.Nonnull MerchantIdUpdateRequest merchantIdUpdateRequest, Map<String, String> headers) throws ApiException {
    // verify the required parameter 'id' is set
    if (id == null) {
      throw new ApiException(400, "Missing the required parameter 'id' when calling merchantIdsUpdateInstance");
    }
    // verify the required parameter 'merchantIdUpdateRequest' is set
    if (merchantIdUpdateRequest == null) {
      throw new ApiException(400, "Missing the required parameter 'merchantIdUpdateRequest' when calling merchantIdsUpdateInstance");
    }

    HttpRequest.Builder localVarRequestBuilder = HttpRequest.newBuilder();

    String localVarPath = "/v1/merchantIds/{id}"
        .replace("{id}", ApiClient.urlEncode(id.toString()));

    localVarRequestBuilder.uri(URI.create(memberVarBaseUri + localVarPath));

    localVarRequestBuilder.header("Content-Type", "application/json");
    localVarRequestBuilder.header("Accept", "application/json");

    try {
      byte[] localVarPostBody = memberVarObjectMapper.writeValueAsBytes(merchantIdUpdateRequest);
      localVarRequestBuilder.method("PATCH", HttpRequest.BodyPublishers.ofByteArray(localVarPostBody));
    } catch (IOException e) {
      throw new ApiException(e);
    }
    if (memberVarReadTimeout != null) {
      localVarRequestBuilder.timeout(memberVarReadTimeout);
    }
    // Add custom headers if provided
    localVarRequestBuilder = HttpRequestBuilderExtensions.withAdditionalHeaders(localVarRequestBuilder, headers);
    if (memberVarInterceptor != null) {
      memberVarInterceptor.accept(localVarRequestBuilder);
    }
    return localVarRequestBuilder;
  }

}
