/*
 * App Store Connect API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 4.2
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

package com.adguard.stores.appstoreconnect.api;

import com.adguard.stores.appstoreconnect.ApiClient;
import com.adguard.stores.appstoreconnect.ApiException;
import com.adguard.stores.appstoreconnect.ApiResponse;
import com.adguard.stores.appstoreconnect.Configuration;
import com.adguard.stores.appstoreconnect.Pair;

import com.adguard.stores.appstoreconnect.model.ErrorResponse;
import com.adguard.stores.appstoreconnect.model.TerritoryAvailabilityResponse;
import com.adguard.stores.appstoreconnect.model.TerritoryAvailabilityUpdateRequest;

import com.fasterxml.jackson.core.type.TypeReference;
import com.fasterxml.jackson.databind.ObjectMapper;

import java.io.InputStream;
import java.io.ByteArrayInputStream;
import java.io.ByteArrayOutputStream;
import java.io.File;
import java.io.IOException;
import java.io.OutputStream;
import java.net.http.HttpRequest;
import java.nio.channels.Channels;
import java.nio.channels.Pipe;
import java.net.URI;
import java.net.http.HttpClient;
import java.net.http.HttpRequest;
import java.net.http.HttpResponse;
import java.time.Duration;

import java.util.ArrayList;
import java.util.StringJoiner;
import java.util.List;
import java.util.Map;
import java.util.Set;
import java.util.Locale;
import java.util.function.Consumer;

@jakarta.annotation.Generated(value = "org.openapitools.codegen.languages.JavaClientCodegen", comments = "Generator version: 7.17.0")
public class TerritoryAvailabilitiesApi {
  /**
   * Utility class for extending HttpRequest.Builder functionality.
   */
  private static class HttpRequestBuilderExtensions {
    /**
     * Adds additional headers to the provided HttpRequest.Builder. Useful for adding method/endpoint specific headers.
     *
     * @param builder the HttpRequest.Builder to which headers will be added
     * @param headers a map of header names and values to add; may be null
     * @return the same HttpRequest.Builder instance with the additional headers set
     */
    static HttpRequest.Builder withAdditionalHeaders(HttpRequest.Builder builder, Map<String, String> headers) {
        if (headers != null) {
            for (Map.Entry<String, String> entry : headers.entrySet()) {
                builder.header(entry.getKey(), entry.getValue());
            }
        }
        return builder;
    }
  }
  private final HttpClient memberVarHttpClient;
  private final ObjectMapper memberVarObjectMapper;
  private final String memberVarBaseUri;
  private final Consumer<HttpRequest.Builder> memberVarInterceptor;
  private final Duration memberVarReadTimeout;
  private final Consumer<HttpResponse<InputStream>> memberVarResponseInterceptor;
  private final Consumer<HttpResponse<String>> memberVarAsyncResponseInterceptor;

  public TerritoryAvailabilitiesApi() {
    this(Configuration.getDefaultApiClient());
  }

  public TerritoryAvailabilitiesApi(ApiClient apiClient) {
    memberVarHttpClient = apiClient.getHttpClient();
    memberVarObjectMapper = apiClient.getObjectMapper();
    memberVarBaseUri = apiClient.getBaseUri();
    memberVarInterceptor = apiClient.getRequestInterceptor();
    memberVarReadTimeout = apiClient.getReadTimeout();
    memberVarResponseInterceptor = apiClient.getResponseInterceptor();
    memberVarAsyncResponseInterceptor = apiClient.getAsyncResponseInterceptor();
  }


  protected ApiException getApiException(String operationId, HttpResponse<InputStream> response) throws IOException {
    String body = response.body() == null ? null : new String(response.body().readAllBytes());
    String message = formatExceptionMessage(operationId, response.statusCode(), body);
    return new ApiException(response.statusCode(), message, response.headers(), body);
  }

  private String formatExceptionMessage(String operationId, int statusCode, String body) {
    if (body == null || body.isEmpty()) {
      body = "[no body]";
    }
    return operationId + " call failed with: " + statusCode + " - " + body;
  }

  /**
   * Download file from the given response.
   *
   * @param response Response
   * @return File
   * @throws ApiException If fail to read file content from response and write to disk
   */
  public File downloadFileFromResponse(HttpResponse<InputStream> response) throws ApiException {
    try {
      File file = prepareDownloadFile(response);
      java.nio.file.Files.copy(response.body(), file.toPath(), java.nio.file.StandardCopyOption.REPLACE_EXISTING);
      return file;
    } catch (IOException e) {
      throw new ApiException(e);
    }
  }

  /**
   * <p>Prepare the file for download from the response.</p>
   *
   * @param response a {@link java.net.http.HttpResponse} object.
   * @return a {@link java.io.File} object.
   * @throws java.io.IOException if any.
   */
  private File prepareDownloadFile(HttpResponse<InputStream> response) throws IOException {
    String filename = null;
    java.util.Optional<String> contentDisposition = response.headers().firstValue("Content-Disposition");
    if (contentDisposition.isPresent() && !"".equals(contentDisposition.get())) {
      // Get filename from the Content-Disposition header.
      java.util.regex.Pattern pattern = java.util.regex.Pattern.compile("filename=['\"]?([^'\"\\s]+)['\"]?");
      java.util.regex.Matcher matcher = pattern.matcher(contentDisposition.get());
      if (matcher.find())
        filename = matcher.group(1);
    }
    File file = null;
    if (filename != null) {
      java.nio.file.Path tempDir = java.nio.file.Files.createTempDirectory("swagger-gen-native");
      java.nio.file.Path filePath = java.nio.file.Files.createFile(tempDir.resolve(filename));
      file = filePath.toFile();
      tempDir.toFile().deleteOnExit();   // best effort cleanup
      file.deleteOnExit(); // best effort cleanup
    } else {
      file = java.nio.file.Files.createTempFile("download-", "").toFile();
      file.deleteOnExit(); // best effort cleanup
    }
    return file;
  }

  /**
   * 
   * 
   * @param id the id of the requested resource (required)
   * @param territoryAvailabilityUpdateRequest TerritoryAvailability representation (required)
   * @return TerritoryAvailabilityResponse
   * @throws ApiException if fails to make API call
   */
  public TerritoryAvailabilityResponse territoryAvailabilitiesUpdateInstance(@jakarta.annotation.Nonnull String id, @jakarta.annotation.Nonnull TerritoryAvailabilityUpdateRequest territoryAvailabilityUpdateRequest) throws ApiException {
    return territoryAvailabilitiesUpdateInstance(id, territoryAvailabilityUpdateRequest, null);
  }

  /**
   * 
   * 
   * @param id the id of the requested resource (required)
   * @param territoryAvailabilityUpdateRequest TerritoryAvailability representation (required)
   * @param headers Optional headers to include in the request
   * @return TerritoryAvailabilityResponse
   * @throws ApiException if fails to make API call
   */
  public TerritoryAvailabilityResponse territoryAvailabilitiesUpdateInstance(@jakarta.annotation.Nonnull String id, @jakarta.annotation.Nonnull TerritoryAvailabilityUpdateRequest territoryAvailabilityUpdateRequest, Map<String, String> headers) throws ApiException {
    ApiResponse<TerritoryAvailabilityResponse> localVarResponse = territoryAvailabilitiesUpdateInstanceWithHttpInfo(id, territoryAvailabilityUpdateRequest, headers);
    return localVarResponse.getData();
  }

  /**
   * 
   * 
   * @param id the id of the requested resource (required)
   * @param territoryAvailabilityUpdateRequest TerritoryAvailability representation (required)
   * @return ApiResponse&lt;TerritoryAvailabilityResponse&gt;
   * @throws ApiException if fails to make API call
   */
  public ApiResponse<TerritoryAvailabilityResponse> territoryAvailabilitiesUpdateInstanceWithHttpInfo(@jakarta.annotation.Nonnull String id, @jakarta.annotation.Nonnull TerritoryAvailabilityUpdateRequest territoryAvailabilityUpdateRequest) throws ApiException {
    return territoryAvailabilitiesUpdateInstanceWithHttpInfo(id, territoryAvailabilityUpdateRequest, null);
  }

  /**
   * 
   * 
   * @param id the id of the requested resource (required)
   * @param territoryAvailabilityUpdateRequest TerritoryAvailability representation (required)
   * @param headers Optional headers to include in the request
   * @return ApiResponse&lt;TerritoryAvailabilityResponse&gt;
   * @throws ApiException if fails to make API call
   */
  public ApiResponse<TerritoryAvailabilityResponse> territoryAvailabilitiesUpdateInstanceWithHttpInfo(@jakarta.annotation.Nonnull String id, @jakarta.annotation.Nonnull TerritoryAvailabilityUpdateRequest territoryAvailabilityUpdateRequest, Map<String, String> headers) throws ApiException {
    HttpRequest.Builder localVarRequestBuilder = territoryAvailabilitiesUpdateInstanceRequestBuilder(id, territoryAvailabilityUpdateRequest, headers);
    try {
      HttpResponse<InputStream> localVarResponse = memberVarHttpClient.send(
          localVarRequestBuilder.build(),
          HttpResponse.BodyHandlers.ofInputStream());
      if (memberVarResponseInterceptor != null) {
        memberVarResponseInterceptor.accept(localVarResponse);
      }
      try {
        if (localVarResponse.statusCode()/ 100 != 2) {
          throw getApiException("territoryAvailabilitiesUpdateInstance", localVarResponse);
        }
        if (localVarResponse.body() == null) {
          return new ApiResponse<TerritoryAvailabilityResponse>(
              localVarResponse.statusCode(),
              localVarResponse.headers().map(),
              null
          );
        }

        
        
        String responseBody = new String(localVarResponse.body().readAllBytes());
        TerritoryAvailabilityResponse responseValue = responseBody.isBlank()? null: memberVarObjectMapper.readValue(responseBody, new TypeReference<TerritoryAvailabilityResponse>() {});
        
        localVarResponse.body().close();

        return new ApiResponse<TerritoryAvailabilityResponse>(
            localVarResponse.statusCode(),
            localVarResponse.headers().map(),
            responseValue
        );
      } finally {
      }
    } catch (IOException e) {
      throw new ApiException(e);
    }
    catch (InterruptedException e) {
      Thread.currentThread().interrupt();
      throw new ApiException(e);
    }
  }

  private HttpRequest.Builder territoryAvailabilitiesUpdateInstanceRequestBuilder(@jakarta.annotation.Nonnull String id, @jakarta.annotation.Nonnull TerritoryAvailabilityUpdateRequest territoryAvailabilityUpdateRequest, Map<String, String> headers) throws ApiException {
    // verify the required parameter 'id' is set
    if (id == null) {
      throw new ApiException(400, "Missing the required parameter 'id' when calling territoryAvailabilitiesUpdateInstance");
    }
    // verify the required parameter 'territoryAvailabilityUpdateRequest' is set
    if (territoryAvailabilityUpdateRequest == null) {
      throw new ApiException(400, "Missing the required parameter 'territoryAvailabilityUpdateRequest' when calling territoryAvailabilitiesUpdateInstance");
    }

    HttpRequest.Builder localVarRequestBuilder = HttpRequest.newBuilder();

    String localVarPath = "/v1/territoryAvailabilities/{id}"
        .replace("{id}", ApiClient.urlEncode(id.toString()));

    localVarRequestBuilder.uri(URI.create(memberVarBaseUri + localVarPath));

    localVarRequestBuilder.header("Content-Type", "application/json");
    localVarRequestBuilder.header("Accept", "application/json");

    try {
      byte[] localVarPostBody = memberVarObjectMapper.writeValueAsBytes(territoryAvailabilityUpdateRequest);
      localVarRequestBuilder.method("PATCH", HttpRequest.BodyPublishers.ofByteArray(localVarPostBody));
    } catch (IOException e) {
      throw new ApiException(e);
    }
    if (memberVarReadTimeout != null) {
      localVarRequestBuilder.timeout(memberVarReadTimeout);
    }
    // Add custom headers if provided
    localVarRequestBuilder = HttpRequestBuilderExtensions.withAdditionalHeaders(localVarRequestBuilder, headers);
    if (memberVarInterceptor != null) {
      memberVarInterceptor.accept(localVarRequestBuilder);
    }
    return localVarRequestBuilder;
  }

}
