/*
 * App Store Connect API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 4.2
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package com.adguard.stores.appstoreconnect.model;

import java.net.URLEncoder;
import java.nio.charset.StandardCharsets;
import java.util.StringJoiner;
import java.util.Objects;
import java.util.Map;
import java.util.HashMap;
import java.util.Locale;
import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonTypeName;
import com.fasterxml.jackson.annotation.JsonValue;
import java.util.ArrayList;
import java.util.Arrays;
import java.util.List;
import com.fasterxml.jackson.annotation.JsonPropertyOrder;


import com.adguard.stores.appstoreconnect.ApiClient;
/**
 * AndroidToIosAppMappingDetailAttributes
 */
@JsonPropertyOrder({
  AndroidToIosAppMappingDetailAttributes.JSON_PROPERTY_PACKAGE_NAME,
  AndroidToIosAppMappingDetailAttributes.JSON_PROPERTY_APP_SIGNING_KEY_PUBLIC_CERTIFICATE_SHA256_FINGERPRINTS
})
@jakarta.annotation.Generated(value = "org.openapitools.codegen.languages.JavaClientCodegen", comments = "Generator version: 7.17.0")
public class AndroidToIosAppMappingDetailAttributes {
  public static final String JSON_PROPERTY_PACKAGE_NAME = "packageName";
  @jakarta.annotation.Nullable
  private String packageName;

  public static final String JSON_PROPERTY_APP_SIGNING_KEY_PUBLIC_CERTIFICATE_SHA256_FINGERPRINTS = "appSigningKeyPublicCertificateSha256Fingerprints";
  @jakarta.annotation.Nullable
  private List<String> appSigningKeyPublicCertificateSha256Fingerprints = new ArrayList<>();

  public AndroidToIosAppMappingDetailAttributes() { 
  }

  public AndroidToIosAppMappingDetailAttributes packageName(@jakarta.annotation.Nullable String packageName) {
    this.packageName = packageName;
    return this;
  }

  /**
   * Get packageName
   * @return packageName
   */
  @jakarta.annotation.Nullable
  @JsonProperty(value = JSON_PROPERTY_PACKAGE_NAME, required = false)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public String getPackageName() {
    return packageName;
  }


  @JsonProperty(value = JSON_PROPERTY_PACKAGE_NAME, required = false)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setPackageName(@jakarta.annotation.Nullable String packageName) {
    this.packageName = packageName;
  }


  public AndroidToIosAppMappingDetailAttributes appSigningKeyPublicCertificateSha256Fingerprints(@jakarta.annotation.Nullable List<String> appSigningKeyPublicCertificateSha256Fingerprints) {
    this.appSigningKeyPublicCertificateSha256Fingerprints = appSigningKeyPublicCertificateSha256Fingerprints;
    return this;
  }

  public AndroidToIosAppMappingDetailAttributes addAppSigningKeyPublicCertificateSha256FingerprintsItem(String appSigningKeyPublicCertificateSha256FingerprintsItem) {
    if (this.appSigningKeyPublicCertificateSha256Fingerprints == null) {
      this.appSigningKeyPublicCertificateSha256Fingerprints = new ArrayList<>();
    }
    this.appSigningKeyPublicCertificateSha256Fingerprints.add(appSigningKeyPublicCertificateSha256FingerprintsItem);
    return this;
  }

  /**
   * Get appSigningKeyPublicCertificateSha256Fingerprints
   * @return appSigningKeyPublicCertificateSha256Fingerprints
   */
  @jakarta.annotation.Nullable
  @JsonProperty(value = JSON_PROPERTY_APP_SIGNING_KEY_PUBLIC_CERTIFICATE_SHA256_FINGERPRINTS, required = false)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public List<String> getAppSigningKeyPublicCertificateSha256Fingerprints() {
    return appSigningKeyPublicCertificateSha256Fingerprints;
  }


  @JsonProperty(value = JSON_PROPERTY_APP_SIGNING_KEY_PUBLIC_CERTIFICATE_SHA256_FINGERPRINTS, required = false)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setAppSigningKeyPublicCertificateSha256Fingerprints(@jakarta.annotation.Nullable List<String> appSigningKeyPublicCertificateSha256Fingerprints) {
    this.appSigningKeyPublicCertificateSha256Fingerprints = appSigningKeyPublicCertificateSha256Fingerprints;
  }


  /**
   * Return true if this AndroidToIosAppMappingDetail_attributes object is equal to o.
   */
  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    AndroidToIosAppMappingDetailAttributes androidToIosAppMappingDetailAttributes = (AndroidToIosAppMappingDetailAttributes) o;
    return Objects.equals(this.packageName, androidToIosAppMappingDetailAttributes.packageName) &&
        Objects.equals(this.appSigningKeyPublicCertificateSha256Fingerprints, androidToIosAppMappingDetailAttributes.appSigningKeyPublicCertificateSha256Fingerprints);
  }

  @Override
  public int hashCode() {
    return Objects.hash(packageName, appSigningKeyPublicCertificateSha256Fingerprints);
  }

  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class AndroidToIosAppMappingDetailAttributes {\n");
    sb.append("    packageName: ").append(toIndentedString(packageName)).append("\n");
    sb.append("    appSigningKeyPublicCertificateSha256Fingerprints: ").append(toIndentedString(appSigningKeyPublicCertificateSha256Fingerprints)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

  /**
   * Convert the instance into URL query string.
   *
   * @return URL query string
   */
  public String toUrlQueryString() {
    return toUrlQueryString(null);
  }

  /**
   * Convert the instance into URL query string.
   *
   * @param prefix prefix of the query string
   * @return URL query string
   */
  public String toUrlQueryString(String prefix) {
    String suffix = "";
    String containerSuffix = "";
    String containerPrefix = "";
    if (prefix == null) {
      // style=form, explode=true, e.g. /pet?name=cat&type=manx
      prefix = "";
    } else {
      // deepObject style e.g. /pet?id[name]=cat&id[type]=manx
      prefix = prefix + "[";
      suffix = "]";
      containerSuffix = "]";
      containerPrefix = "[";
    }

    StringJoiner joiner = new StringJoiner("&");

    // add `packageName` to the URL query string
    if (getPackageName() != null) {
      joiner.add(String.format(Locale.ROOT, "%spackageName%s=%s", prefix, suffix, ApiClient.urlEncode(ApiClient.valueToString(getPackageName()))));
    }

    // add `appSigningKeyPublicCertificateSha256Fingerprints` to the URL query string
    if (getAppSigningKeyPublicCertificateSha256Fingerprints() != null) {
      for (int i = 0; i < getAppSigningKeyPublicCertificateSha256Fingerprints().size(); i++) {
        joiner.add(String.format(Locale.ROOT, "%sappSigningKeyPublicCertificateSha256Fingerprints%s%s=%s", prefix, suffix,
            "".equals(suffix) ? "" : String.format(Locale.ROOT, "%s%d%s", containerPrefix, i, containerSuffix),
            ApiClient.urlEncode(ApiClient.valueToString(getAppSigningKeyPublicCertificateSha256Fingerprints().get(i)))));
      }
    }

    return joiner.toString();
  }
}

