/*
 * App Store Connect API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 4.2
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package com.adguard.stores.appstoreconnect.model;

import java.net.URLEncoder;
import java.nio.charset.StandardCharsets;
import java.util.StringJoiner;
import java.util.Objects;
import java.util.Map;
import java.util.HashMap;
import java.util.Locale;
import com.adguard.stores.appstoreconnect.model.AccessibilityDeclarationCreateRequestDataRelationshipsApp;
import com.adguard.stores.appstoreconnect.model.AppAvailabilityV2CreateRequestDataRelationshipsTerritoryAvailabilities;
import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonTypeName;
import com.fasterxml.jackson.annotation.JsonValue;
import java.util.Arrays;
import com.fasterxml.jackson.annotation.JsonPropertyOrder;


import com.adguard.stores.appstoreconnect.ApiClient;
/**
 * AppAvailabilityV2CreateRequestDataRelationships
 */
@JsonPropertyOrder({
  AppAvailabilityV2CreateRequestDataRelationships.JSON_PROPERTY_APP,
  AppAvailabilityV2CreateRequestDataRelationships.JSON_PROPERTY_TERRITORY_AVAILABILITIES
})
@jakarta.annotation.Generated(value = "org.openapitools.codegen.languages.JavaClientCodegen", comments = "Generator version: 7.17.0")
public class AppAvailabilityV2CreateRequestDataRelationships {
  public static final String JSON_PROPERTY_APP = "app";
  @jakarta.annotation.Nonnull
  private AccessibilityDeclarationCreateRequestDataRelationshipsApp app;

  public static final String JSON_PROPERTY_TERRITORY_AVAILABILITIES = "territoryAvailabilities";
  @jakarta.annotation.Nonnull
  private AppAvailabilityV2CreateRequestDataRelationshipsTerritoryAvailabilities territoryAvailabilities;

  public AppAvailabilityV2CreateRequestDataRelationships() { 
  }

  public AppAvailabilityV2CreateRequestDataRelationships app(@jakarta.annotation.Nonnull AccessibilityDeclarationCreateRequestDataRelationshipsApp app) {
    this.app = app;
    return this;
  }

  /**
   * Get app
   * @return app
   */
  @jakarta.annotation.Nonnull
  @JsonProperty(value = JSON_PROPERTY_APP, required = true)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)
  public AccessibilityDeclarationCreateRequestDataRelationshipsApp getApp() {
    return app;
  }


  @JsonProperty(value = JSON_PROPERTY_APP, required = true)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)
  public void setApp(@jakarta.annotation.Nonnull AccessibilityDeclarationCreateRequestDataRelationshipsApp app) {
    this.app = app;
  }


  public AppAvailabilityV2CreateRequestDataRelationships territoryAvailabilities(@jakarta.annotation.Nonnull AppAvailabilityV2CreateRequestDataRelationshipsTerritoryAvailabilities territoryAvailabilities) {
    this.territoryAvailabilities = territoryAvailabilities;
    return this;
  }

  /**
   * Get territoryAvailabilities
   * @return territoryAvailabilities
   */
  @jakarta.annotation.Nonnull
  @JsonProperty(value = JSON_PROPERTY_TERRITORY_AVAILABILITIES, required = true)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)
  public AppAvailabilityV2CreateRequestDataRelationshipsTerritoryAvailabilities getTerritoryAvailabilities() {
    return territoryAvailabilities;
  }


  @JsonProperty(value = JSON_PROPERTY_TERRITORY_AVAILABILITIES, required = true)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)
  public void setTerritoryAvailabilities(@jakarta.annotation.Nonnull AppAvailabilityV2CreateRequestDataRelationshipsTerritoryAvailabilities territoryAvailabilities) {
    this.territoryAvailabilities = territoryAvailabilities;
  }


  /**
   * Return true if this AppAvailabilityV2CreateRequest_data_relationships object is equal to o.
   */
  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    AppAvailabilityV2CreateRequestDataRelationships appAvailabilityV2CreateRequestDataRelationships = (AppAvailabilityV2CreateRequestDataRelationships) o;
    return Objects.equals(this.app, appAvailabilityV2CreateRequestDataRelationships.app) &&
        Objects.equals(this.territoryAvailabilities, appAvailabilityV2CreateRequestDataRelationships.territoryAvailabilities);
  }

  @Override
  public int hashCode() {
    return Objects.hash(app, territoryAvailabilities);
  }

  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class AppAvailabilityV2CreateRequestDataRelationships {\n");
    sb.append("    app: ").append(toIndentedString(app)).append("\n");
    sb.append("    territoryAvailabilities: ").append(toIndentedString(territoryAvailabilities)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

  /**
   * Convert the instance into URL query string.
   *
   * @return URL query string
   */
  public String toUrlQueryString() {
    return toUrlQueryString(null);
  }

  /**
   * Convert the instance into URL query string.
   *
   * @param prefix prefix of the query string
   * @return URL query string
   */
  public String toUrlQueryString(String prefix) {
    String suffix = "";
    String containerSuffix = "";
    String containerPrefix = "";
    if (prefix == null) {
      // style=form, explode=true, e.g. /pet?name=cat&type=manx
      prefix = "";
    } else {
      // deepObject style e.g. /pet?id[name]=cat&id[type]=manx
      prefix = prefix + "[";
      suffix = "]";
      containerSuffix = "]";
      containerPrefix = "[";
    }

    StringJoiner joiner = new StringJoiner("&");

    // add `app` to the URL query string
    if (getApp() != null) {
      joiner.add(getApp().toUrlQueryString(prefix + "app" + suffix));
    }

    // add `territoryAvailabilities` to the URL query string
    if (getTerritoryAvailabilities() != null) {
      joiner.add(getTerritoryAvailabilities().toUrlQueryString(prefix + "territoryAvailabilities" + suffix));
    }

    return joiner.toString();
  }
}

