/*
 * App Store Connect API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 4.2
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package com.adguard.stores.appstoreconnect.model;

import java.net.URLEncoder;
import java.nio.charset.StandardCharsets;
import java.util.StringJoiner;
import java.util.Objects;
import java.util.Map;
import java.util.HashMap;
import java.util.Locale;
import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonTypeName;
import com.fasterxml.jackson.annotation.JsonValue;
import java.net.URI;
import java.util.Arrays;
import com.fasterxml.jackson.annotation.JsonPropertyOrder;


import com.adguard.stores.appstoreconnect.ApiClient;
/**
 * AppCustomProductPageVersionAttributes
 */
@JsonPropertyOrder({
  AppCustomProductPageVersionAttributes.JSON_PROPERTY_VERSION,
  AppCustomProductPageVersionAttributes.JSON_PROPERTY_STATE,
  AppCustomProductPageVersionAttributes.JSON_PROPERTY_DEEP_LINK
})
@jakarta.annotation.Generated(value = "org.openapitools.codegen.languages.JavaClientCodegen", comments = "Generator version: 7.17.0")
public class AppCustomProductPageVersionAttributes {
  public static final String JSON_PROPERTY_VERSION = "version";
  @jakarta.annotation.Nullable
  private String version;

  /**
   * Gets or Sets state
   */
  public enum StateEnum {
    PREPARE_FOR_SUBMISSION(String.valueOf("PREPARE_FOR_SUBMISSION")),
    
    READY_FOR_REVIEW(String.valueOf("READY_FOR_REVIEW")),
    
    WAITING_FOR_REVIEW(String.valueOf("WAITING_FOR_REVIEW")),
    
    IN_REVIEW(String.valueOf("IN_REVIEW")),
    
    ACCEPTED(String.valueOf("ACCEPTED")),
    
    APPROVED(String.valueOf("APPROVED")),
    
    REPLACED_WITH_NEW_VERSION(String.valueOf("REPLACED_WITH_NEW_VERSION")),
    
    REJECTED(String.valueOf("REJECTED"));

    private String value;

    StateEnum(String value) {
      this.value = value;
    }

    @JsonValue
    public String getValue() {
      return value;
    }

    @Override
    public String toString() {
      return String.valueOf(value);
    }

    @JsonCreator
    public static StateEnum fromValue(String value) {
      for (StateEnum b : StateEnum.values()) {
        if (b.value.equals(value)) {
          return b;
        }
      }
      throw new IllegalArgumentException("Unexpected value '" + value + "'");
    }
  }

  public static final String JSON_PROPERTY_STATE = "state";
  @jakarta.annotation.Nullable
  private StateEnum state;

  public static final String JSON_PROPERTY_DEEP_LINK = "deepLink";
  @jakarta.annotation.Nullable
  private URI deepLink;

  public AppCustomProductPageVersionAttributes() { 
  }

  public AppCustomProductPageVersionAttributes version(@jakarta.annotation.Nullable String version) {
    this.version = version;
    return this;
  }

  /**
   * Get version
   * @return version
   */
  @jakarta.annotation.Nullable
  @JsonProperty(value = JSON_PROPERTY_VERSION, required = false)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public String getVersion() {
    return version;
  }


  @JsonProperty(value = JSON_PROPERTY_VERSION, required = false)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setVersion(@jakarta.annotation.Nullable String version) {
    this.version = version;
  }


  public AppCustomProductPageVersionAttributes state(@jakarta.annotation.Nullable StateEnum state) {
    this.state = state;
    return this;
  }

  /**
   * Get state
   * @return state
   */
  @jakarta.annotation.Nullable
  @JsonProperty(value = JSON_PROPERTY_STATE, required = false)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public StateEnum getState() {
    return state;
  }


  @JsonProperty(value = JSON_PROPERTY_STATE, required = false)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setState(@jakarta.annotation.Nullable StateEnum state) {
    this.state = state;
  }


  public AppCustomProductPageVersionAttributes deepLink(@jakarta.annotation.Nullable URI deepLink) {
    this.deepLink = deepLink;
    return this;
  }

  /**
   * Get deepLink
   * @return deepLink
   */
  @jakarta.annotation.Nullable
  @JsonProperty(value = JSON_PROPERTY_DEEP_LINK, required = false)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public URI getDeepLink() {
    return deepLink;
  }


  @JsonProperty(value = JSON_PROPERTY_DEEP_LINK, required = false)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setDeepLink(@jakarta.annotation.Nullable URI deepLink) {
    this.deepLink = deepLink;
  }


  /**
   * Return true if this AppCustomProductPageVersion_attributes object is equal to o.
   */
  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    AppCustomProductPageVersionAttributes appCustomProductPageVersionAttributes = (AppCustomProductPageVersionAttributes) o;
    return Objects.equals(this.version, appCustomProductPageVersionAttributes.version) &&
        Objects.equals(this.state, appCustomProductPageVersionAttributes.state) &&
        Objects.equals(this.deepLink, appCustomProductPageVersionAttributes.deepLink);
  }

  @Override
  public int hashCode() {
    return Objects.hash(version, state, deepLink);
  }

  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class AppCustomProductPageVersionAttributes {\n");
    sb.append("    version: ").append(toIndentedString(version)).append("\n");
    sb.append("    state: ").append(toIndentedString(state)).append("\n");
    sb.append("    deepLink: ").append(toIndentedString(deepLink)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

  /**
   * Convert the instance into URL query string.
   *
   * @return URL query string
   */
  public String toUrlQueryString() {
    return toUrlQueryString(null);
  }

  /**
   * Convert the instance into URL query string.
   *
   * @param prefix prefix of the query string
   * @return URL query string
   */
  public String toUrlQueryString(String prefix) {
    String suffix = "";
    String containerSuffix = "";
    String containerPrefix = "";
    if (prefix == null) {
      // style=form, explode=true, e.g. /pet?name=cat&type=manx
      prefix = "";
    } else {
      // deepObject style e.g. /pet?id[name]=cat&id[type]=manx
      prefix = prefix + "[";
      suffix = "]";
      containerSuffix = "]";
      containerPrefix = "[";
    }

    StringJoiner joiner = new StringJoiner("&");

    // add `version` to the URL query string
    if (getVersion() != null) {
      joiner.add(String.format(Locale.ROOT, "%sversion%s=%s", prefix, suffix, ApiClient.urlEncode(ApiClient.valueToString(getVersion()))));
    }

    // add `state` to the URL query string
    if (getState() != null) {
      joiner.add(String.format(Locale.ROOT, "%sstate%s=%s", prefix, suffix, ApiClient.urlEncode(ApiClient.valueToString(getState()))));
    }

    // add `deepLink` to the URL query string
    if (getDeepLink() != null) {
      joiner.add(String.format(Locale.ROOT, "%sdeepLink%s=%s", prefix, suffix, ApiClient.urlEncode(ApiClient.valueToString(getDeepLink()))));
    }

    return joiner.toString();
  }
}

