/*
 * App Store Connect API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 4.2
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package com.adguard.stores.appstoreconnect.model;

import java.net.URLEncoder;
import java.nio.charset.StandardCharsets;
import java.util.StringJoiner;
import java.util.Objects;
import java.util.Map;
import java.util.HashMap;
import java.util.Locale;
import com.adguard.stores.appstoreconnect.model.AppCategoryRelationshipsParent;
import com.adguard.stores.appstoreconnect.model.AppCategoryRelationshipsSubcategories;
import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonTypeName;
import com.fasterxml.jackson.annotation.JsonValue;
import java.util.Arrays;
import com.fasterxml.jackson.annotation.JsonPropertyOrder;


import com.adguard.stores.appstoreconnect.ApiClient;
/**
 * AppCategoryRelationships
 */
@JsonPropertyOrder({
  AppCategoryRelationships.JSON_PROPERTY_SUBCATEGORIES,
  AppCategoryRelationships.JSON_PROPERTY_PARENT
})
@jakarta.annotation.Generated(value = "org.openapitools.codegen.languages.JavaClientCodegen", comments = "Generator version: 7.17.0")
public class AppCategoryRelationships {
  public static final String JSON_PROPERTY_SUBCATEGORIES = "subcategories";
  @jakarta.annotation.Nullable
  private AppCategoryRelationshipsSubcategories subcategories;

  public static final String JSON_PROPERTY_PARENT = "parent";
  @jakarta.annotation.Nullable
  private AppCategoryRelationshipsParent parent;

  public AppCategoryRelationships() { 
  }

  public AppCategoryRelationships subcategories(@jakarta.annotation.Nullable AppCategoryRelationshipsSubcategories subcategories) {
    this.subcategories = subcategories;
    return this;
  }

  /**
   * Get subcategories
   * @return subcategories
   */
  @jakarta.annotation.Nullable
  @JsonProperty(value = JSON_PROPERTY_SUBCATEGORIES, required = false)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public AppCategoryRelationshipsSubcategories getSubcategories() {
    return subcategories;
  }


  @JsonProperty(value = JSON_PROPERTY_SUBCATEGORIES, required = false)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setSubcategories(@jakarta.annotation.Nullable AppCategoryRelationshipsSubcategories subcategories) {
    this.subcategories = subcategories;
  }


  public AppCategoryRelationships parent(@jakarta.annotation.Nullable AppCategoryRelationshipsParent parent) {
    this.parent = parent;
    return this;
  }

  /**
   * Get parent
   * @return parent
   */
  @jakarta.annotation.Nullable
  @JsonProperty(value = JSON_PROPERTY_PARENT, required = false)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public AppCategoryRelationshipsParent getParent() {
    return parent;
  }


  @JsonProperty(value = JSON_PROPERTY_PARENT, required = false)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setParent(@jakarta.annotation.Nullable AppCategoryRelationshipsParent parent) {
    this.parent = parent;
  }


  /**
   * Return true if this AppCategory_relationships object is equal to o.
   */
  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    AppCategoryRelationships appCategoryRelationships = (AppCategoryRelationships) o;
    return Objects.equals(this.subcategories, appCategoryRelationships.subcategories) &&
        Objects.equals(this.parent, appCategoryRelationships.parent);
  }

  @Override
  public int hashCode() {
    return Objects.hash(subcategories, parent);
  }

  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class AppCategoryRelationships {\n");
    sb.append("    subcategories: ").append(toIndentedString(subcategories)).append("\n");
    sb.append("    parent: ").append(toIndentedString(parent)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

  /**
   * Convert the instance into URL query string.
   *
   * @return URL query string
   */
  public String toUrlQueryString() {
    return toUrlQueryString(null);
  }

  /**
   * Convert the instance into URL query string.
   *
   * @param prefix prefix of the query string
   * @return URL query string
   */
  public String toUrlQueryString(String prefix) {
    String suffix = "";
    String containerSuffix = "";
    String containerPrefix = "";
    if (prefix == null) {
      // style=form, explode=true, e.g. /pet?name=cat&type=manx
      prefix = "";
    } else {
      // deepObject style e.g. /pet?id[name]=cat&id[type]=manx
      prefix = prefix + "[";
      suffix = "]";
      containerSuffix = "]";
      containerPrefix = "[";
    }

    StringJoiner joiner = new StringJoiner("&");

    // add `subcategories` to the URL query string
    if (getSubcategories() != null) {
      joiner.add(getSubcategories().toUrlQueryString(prefix + "subcategories" + suffix));
    }

    // add `parent` to the URL query string
    if (getParent() != null) {
      joiner.add(getParent().toUrlQueryString(prefix + "parent" + suffix));
    }

    return joiner.toString();
  }
}

