/*
 * App Store Connect API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 4.2
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package com.adguard.stores.appstoreconnect.model;

import java.net.URLEncoder;
import java.nio.charset.StandardCharsets;
import java.util.StringJoiner;
import java.util.Objects;
import java.util.Map;
import java.util.HashMap;
import java.util.Locale;
import com.adguard.stores.appstoreconnect.model.AppStoreVersionExperimentTreatmentLocalizationCreateRequestDataRelationshipsAppStoreVersionExperimentTreatment;
import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonTypeName;
import com.fasterxml.jackson.annotation.JsonValue;
import java.util.Arrays;
import com.fasterxml.jackson.annotation.JsonPropertyOrder;


import com.adguard.stores.appstoreconnect.ApiClient;
/**
 * AppStoreVersionExperimentTreatmentLocalizationCreateRequestDataRelationships
 */
@JsonPropertyOrder({
  AppStoreVersionExperimentTreatmentLocalizationCreateRequestDataRelationships.JSON_PROPERTY_APP_STORE_VERSION_EXPERIMENT_TREATMENT
})
@jakarta.annotation.Generated(value = "org.openapitools.codegen.languages.JavaClientCodegen", comments = "Generator version: 7.17.0")
public class AppStoreVersionExperimentTreatmentLocalizationCreateRequestDataRelationships {
  public static final String JSON_PROPERTY_APP_STORE_VERSION_EXPERIMENT_TREATMENT = "appStoreVersionExperimentTreatment";
  @jakarta.annotation.Nonnull
  private AppStoreVersionExperimentTreatmentLocalizationCreateRequestDataRelationshipsAppStoreVersionExperimentTreatment appStoreVersionExperimentTreatment;

  public AppStoreVersionExperimentTreatmentLocalizationCreateRequestDataRelationships() { 
  }

  public AppStoreVersionExperimentTreatmentLocalizationCreateRequestDataRelationships appStoreVersionExperimentTreatment(@jakarta.annotation.Nonnull AppStoreVersionExperimentTreatmentLocalizationCreateRequestDataRelationshipsAppStoreVersionExperimentTreatment appStoreVersionExperimentTreatment) {
    this.appStoreVersionExperimentTreatment = appStoreVersionExperimentTreatment;
    return this;
  }

  /**
   * Get appStoreVersionExperimentTreatment
   * @return appStoreVersionExperimentTreatment
   */
  @jakarta.annotation.Nonnull
  @JsonProperty(value = JSON_PROPERTY_APP_STORE_VERSION_EXPERIMENT_TREATMENT, required = true)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)
  public AppStoreVersionExperimentTreatmentLocalizationCreateRequestDataRelationshipsAppStoreVersionExperimentTreatment getAppStoreVersionExperimentTreatment() {
    return appStoreVersionExperimentTreatment;
  }


  @JsonProperty(value = JSON_PROPERTY_APP_STORE_VERSION_EXPERIMENT_TREATMENT, required = true)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)
  public void setAppStoreVersionExperimentTreatment(@jakarta.annotation.Nonnull AppStoreVersionExperimentTreatmentLocalizationCreateRequestDataRelationshipsAppStoreVersionExperimentTreatment appStoreVersionExperimentTreatment) {
    this.appStoreVersionExperimentTreatment = appStoreVersionExperimentTreatment;
  }


  /**
   * Return true if this AppStoreVersionExperimentTreatmentLocalizationCreateRequest_data_relationships object is equal to o.
   */
  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    AppStoreVersionExperimentTreatmentLocalizationCreateRequestDataRelationships appStoreVersionExperimentTreatmentLocalizationCreateRequestDataRelationships = (AppStoreVersionExperimentTreatmentLocalizationCreateRequestDataRelationships) o;
    return Objects.equals(this.appStoreVersionExperimentTreatment, appStoreVersionExperimentTreatmentLocalizationCreateRequestDataRelationships.appStoreVersionExperimentTreatment);
  }

  @Override
  public int hashCode() {
    return Objects.hash(appStoreVersionExperimentTreatment);
  }

  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class AppStoreVersionExperimentTreatmentLocalizationCreateRequestDataRelationships {\n");
    sb.append("    appStoreVersionExperimentTreatment: ").append(toIndentedString(appStoreVersionExperimentTreatment)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

  /**
   * Convert the instance into URL query string.
   *
   * @return URL query string
   */
  public String toUrlQueryString() {
    return toUrlQueryString(null);
  }

  /**
   * Convert the instance into URL query string.
   *
   * @param prefix prefix of the query string
   * @return URL query string
   */
  public String toUrlQueryString(String prefix) {
    String suffix = "";
    String containerSuffix = "";
    String containerPrefix = "";
    if (prefix == null) {
      // style=form, explode=true, e.g. /pet?name=cat&type=manx
      prefix = "";
    } else {
      // deepObject style e.g. /pet?id[name]=cat&id[type]=manx
      prefix = prefix + "[";
      suffix = "]";
      containerSuffix = "]";
      containerPrefix = "[";
    }

    StringJoiner joiner = new StringJoiner("&");

    // add `appStoreVersionExperimentTreatment` to the URL query string
    if (getAppStoreVersionExperimentTreatment() != null) {
      joiner.add(getAppStoreVersionExperimentTreatment().toUrlQueryString(prefix + "appStoreVersionExperimentTreatment" + suffix));
    }

    return joiner.toString();
  }
}

