/*
 * App Store Connect API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 4.2
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package com.adguard.stores.appstoreconnect.model;

import java.net.URLEncoder;
import java.nio.charset.StandardCharsets;
import java.util.StringJoiner;
import java.util.Objects;
import java.util.Map;
import java.util.HashMap;
import java.util.Locale;
import com.adguard.stores.appstoreconnect.model.BetaInviteType;
import com.adguard.stores.appstoreconnect.model.BetaTesterAttributesAppDevicesInner;
import com.adguard.stores.appstoreconnect.model.BetaTesterState;
import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonTypeName;
import com.fasterxml.jackson.annotation.JsonValue;
import java.util.ArrayList;
import java.util.Arrays;
import java.util.List;
import com.fasterxml.jackson.annotation.JsonPropertyOrder;


import com.adguard.stores.appstoreconnect.ApiClient;
/**
 * BetaTesterAttributes
 */
@JsonPropertyOrder({
  BetaTesterAttributes.JSON_PROPERTY_FIRST_NAME,
  BetaTesterAttributes.JSON_PROPERTY_LAST_NAME,
  BetaTesterAttributes.JSON_PROPERTY_EMAIL,
  BetaTesterAttributes.JSON_PROPERTY_INVITE_TYPE,
  BetaTesterAttributes.JSON_PROPERTY_STATE,
  BetaTesterAttributes.JSON_PROPERTY_APP_DEVICES
})
@jakarta.annotation.Generated(value = "org.openapitools.codegen.languages.JavaClientCodegen", comments = "Generator version: 7.17.0")
public class BetaTesterAttributes {
  public static final String JSON_PROPERTY_FIRST_NAME = "firstName";
  @jakarta.annotation.Nullable
  private String firstName;

  public static final String JSON_PROPERTY_LAST_NAME = "lastName";
  @jakarta.annotation.Nullable
  private String lastName;

  public static final String JSON_PROPERTY_EMAIL = "email";
  @jakarta.annotation.Nullable
  private String email;

  public static final String JSON_PROPERTY_INVITE_TYPE = "inviteType";
  @jakarta.annotation.Nullable
  private BetaInviteType inviteType;

  public static final String JSON_PROPERTY_STATE = "state";
  @jakarta.annotation.Nullable
  private BetaTesterState state;

  public static final String JSON_PROPERTY_APP_DEVICES = "appDevices";
  @jakarta.annotation.Nullable
  private List<BetaTesterAttributesAppDevicesInner> appDevices = new ArrayList<>();

  public BetaTesterAttributes() { 
  }

  public BetaTesterAttributes firstName(@jakarta.annotation.Nullable String firstName) {
    this.firstName = firstName;
    return this;
  }

  /**
   * Get firstName
   * @return firstName
   */
  @jakarta.annotation.Nullable
  @JsonProperty(value = JSON_PROPERTY_FIRST_NAME, required = false)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public String getFirstName() {
    return firstName;
  }


  @JsonProperty(value = JSON_PROPERTY_FIRST_NAME, required = false)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setFirstName(@jakarta.annotation.Nullable String firstName) {
    this.firstName = firstName;
  }


  public BetaTesterAttributes lastName(@jakarta.annotation.Nullable String lastName) {
    this.lastName = lastName;
    return this;
  }

  /**
   * Get lastName
   * @return lastName
   */
  @jakarta.annotation.Nullable
  @JsonProperty(value = JSON_PROPERTY_LAST_NAME, required = false)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public String getLastName() {
    return lastName;
  }


  @JsonProperty(value = JSON_PROPERTY_LAST_NAME, required = false)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setLastName(@jakarta.annotation.Nullable String lastName) {
    this.lastName = lastName;
  }


  public BetaTesterAttributes email(@jakarta.annotation.Nullable String email) {
    this.email = email;
    return this;
  }

  /**
   * Get email
   * @return email
   */
  @jakarta.annotation.Nullable
  @JsonProperty(value = JSON_PROPERTY_EMAIL, required = false)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public String getEmail() {
    return email;
  }


  @JsonProperty(value = JSON_PROPERTY_EMAIL, required = false)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setEmail(@jakarta.annotation.Nullable String email) {
    this.email = email;
  }


  public BetaTesterAttributes inviteType(@jakarta.annotation.Nullable BetaInviteType inviteType) {
    this.inviteType = inviteType;
    return this;
  }

  /**
   * Get inviteType
   * @return inviteType
   */
  @jakarta.annotation.Nullable
  @JsonProperty(value = JSON_PROPERTY_INVITE_TYPE, required = false)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public BetaInviteType getInviteType() {
    return inviteType;
  }


  @JsonProperty(value = JSON_PROPERTY_INVITE_TYPE, required = false)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setInviteType(@jakarta.annotation.Nullable BetaInviteType inviteType) {
    this.inviteType = inviteType;
  }


  public BetaTesterAttributes state(@jakarta.annotation.Nullable BetaTesterState state) {
    this.state = state;
    return this;
  }

  /**
   * Get state
   * @return state
   */
  @jakarta.annotation.Nullable
  @JsonProperty(value = JSON_PROPERTY_STATE, required = false)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public BetaTesterState getState() {
    return state;
  }


  @JsonProperty(value = JSON_PROPERTY_STATE, required = false)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setState(@jakarta.annotation.Nullable BetaTesterState state) {
    this.state = state;
  }


  public BetaTesterAttributes appDevices(@jakarta.annotation.Nullable List<BetaTesterAttributesAppDevicesInner> appDevices) {
    this.appDevices = appDevices;
    return this;
  }

  public BetaTesterAttributes addAppDevicesItem(BetaTesterAttributesAppDevicesInner appDevicesItem) {
    if (this.appDevices == null) {
      this.appDevices = new ArrayList<>();
    }
    this.appDevices.add(appDevicesItem);
    return this;
  }

  /**
   * Get appDevices
   * @return appDevices
   */
  @jakarta.annotation.Nullable
  @JsonProperty(value = JSON_PROPERTY_APP_DEVICES, required = false)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public List<BetaTesterAttributesAppDevicesInner> getAppDevices() {
    return appDevices;
  }


  @JsonProperty(value = JSON_PROPERTY_APP_DEVICES, required = false)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setAppDevices(@jakarta.annotation.Nullable List<BetaTesterAttributesAppDevicesInner> appDevices) {
    this.appDevices = appDevices;
  }


  /**
   * Return true if this BetaTester_attributes object is equal to o.
   */
  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    BetaTesterAttributes betaTesterAttributes = (BetaTesterAttributes) o;
    return Objects.equals(this.firstName, betaTesterAttributes.firstName) &&
        Objects.equals(this.lastName, betaTesterAttributes.lastName) &&
        Objects.equals(this.email, betaTesterAttributes.email) &&
        Objects.equals(this.inviteType, betaTesterAttributes.inviteType) &&
        Objects.equals(this.state, betaTesterAttributes.state) &&
        Objects.equals(this.appDevices, betaTesterAttributes.appDevices);
  }

  @Override
  public int hashCode() {
    return Objects.hash(firstName, lastName, email, inviteType, state, appDevices);
  }

  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class BetaTesterAttributes {\n");
    sb.append("    firstName: ").append(toIndentedString(firstName)).append("\n");
    sb.append("    lastName: ").append(toIndentedString(lastName)).append("\n");
    sb.append("    email: ").append(toIndentedString(email)).append("\n");
    sb.append("    inviteType: ").append(toIndentedString(inviteType)).append("\n");
    sb.append("    state: ").append(toIndentedString(state)).append("\n");
    sb.append("    appDevices: ").append(toIndentedString(appDevices)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

  /**
   * Convert the instance into URL query string.
   *
   * @return URL query string
   */
  public String toUrlQueryString() {
    return toUrlQueryString(null);
  }

  /**
   * Convert the instance into URL query string.
   *
   * @param prefix prefix of the query string
   * @return URL query string
   */
  public String toUrlQueryString(String prefix) {
    String suffix = "";
    String containerSuffix = "";
    String containerPrefix = "";
    if (prefix == null) {
      // style=form, explode=true, e.g. /pet?name=cat&type=manx
      prefix = "";
    } else {
      // deepObject style e.g. /pet?id[name]=cat&id[type]=manx
      prefix = prefix + "[";
      suffix = "]";
      containerSuffix = "]";
      containerPrefix = "[";
    }

    StringJoiner joiner = new StringJoiner("&");

    // add `firstName` to the URL query string
    if (getFirstName() != null) {
      joiner.add(String.format(Locale.ROOT, "%sfirstName%s=%s", prefix, suffix, ApiClient.urlEncode(ApiClient.valueToString(getFirstName()))));
    }

    // add `lastName` to the URL query string
    if (getLastName() != null) {
      joiner.add(String.format(Locale.ROOT, "%slastName%s=%s", prefix, suffix, ApiClient.urlEncode(ApiClient.valueToString(getLastName()))));
    }

    // add `email` to the URL query string
    if (getEmail() != null) {
      joiner.add(String.format(Locale.ROOT, "%semail%s=%s", prefix, suffix, ApiClient.urlEncode(ApiClient.valueToString(getEmail()))));
    }

    // add `inviteType` to the URL query string
    if (getInviteType() != null) {
      joiner.add(String.format(Locale.ROOT, "%sinviteType%s=%s", prefix, suffix, ApiClient.urlEncode(ApiClient.valueToString(getInviteType()))));
    }

    // add `state` to the URL query string
    if (getState() != null) {
      joiner.add(String.format(Locale.ROOT, "%sstate%s=%s", prefix, suffix, ApiClient.urlEncode(ApiClient.valueToString(getState()))));
    }

    // add `appDevices` to the URL query string
    if (getAppDevices() != null) {
      for (int i = 0; i < getAppDevices().size(); i++) {
        if (getAppDevices().get(i) != null) {
          joiner.add(getAppDevices().get(i).toUrlQueryString(String.format(Locale.ROOT, "%sappDevices%s%s", prefix, suffix,
          "".equals(suffix) ? "" : String.format(Locale.ROOT, "%s%d%s", containerPrefix, i, containerSuffix))));
        }
      }
    }

    return joiner.toString();
  }
}

