/*
 * App Store Connect API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 4.2
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package com.adguard.stores.appstoreconnect.model;

import java.net.URLEncoder;
import java.nio.charset.StandardCharsets;
import java.util.StringJoiner;
import java.util.Objects;
import java.util.Map;
import java.util.HashMap;
import java.util.Locale;
import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonTypeName;
import com.fasterxml.jackson.annotation.JsonValue;
import java.util.Arrays;
import com.fasterxml.jackson.annotation.JsonPropertyOrder;


import com.adguard.stores.appstoreconnect.ApiClient;
/**
 * CiBranchPatternsPatternsInner
 */
@JsonPropertyOrder({
  CiBranchPatternsPatternsInner.JSON_PROPERTY_PATTERN,
  CiBranchPatternsPatternsInner.JSON_PROPERTY_IS_PREFIX
})
@jakarta.annotation.Generated(value = "org.openapitools.codegen.languages.JavaClientCodegen", comments = "Generator version: 7.17.0")
public class CiBranchPatternsPatternsInner {
  public static final String JSON_PROPERTY_PATTERN = "pattern";
  @jakarta.annotation.Nullable
  private String pattern;

  public static final String JSON_PROPERTY_IS_PREFIX = "isPrefix";
  @jakarta.annotation.Nullable
  private Boolean isPrefix;

  public CiBranchPatternsPatternsInner() { 
  }

  public CiBranchPatternsPatternsInner pattern(@jakarta.annotation.Nullable String pattern) {
    this.pattern = pattern;
    return this;
  }

  /**
   * Get pattern
   * @return pattern
   */
  @jakarta.annotation.Nullable
  @JsonProperty(value = JSON_PROPERTY_PATTERN, required = false)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public String getPattern() {
    return pattern;
  }


  @JsonProperty(value = JSON_PROPERTY_PATTERN, required = false)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setPattern(@jakarta.annotation.Nullable String pattern) {
    this.pattern = pattern;
  }


  public CiBranchPatternsPatternsInner isPrefix(@jakarta.annotation.Nullable Boolean isPrefix) {
    this.isPrefix = isPrefix;
    return this;
  }

  /**
   * Get isPrefix
   * @return isPrefix
   */
  @jakarta.annotation.Nullable
  @JsonProperty(value = JSON_PROPERTY_IS_PREFIX, required = false)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public Boolean getIsPrefix() {
    return isPrefix;
  }


  @JsonProperty(value = JSON_PROPERTY_IS_PREFIX, required = false)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setIsPrefix(@jakarta.annotation.Nullable Boolean isPrefix) {
    this.isPrefix = isPrefix;
  }


  /**
   * Return true if this CiBranchPatterns_patterns_inner object is equal to o.
   */
  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    CiBranchPatternsPatternsInner ciBranchPatternsPatternsInner = (CiBranchPatternsPatternsInner) o;
    return Objects.equals(this.pattern, ciBranchPatternsPatternsInner.pattern) &&
        Objects.equals(this.isPrefix, ciBranchPatternsPatternsInner.isPrefix);
  }

  @Override
  public int hashCode() {
    return Objects.hash(pattern, isPrefix);
  }

  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class CiBranchPatternsPatternsInner {\n");
    sb.append("    pattern: ").append(toIndentedString(pattern)).append("\n");
    sb.append("    isPrefix: ").append(toIndentedString(isPrefix)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

  /**
   * Convert the instance into URL query string.
   *
   * @return URL query string
   */
  public String toUrlQueryString() {
    return toUrlQueryString(null);
  }

  /**
   * Convert the instance into URL query string.
   *
   * @param prefix prefix of the query string
   * @return URL query string
   */
  public String toUrlQueryString(String prefix) {
    String suffix = "";
    String containerSuffix = "";
    String containerPrefix = "";
    if (prefix == null) {
      // style=form, explode=true, e.g. /pet?name=cat&type=manx
      prefix = "";
    } else {
      // deepObject style e.g. /pet?id[name]=cat&id[type]=manx
      prefix = prefix + "[";
      suffix = "]";
      containerSuffix = "]";
      containerPrefix = "[";
    }

    StringJoiner joiner = new StringJoiner("&");

    // add `pattern` to the URL query string
    if (getPattern() != null) {
      joiner.add(String.format(Locale.ROOT, "%spattern%s=%s", prefix, suffix, ApiClient.urlEncode(ApiClient.valueToString(getPattern()))));
    }

    // add `isPrefix` to the URL query string
    if (getIsPrefix() != null) {
      joiner.add(String.format(Locale.ROOT, "%sisPrefix%s=%s", prefix, suffix, ApiClient.urlEncode(ApiClient.valueToString(getIsPrefix()))));
    }

    return joiner.toString();
  }
}

