/*
 * App Store Connect API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 4.2
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package com.adguard.stores.appstoreconnect.model;

import java.net.URLEncoder;
import java.nio.charset.StandardCharsets;
import java.util.StringJoiner;
import java.util.Objects;
import java.util.Map;
import java.util.HashMap;
import java.util.Locale;
import com.adguard.stores.appstoreconnect.model.CiAction;
import com.adguard.stores.appstoreconnect.model.CiBranchStartCondition;
import com.adguard.stores.appstoreconnect.model.CiManualBranchStartCondition;
import com.adguard.stores.appstoreconnect.model.CiManualPullRequestStartCondition;
import com.adguard.stores.appstoreconnect.model.CiManualTagStartCondition;
import com.adguard.stores.appstoreconnect.model.CiPullRequestStartCondition;
import com.adguard.stores.appstoreconnect.model.CiScheduledStartCondition;
import com.adguard.stores.appstoreconnect.model.CiTagStartCondition;
import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonTypeName;
import com.fasterxml.jackson.annotation.JsonValue;
import java.util.ArrayList;
import java.util.Arrays;
import java.util.List;
import org.openapitools.jackson.nullable.JsonNullable;
import com.fasterxml.jackson.annotation.JsonIgnore;
import org.openapitools.jackson.nullable.JsonNullable;
import java.util.NoSuchElementException;
import com.fasterxml.jackson.annotation.JsonPropertyOrder;


import com.adguard.stores.appstoreconnect.ApiClient;
/**
 * CiWorkflowCreateRequestDataAttributes
 */
@JsonPropertyOrder({
  CiWorkflowCreateRequestDataAttributes.JSON_PROPERTY_NAME,
  CiWorkflowCreateRequestDataAttributes.JSON_PROPERTY_DESCRIPTION,
  CiWorkflowCreateRequestDataAttributes.JSON_PROPERTY_BRANCH_START_CONDITION,
  CiWorkflowCreateRequestDataAttributes.JSON_PROPERTY_TAG_START_CONDITION,
  CiWorkflowCreateRequestDataAttributes.JSON_PROPERTY_PULL_REQUEST_START_CONDITION,
  CiWorkflowCreateRequestDataAttributes.JSON_PROPERTY_SCHEDULED_START_CONDITION,
  CiWorkflowCreateRequestDataAttributes.JSON_PROPERTY_MANUAL_BRANCH_START_CONDITION,
  CiWorkflowCreateRequestDataAttributes.JSON_PROPERTY_MANUAL_TAG_START_CONDITION,
  CiWorkflowCreateRequestDataAttributes.JSON_PROPERTY_MANUAL_PULL_REQUEST_START_CONDITION,
  CiWorkflowCreateRequestDataAttributes.JSON_PROPERTY_ACTIONS,
  CiWorkflowCreateRequestDataAttributes.JSON_PROPERTY_IS_ENABLED,
  CiWorkflowCreateRequestDataAttributes.JSON_PROPERTY_IS_LOCKED_FOR_EDITING,
  CiWorkflowCreateRequestDataAttributes.JSON_PROPERTY_CLEAN,
  CiWorkflowCreateRequestDataAttributes.JSON_PROPERTY_CONTAINER_FILE_PATH
})
@jakarta.annotation.Generated(value = "org.openapitools.codegen.languages.JavaClientCodegen", comments = "Generator version: 7.17.0")
public class CiWorkflowCreateRequestDataAttributes {
  public static final String JSON_PROPERTY_NAME = "name";
  @jakarta.annotation.Nonnull
  private String name;

  public static final String JSON_PROPERTY_DESCRIPTION = "description";
  @jakarta.annotation.Nonnull
  private String description;

  public static final String JSON_PROPERTY_BRANCH_START_CONDITION = "branchStartCondition";
  @jakarta.annotation.Nullable
  private CiBranchStartCondition branchStartCondition;

  public static final String JSON_PROPERTY_TAG_START_CONDITION = "tagStartCondition";
  @jakarta.annotation.Nullable
  private CiTagStartCondition tagStartCondition;

  public static final String JSON_PROPERTY_PULL_REQUEST_START_CONDITION = "pullRequestStartCondition";
  @jakarta.annotation.Nullable
  private CiPullRequestStartCondition pullRequestStartCondition;

  public static final String JSON_PROPERTY_SCHEDULED_START_CONDITION = "scheduledStartCondition";
  @jakarta.annotation.Nullable
  private CiScheduledStartCondition scheduledStartCondition;

  public static final String JSON_PROPERTY_MANUAL_BRANCH_START_CONDITION = "manualBranchStartCondition";
  @jakarta.annotation.Nullable
  private CiManualBranchStartCondition manualBranchStartCondition;

  public static final String JSON_PROPERTY_MANUAL_TAG_START_CONDITION = "manualTagStartCondition";
  @jakarta.annotation.Nullable
  private CiManualTagStartCondition manualTagStartCondition;

  public static final String JSON_PROPERTY_MANUAL_PULL_REQUEST_START_CONDITION = "manualPullRequestStartCondition";
  @jakarta.annotation.Nullable
  private CiManualPullRequestStartCondition manualPullRequestStartCondition;

  public static final String JSON_PROPERTY_ACTIONS = "actions";
  @jakarta.annotation.Nonnull
  private List<CiAction> actions = new ArrayList<>();

  public static final String JSON_PROPERTY_IS_ENABLED = "isEnabled";
  @jakarta.annotation.Nonnull
  private Boolean isEnabled;

  public static final String JSON_PROPERTY_IS_LOCKED_FOR_EDITING = "isLockedForEditing";
  private JsonNullable<Boolean> isLockedForEditing = JsonNullable.<Boolean>undefined();

  public static final String JSON_PROPERTY_CLEAN = "clean";
  @jakarta.annotation.Nonnull
  private Boolean clean;

  public static final String JSON_PROPERTY_CONTAINER_FILE_PATH = "containerFilePath";
  @jakarta.annotation.Nonnull
  private String containerFilePath;

  public CiWorkflowCreateRequestDataAttributes() { 
  }

  public CiWorkflowCreateRequestDataAttributes name(@jakarta.annotation.Nonnull String name) {
    this.name = name;
    return this;
  }

  /**
   * Get name
   * @return name
   */
  @jakarta.annotation.Nonnull
  @JsonProperty(value = JSON_PROPERTY_NAME, required = true)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)
  public String getName() {
    return name;
  }


  @JsonProperty(value = JSON_PROPERTY_NAME, required = true)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)
  public void setName(@jakarta.annotation.Nonnull String name) {
    this.name = name;
  }


  public CiWorkflowCreateRequestDataAttributes description(@jakarta.annotation.Nonnull String description) {
    this.description = description;
    return this;
  }

  /**
   * Get description
   * @return description
   */
  @jakarta.annotation.Nonnull
  @JsonProperty(value = JSON_PROPERTY_DESCRIPTION, required = true)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)
  public String getDescription() {
    return description;
  }


  @JsonProperty(value = JSON_PROPERTY_DESCRIPTION, required = true)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)
  public void setDescription(@jakarta.annotation.Nonnull String description) {
    this.description = description;
  }


  public CiWorkflowCreateRequestDataAttributes branchStartCondition(@jakarta.annotation.Nullable CiBranchStartCondition branchStartCondition) {
    this.branchStartCondition = branchStartCondition;
    return this;
  }

  /**
   * Get branchStartCondition
   * @return branchStartCondition
   */
  @jakarta.annotation.Nullable
  @JsonProperty(value = JSON_PROPERTY_BRANCH_START_CONDITION, required = false)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public CiBranchStartCondition getBranchStartCondition() {
    return branchStartCondition;
  }


  @JsonProperty(value = JSON_PROPERTY_BRANCH_START_CONDITION, required = false)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setBranchStartCondition(@jakarta.annotation.Nullable CiBranchStartCondition branchStartCondition) {
    this.branchStartCondition = branchStartCondition;
  }


  public CiWorkflowCreateRequestDataAttributes tagStartCondition(@jakarta.annotation.Nullable CiTagStartCondition tagStartCondition) {
    this.tagStartCondition = tagStartCondition;
    return this;
  }

  /**
   * Get tagStartCondition
   * @return tagStartCondition
   */
  @jakarta.annotation.Nullable
  @JsonProperty(value = JSON_PROPERTY_TAG_START_CONDITION, required = false)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public CiTagStartCondition getTagStartCondition() {
    return tagStartCondition;
  }


  @JsonProperty(value = JSON_PROPERTY_TAG_START_CONDITION, required = false)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setTagStartCondition(@jakarta.annotation.Nullable CiTagStartCondition tagStartCondition) {
    this.tagStartCondition = tagStartCondition;
  }


  public CiWorkflowCreateRequestDataAttributes pullRequestStartCondition(@jakarta.annotation.Nullable CiPullRequestStartCondition pullRequestStartCondition) {
    this.pullRequestStartCondition = pullRequestStartCondition;
    return this;
  }

  /**
   * Get pullRequestStartCondition
   * @return pullRequestStartCondition
   */
  @jakarta.annotation.Nullable
  @JsonProperty(value = JSON_PROPERTY_PULL_REQUEST_START_CONDITION, required = false)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public CiPullRequestStartCondition getPullRequestStartCondition() {
    return pullRequestStartCondition;
  }


  @JsonProperty(value = JSON_PROPERTY_PULL_REQUEST_START_CONDITION, required = false)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setPullRequestStartCondition(@jakarta.annotation.Nullable CiPullRequestStartCondition pullRequestStartCondition) {
    this.pullRequestStartCondition = pullRequestStartCondition;
  }


  public CiWorkflowCreateRequestDataAttributes scheduledStartCondition(@jakarta.annotation.Nullable CiScheduledStartCondition scheduledStartCondition) {
    this.scheduledStartCondition = scheduledStartCondition;
    return this;
  }

  /**
   * Get scheduledStartCondition
   * @return scheduledStartCondition
   */
  @jakarta.annotation.Nullable
  @JsonProperty(value = JSON_PROPERTY_SCHEDULED_START_CONDITION, required = false)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public CiScheduledStartCondition getScheduledStartCondition() {
    return scheduledStartCondition;
  }


  @JsonProperty(value = JSON_PROPERTY_SCHEDULED_START_CONDITION, required = false)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setScheduledStartCondition(@jakarta.annotation.Nullable CiScheduledStartCondition scheduledStartCondition) {
    this.scheduledStartCondition = scheduledStartCondition;
  }


  public CiWorkflowCreateRequestDataAttributes manualBranchStartCondition(@jakarta.annotation.Nullable CiManualBranchStartCondition manualBranchStartCondition) {
    this.manualBranchStartCondition = manualBranchStartCondition;
    return this;
  }

  /**
   * Get manualBranchStartCondition
   * @return manualBranchStartCondition
   */
  @jakarta.annotation.Nullable
  @JsonProperty(value = JSON_PROPERTY_MANUAL_BRANCH_START_CONDITION, required = false)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public CiManualBranchStartCondition getManualBranchStartCondition() {
    return manualBranchStartCondition;
  }


  @JsonProperty(value = JSON_PROPERTY_MANUAL_BRANCH_START_CONDITION, required = false)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setManualBranchStartCondition(@jakarta.annotation.Nullable CiManualBranchStartCondition manualBranchStartCondition) {
    this.manualBranchStartCondition = manualBranchStartCondition;
  }


  public CiWorkflowCreateRequestDataAttributes manualTagStartCondition(@jakarta.annotation.Nullable CiManualTagStartCondition manualTagStartCondition) {
    this.manualTagStartCondition = manualTagStartCondition;
    return this;
  }

  /**
   * Get manualTagStartCondition
   * @return manualTagStartCondition
   */
  @jakarta.annotation.Nullable
  @JsonProperty(value = JSON_PROPERTY_MANUAL_TAG_START_CONDITION, required = false)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public CiManualTagStartCondition getManualTagStartCondition() {
    return manualTagStartCondition;
  }


  @JsonProperty(value = JSON_PROPERTY_MANUAL_TAG_START_CONDITION, required = false)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setManualTagStartCondition(@jakarta.annotation.Nullable CiManualTagStartCondition manualTagStartCondition) {
    this.manualTagStartCondition = manualTagStartCondition;
  }


  public CiWorkflowCreateRequestDataAttributes manualPullRequestStartCondition(@jakarta.annotation.Nullable CiManualPullRequestStartCondition manualPullRequestStartCondition) {
    this.manualPullRequestStartCondition = manualPullRequestStartCondition;
    return this;
  }

  /**
   * Get manualPullRequestStartCondition
   * @return manualPullRequestStartCondition
   */
  @jakarta.annotation.Nullable
  @JsonProperty(value = JSON_PROPERTY_MANUAL_PULL_REQUEST_START_CONDITION, required = false)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public CiManualPullRequestStartCondition getManualPullRequestStartCondition() {
    return manualPullRequestStartCondition;
  }


  @JsonProperty(value = JSON_PROPERTY_MANUAL_PULL_REQUEST_START_CONDITION, required = false)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setManualPullRequestStartCondition(@jakarta.annotation.Nullable CiManualPullRequestStartCondition manualPullRequestStartCondition) {
    this.manualPullRequestStartCondition = manualPullRequestStartCondition;
  }


  public CiWorkflowCreateRequestDataAttributes actions(@jakarta.annotation.Nonnull List<CiAction> actions) {
    this.actions = actions;
    return this;
  }

  public CiWorkflowCreateRequestDataAttributes addActionsItem(CiAction actionsItem) {
    if (this.actions == null) {
      this.actions = new ArrayList<>();
    }
    this.actions.add(actionsItem);
    return this;
  }

  /**
   * Get actions
   * @return actions
   */
  @jakarta.annotation.Nonnull
  @JsonProperty(value = JSON_PROPERTY_ACTIONS, required = true)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)
  public List<CiAction> getActions() {
    return actions;
  }


  @JsonProperty(value = JSON_PROPERTY_ACTIONS, required = true)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)
  public void setActions(@jakarta.annotation.Nonnull List<CiAction> actions) {
    this.actions = actions;
  }


  public CiWorkflowCreateRequestDataAttributes isEnabled(@jakarta.annotation.Nonnull Boolean isEnabled) {
    this.isEnabled = isEnabled;
    return this;
  }

  /**
   * Get isEnabled
   * @return isEnabled
   */
  @jakarta.annotation.Nonnull
  @JsonProperty(value = JSON_PROPERTY_IS_ENABLED, required = true)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)
  public Boolean getIsEnabled() {
    return isEnabled;
  }


  @JsonProperty(value = JSON_PROPERTY_IS_ENABLED, required = true)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)
  public void setIsEnabled(@jakarta.annotation.Nonnull Boolean isEnabled) {
    this.isEnabled = isEnabled;
  }


  public CiWorkflowCreateRequestDataAttributes isLockedForEditing(@jakarta.annotation.Nullable Boolean isLockedForEditing) {
    this.isLockedForEditing = JsonNullable.<Boolean>of(isLockedForEditing);
    return this;
  }

  /**
   * Get isLockedForEditing
   * @return isLockedForEditing
   */
  @jakarta.annotation.Nullable
  @JsonIgnore
  public Boolean getIsLockedForEditing() {
        return isLockedForEditing.orElse(null);
  }

  @JsonProperty(value = JSON_PROPERTY_IS_LOCKED_FOR_EDITING, required = false)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public JsonNullable<Boolean> getIsLockedForEditing_JsonNullable() {
    return isLockedForEditing;
  }
  
  @JsonProperty(JSON_PROPERTY_IS_LOCKED_FOR_EDITING)
  public void setIsLockedForEditing_JsonNullable(JsonNullable<Boolean> isLockedForEditing) {
    this.isLockedForEditing = isLockedForEditing;
  }

  public void setIsLockedForEditing(@jakarta.annotation.Nullable Boolean isLockedForEditing) {
    this.isLockedForEditing = JsonNullable.<Boolean>of(isLockedForEditing);
  }


  public CiWorkflowCreateRequestDataAttributes clean(@jakarta.annotation.Nonnull Boolean clean) {
    this.clean = clean;
    return this;
  }

  /**
   * Get clean
   * @return clean
   */
  @jakarta.annotation.Nonnull
  @JsonProperty(value = JSON_PROPERTY_CLEAN, required = true)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)
  public Boolean getClean() {
    return clean;
  }


  @JsonProperty(value = JSON_PROPERTY_CLEAN, required = true)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)
  public void setClean(@jakarta.annotation.Nonnull Boolean clean) {
    this.clean = clean;
  }


  public CiWorkflowCreateRequestDataAttributes containerFilePath(@jakarta.annotation.Nonnull String containerFilePath) {
    this.containerFilePath = containerFilePath;
    return this;
  }

  /**
   * Get containerFilePath
   * @return containerFilePath
   */
  @jakarta.annotation.Nonnull
  @JsonProperty(value = JSON_PROPERTY_CONTAINER_FILE_PATH, required = true)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)
  public String getContainerFilePath() {
    return containerFilePath;
  }


  @JsonProperty(value = JSON_PROPERTY_CONTAINER_FILE_PATH, required = true)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)
  public void setContainerFilePath(@jakarta.annotation.Nonnull String containerFilePath) {
    this.containerFilePath = containerFilePath;
  }


  /**
   * Return true if this CiWorkflowCreateRequest_data_attributes object is equal to o.
   */
  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    CiWorkflowCreateRequestDataAttributes ciWorkflowCreateRequestDataAttributes = (CiWorkflowCreateRequestDataAttributes) o;
    return Objects.equals(this.name, ciWorkflowCreateRequestDataAttributes.name) &&
        Objects.equals(this.description, ciWorkflowCreateRequestDataAttributes.description) &&
        Objects.equals(this.branchStartCondition, ciWorkflowCreateRequestDataAttributes.branchStartCondition) &&
        Objects.equals(this.tagStartCondition, ciWorkflowCreateRequestDataAttributes.tagStartCondition) &&
        Objects.equals(this.pullRequestStartCondition, ciWorkflowCreateRequestDataAttributes.pullRequestStartCondition) &&
        Objects.equals(this.scheduledStartCondition, ciWorkflowCreateRequestDataAttributes.scheduledStartCondition) &&
        Objects.equals(this.manualBranchStartCondition, ciWorkflowCreateRequestDataAttributes.manualBranchStartCondition) &&
        Objects.equals(this.manualTagStartCondition, ciWorkflowCreateRequestDataAttributes.manualTagStartCondition) &&
        Objects.equals(this.manualPullRequestStartCondition, ciWorkflowCreateRequestDataAttributes.manualPullRequestStartCondition) &&
        Objects.equals(this.actions, ciWorkflowCreateRequestDataAttributes.actions) &&
        Objects.equals(this.isEnabled, ciWorkflowCreateRequestDataAttributes.isEnabled) &&
        equalsNullable(this.isLockedForEditing, ciWorkflowCreateRequestDataAttributes.isLockedForEditing) &&
        Objects.equals(this.clean, ciWorkflowCreateRequestDataAttributes.clean) &&
        Objects.equals(this.containerFilePath, ciWorkflowCreateRequestDataAttributes.containerFilePath);
  }

  private static <T> boolean equalsNullable(JsonNullable<T> a, JsonNullable<T> b) {
    return a == b || (a != null && b != null && a.isPresent() && b.isPresent() && Objects.deepEquals(a.get(), b.get()));
  }

  @Override
  public int hashCode() {
    return Objects.hash(name, description, branchStartCondition, tagStartCondition, pullRequestStartCondition, scheduledStartCondition, manualBranchStartCondition, manualTagStartCondition, manualPullRequestStartCondition, actions, isEnabled, hashCodeNullable(isLockedForEditing), clean, containerFilePath);
  }

  private static <T> int hashCodeNullable(JsonNullable<T> a) {
    if (a == null) {
      return 1;
    }
    return a.isPresent() ? Arrays.deepHashCode(new Object[]{a.get()}) : 31;
  }

  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class CiWorkflowCreateRequestDataAttributes {\n");
    sb.append("    name: ").append(toIndentedString(name)).append("\n");
    sb.append("    description: ").append(toIndentedString(description)).append("\n");
    sb.append("    branchStartCondition: ").append(toIndentedString(branchStartCondition)).append("\n");
    sb.append("    tagStartCondition: ").append(toIndentedString(tagStartCondition)).append("\n");
    sb.append("    pullRequestStartCondition: ").append(toIndentedString(pullRequestStartCondition)).append("\n");
    sb.append("    scheduledStartCondition: ").append(toIndentedString(scheduledStartCondition)).append("\n");
    sb.append("    manualBranchStartCondition: ").append(toIndentedString(manualBranchStartCondition)).append("\n");
    sb.append("    manualTagStartCondition: ").append(toIndentedString(manualTagStartCondition)).append("\n");
    sb.append("    manualPullRequestStartCondition: ").append(toIndentedString(manualPullRequestStartCondition)).append("\n");
    sb.append("    actions: ").append(toIndentedString(actions)).append("\n");
    sb.append("    isEnabled: ").append(toIndentedString(isEnabled)).append("\n");
    sb.append("    isLockedForEditing: ").append(toIndentedString(isLockedForEditing)).append("\n");
    sb.append("    clean: ").append(toIndentedString(clean)).append("\n");
    sb.append("    containerFilePath: ").append(toIndentedString(containerFilePath)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

  /**
   * Convert the instance into URL query string.
   *
   * @return URL query string
   */
  public String toUrlQueryString() {
    return toUrlQueryString(null);
  }

  /**
   * Convert the instance into URL query string.
   *
   * @param prefix prefix of the query string
   * @return URL query string
   */
  public String toUrlQueryString(String prefix) {
    String suffix = "";
    String containerSuffix = "";
    String containerPrefix = "";
    if (prefix == null) {
      // style=form, explode=true, e.g. /pet?name=cat&type=manx
      prefix = "";
    } else {
      // deepObject style e.g. /pet?id[name]=cat&id[type]=manx
      prefix = prefix + "[";
      suffix = "]";
      containerSuffix = "]";
      containerPrefix = "[";
    }

    StringJoiner joiner = new StringJoiner("&");

    // add `name` to the URL query string
    if (getName() != null) {
      joiner.add(String.format(Locale.ROOT, "%sname%s=%s", prefix, suffix, ApiClient.urlEncode(ApiClient.valueToString(getName()))));
    }

    // add `description` to the URL query string
    if (getDescription() != null) {
      joiner.add(String.format(Locale.ROOT, "%sdescription%s=%s", prefix, suffix, ApiClient.urlEncode(ApiClient.valueToString(getDescription()))));
    }

    // add `branchStartCondition` to the URL query string
    if (getBranchStartCondition() != null) {
      joiner.add(getBranchStartCondition().toUrlQueryString(prefix + "branchStartCondition" + suffix));
    }

    // add `tagStartCondition` to the URL query string
    if (getTagStartCondition() != null) {
      joiner.add(getTagStartCondition().toUrlQueryString(prefix + "tagStartCondition" + suffix));
    }

    // add `pullRequestStartCondition` to the URL query string
    if (getPullRequestStartCondition() != null) {
      joiner.add(getPullRequestStartCondition().toUrlQueryString(prefix + "pullRequestStartCondition" + suffix));
    }

    // add `scheduledStartCondition` to the URL query string
    if (getScheduledStartCondition() != null) {
      joiner.add(getScheduledStartCondition().toUrlQueryString(prefix + "scheduledStartCondition" + suffix));
    }

    // add `manualBranchStartCondition` to the URL query string
    if (getManualBranchStartCondition() != null) {
      joiner.add(getManualBranchStartCondition().toUrlQueryString(prefix + "manualBranchStartCondition" + suffix));
    }

    // add `manualTagStartCondition` to the URL query string
    if (getManualTagStartCondition() != null) {
      joiner.add(getManualTagStartCondition().toUrlQueryString(prefix + "manualTagStartCondition" + suffix));
    }

    // add `manualPullRequestStartCondition` to the URL query string
    if (getManualPullRequestStartCondition() != null) {
      joiner.add(getManualPullRequestStartCondition().toUrlQueryString(prefix + "manualPullRequestStartCondition" + suffix));
    }

    // add `actions` to the URL query string
    if (getActions() != null) {
      for (int i = 0; i < getActions().size(); i++) {
        if (getActions().get(i) != null) {
          joiner.add(getActions().get(i).toUrlQueryString(String.format(Locale.ROOT, "%sactions%s%s", prefix, suffix,
          "".equals(suffix) ? "" : String.format(Locale.ROOT, "%s%d%s", containerPrefix, i, containerSuffix))));
        }
      }
    }

    // add `isEnabled` to the URL query string
    if (getIsEnabled() != null) {
      joiner.add(String.format(Locale.ROOT, "%sisEnabled%s=%s", prefix, suffix, ApiClient.urlEncode(ApiClient.valueToString(getIsEnabled()))));
    }

    // add `isLockedForEditing` to the URL query string
    if (getIsLockedForEditing() != null) {
      joiner.add(String.format(Locale.ROOT, "%sisLockedForEditing%s=%s", prefix, suffix, ApiClient.urlEncode(ApiClient.valueToString(getIsLockedForEditing()))));
    }

    // add `clean` to the URL query string
    if (getClean() != null) {
      joiner.add(String.format(Locale.ROOT, "%sclean%s=%s", prefix, suffix, ApiClient.urlEncode(ApiClient.valueToString(getClean()))));
    }

    // add `containerFilePath` to the URL query string
    if (getContainerFilePath() != null) {
      joiner.add(String.format(Locale.ROOT, "%scontainerFilePath%s=%s", prefix, suffix, ApiClient.urlEncode(ApiClient.valueToString(getContainerFilePath()))));
    }

    return joiner.toString();
  }
}

