/*
 * App Store Connect API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 4.2
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package com.adguard.stores.appstoreconnect.model;

import java.net.URLEncoder;
import java.nio.charset.StandardCharsets;
import java.util.StringJoiner;
import java.util.Objects;
import java.util.Map;
import java.util.HashMap;
import java.util.Locale;
import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonTypeName;
import com.fasterxml.jackson.annotation.JsonValue;
import java.util.Arrays;
import com.fasterxml.jackson.annotation.JsonPropertyOrder;


import com.adguard.stores.appstoreconnect.ApiClient;
/**
 * CiXcodeVersionAttributesTestDestinationsInnerAvailableRuntimesInner
 */
@JsonPropertyOrder({
  CiXcodeVersionAttributesTestDestinationsInnerAvailableRuntimesInner.JSON_PROPERTY_RUNTIME_NAME,
  CiXcodeVersionAttributesTestDestinationsInnerAvailableRuntimesInner.JSON_PROPERTY_RUNTIME_IDENTIFIER
})
@jakarta.annotation.Generated(value = "org.openapitools.codegen.languages.JavaClientCodegen", comments = "Generator version: 7.17.0")
public class CiXcodeVersionAttributesTestDestinationsInnerAvailableRuntimesInner {
  public static final String JSON_PROPERTY_RUNTIME_NAME = "runtimeName";
  @jakarta.annotation.Nullable
  private String runtimeName;

  public static final String JSON_PROPERTY_RUNTIME_IDENTIFIER = "runtimeIdentifier";
  @jakarta.annotation.Nullable
  private String runtimeIdentifier;

  public CiXcodeVersionAttributesTestDestinationsInnerAvailableRuntimesInner() { 
  }

  public CiXcodeVersionAttributesTestDestinationsInnerAvailableRuntimesInner runtimeName(@jakarta.annotation.Nullable String runtimeName) {
    this.runtimeName = runtimeName;
    return this;
  }

  /**
   * Get runtimeName
   * @return runtimeName
   */
  @jakarta.annotation.Nullable
  @JsonProperty(value = JSON_PROPERTY_RUNTIME_NAME, required = false)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public String getRuntimeName() {
    return runtimeName;
  }


  @JsonProperty(value = JSON_PROPERTY_RUNTIME_NAME, required = false)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setRuntimeName(@jakarta.annotation.Nullable String runtimeName) {
    this.runtimeName = runtimeName;
  }


  public CiXcodeVersionAttributesTestDestinationsInnerAvailableRuntimesInner runtimeIdentifier(@jakarta.annotation.Nullable String runtimeIdentifier) {
    this.runtimeIdentifier = runtimeIdentifier;
    return this;
  }

  /**
   * Get runtimeIdentifier
   * @return runtimeIdentifier
   */
  @jakarta.annotation.Nullable
  @JsonProperty(value = JSON_PROPERTY_RUNTIME_IDENTIFIER, required = false)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public String getRuntimeIdentifier() {
    return runtimeIdentifier;
  }


  @JsonProperty(value = JSON_PROPERTY_RUNTIME_IDENTIFIER, required = false)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setRuntimeIdentifier(@jakarta.annotation.Nullable String runtimeIdentifier) {
    this.runtimeIdentifier = runtimeIdentifier;
  }


  /**
   * Return true if this CiXcodeVersion_attributes_testDestinations_inner_availableRuntimes_inner object is equal to o.
   */
  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    CiXcodeVersionAttributesTestDestinationsInnerAvailableRuntimesInner ciXcodeVersionAttributesTestDestinationsInnerAvailableRuntimesInner = (CiXcodeVersionAttributesTestDestinationsInnerAvailableRuntimesInner) o;
    return Objects.equals(this.runtimeName, ciXcodeVersionAttributesTestDestinationsInnerAvailableRuntimesInner.runtimeName) &&
        Objects.equals(this.runtimeIdentifier, ciXcodeVersionAttributesTestDestinationsInnerAvailableRuntimesInner.runtimeIdentifier);
  }

  @Override
  public int hashCode() {
    return Objects.hash(runtimeName, runtimeIdentifier);
  }

  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class CiXcodeVersionAttributesTestDestinationsInnerAvailableRuntimesInner {\n");
    sb.append("    runtimeName: ").append(toIndentedString(runtimeName)).append("\n");
    sb.append("    runtimeIdentifier: ").append(toIndentedString(runtimeIdentifier)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

  /**
   * Convert the instance into URL query string.
   *
   * @return URL query string
   */
  public String toUrlQueryString() {
    return toUrlQueryString(null);
  }

  /**
   * Convert the instance into URL query string.
   *
   * @param prefix prefix of the query string
   * @return URL query string
   */
  public String toUrlQueryString(String prefix) {
    String suffix = "";
    String containerSuffix = "";
    String containerPrefix = "";
    if (prefix == null) {
      // style=form, explode=true, e.g. /pet?name=cat&type=manx
      prefix = "";
    } else {
      // deepObject style e.g. /pet?id[name]=cat&id[type]=manx
      prefix = prefix + "[";
      suffix = "]";
      containerSuffix = "]";
      containerPrefix = "[";
    }

    StringJoiner joiner = new StringJoiner("&");

    // add `runtimeName` to the URL query string
    if (getRuntimeName() != null) {
      joiner.add(String.format(Locale.ROOT, "%sruntimeName%s=%s", prefix, suffix, ApiClient.urlEncode(ApiClient.valueToString(getRuntimeName()))));
    }

    // add `runtimeIdentifier` to the URL query string
    if (getRuntimeIdentifier() != null) {
      joiner.add(String.format(Locale.ROOT, "%sruntimeIdentifier%s=%s", prefix, suffix, ApiClient.urlEncode(ApiClient.valueToString(getRuntimeIdentifier()))));
    }

    return joiner.toString();
  }
}

