/*
 * App Store Connect API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 4.2
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package com.adguard.stores.appstoreconnect.model;

import java.net.URLEncoder;
import java.nio.charset.StandardCharsets;
import java.util.StringJoiner;
import java.util.Objects;
import java.util.Map;
import java.util.HashMap;
import java.util.Locale;
import com.adguard.stores.appstoreconnect.model.DiagnosticLogsProductDataInnerDiagnosticLogsInnerCallStackTreeInnerCallStacksInner;
import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonTypeName;
import com.fasterxml.jackson.annotation.JsonValue;
import java.util.ArrayList;
import java.util.Arrays;
import java.util.List;
import com.fasterxml.jackson.annotation.JsonPropertyOrder;


import com.adguard.stores.appstoreconnect.ApiClient;
/**
 * DiagnosticLogsProductDataInnerDiagnosticLogsInnerCallStackTreeInner
 */
@JsonPropertyOrder({
  DiagnosticLogsProductDataInnerDiagnosticLogsInnerCallStackTreeInner.JSON_PROPERTY_CALL_STACK_PER_THREAD,
  DiagnosticLogsProductDataInnerDiagnosticLogsInnerCallStackTreeInner.JSON_PROPERTY_CALL_STACKS
})
@jakarta.annotation.Generated(value = "org.openapitools.codegen.languages.JavaClientCodegen", comments = "Generator version: 7.17.0")
public class DiagnosticLogsProductDataInnerDiagnosticLogsInnerCallStackTreeInner {
  public static final String JSON_PROPERTY_CALL_STACK_PER_THREAD = "callStackPerThread";
  @jakarta.annotation.Nullable
  private Boolean callStackPerThread;

  public static final String JSON_PROPERTY_CALL_STACKS = "callStacks";
  @jakarta.annotation.Nullable
  private List<DiagnosticLogsProductDataInnerDiagnosticLogsInnerCallStackTreeInnerCallStacksInner> callStacks = new ArrayList<>();

  public DiagnosticLogsProductDataInnerDiagnosticLogsInnerCallStackTreeInner() { 
  }

  public DiagnosticLogsProductDataInnerDiagnosticLogsInnerCallStackTreeInner callStackPerThread(@jakarta.annotation.Nullable Boolean callStackPerThread) {
    this.callStackPerThread = callStackPerThread;
    return this;
  }

  /**
   * Get callStackPerThread
   * @return callStackPerThread
   */
  @jakarta.annotation.Nullable
  @JsonProperty(value = JSON_PROPERTY_CALL_STACK_PER_THREAD, required = false)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public Boolean getCallStackPerThread() {
    return callStackPerThread;
  }


  @JsonProperty(value = JSON_PROPERTY_CALL_STACK_PER_THREAD, required = false)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setCallStackPerThread(@jakarta.annotation.Nullable Boolean callStackPerThread) {
    this.callStackPerThread = callStackPerThread;
  }


  public DiagnosticLogsProductDataInnerDiagnosticLogsInnerCallStackTreeInner callStacks(@jakarta.annotation.Nullable List<DiagnosticLogsProductDataInnerDiagnosticLogsInnerCallStackTreeInnerCallStacksInner> callStacks) {
    this.callStacks = callStacks;
    return this;
  }

  public DiagnosticLogsProductDataInnerDiagnosticLogsInnerCallStackTreeInner addCallStacksItem(DiagnosticLogsProductDataInnerDiagnosticLogsInnerCallStackTreeInnerCallStacksInner callStacksItem) {
    if (this.callStacks == null) {
      this.callStacks = new ArrayList<>();
    }
    this.callStacks.add(callStacksItem);
    return this;
  }

  /**
   * Get callStacks
   * @return callStacks
   */
  @jakarta.annotation.Nullable
  @JsonProperty(value = JSON_PROPERTY_CALL_STACKS, required = false)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public List<DiagnosticLogsProductDataInnerDiagnosticLogsInnerCallStackTreeInnerCallStacksInner> getCallStacks() {
    return callStacks;
  }


  @JsonProperty(value = JSON_PROPERTY_CALL_STACKS, required = false)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setCallStacks(@jakarta.annotation.Nullable List<DiagnosticLogsProductDataInnerDiagnosticLogsInnerCallStackTreeInnerCallStacksInner> callStacks) {
    this.callStacks = callStacks;
  }


  /**
   * Return true if this diagnosticLogs_productData_inner_diagnosticLogs_inner_callStackTree_inner object is equal to o.
   */
  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    DiagnosticLogsProductDataInnerDiagnosticLogsInnerCallStackTreeInner diagnosticLogsProductDataInnerDiagnosticLogsInnerCallStackTreeInner = (DiagnosticLogsProductDataInnerDiagnosticLogsInnerCallStackTreeInner) o;
    return Objects.equals(this.callStackPerThread, diagnosticLogsProductDataInnerDiagnosticLogsInnerCallStackTreeInner.callStackPerThread) &&
        Objects.equals(this.callStacks, diagnosticLogsProductDataInnerDiagnosticLogsInnerCallStackTreeInner.callStacks);
  }

  @Override
  public int hashCode() {
    return Objects.hash(callStackPerThread, callStacks);
  }

  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class DiagnosticLogsProductDataInnerDiagnosticLogsInnerCallStackTreeInner {\n");
    sb.append("    callStackPerThread: ").append(toIndentedString(callStackPerThread)).append("\n");
    sb.append("    callStacks: ").append(toIndentedString(callStacks)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

  /**
   * Convert the instance into URL query string.
   *
   * @return URL query string
   */
  public String toUrlQueryString() {
    return toUrlQueryString(null);
  }

  /**
   * Convert the instance into URL query string.
   *
   * @param prefix prefix of the query string
   * @return URL query string
   */
  public String toUrlQueryString(String prefix) {
    String suffix = "";
    String containerSuffix = "";
    String containerPrefix = "";
    if (prefix == null) {
      // style=form, explode=true, e.g. /pet?name=cat&type=manx
      prefix = "";
    } else {
      // deepObject style e.g. /pet?id[name]=cat&id[type]=manx
      prefix = prefix + "[";
      suffix = "]";
      containerSuffix = "]";
      containerPrefix = "[";
    }

    StringJoiner joiner = new StringJoiner("&");

    // add `callStackPerThread` to the URL query string
    if (getCallStackPerThread() != null) {
      joiner.add(String.format(Locale.ROOT, "%scallStackPerThread%s=%s", prefix, suffix, ApiClient.urlEncode(ApiClient.valueToString(getCallStackPerThread()))));
    }

    // add `callStacks` to the URL query string
    if (getCallStacks() != null) {
      for (int i = 0; i < getCallStacks().size(); i++) {
        if (getCallStacks().get(i) != null) {
          joiner.add(getCallStacks().get(i).toUrlQueryString(String.format(Locale.ROOT, "%scallStacks%s%s", prefix, suffix,
          "".equals(suffix) ? "" : String.format(Locale.ROOT, "%s%d%s", containerPrefix, i, containerSuffix))));
        }
      }
    }

    return joiner.toString();
  }
}

