/*
 * App Store Connect API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 4.2
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package com.adguard.stores.appstoreconnect.model;

import java.net.URLEncoder;
import java.nio.charset.StandardCharsets;
import java.util.StringJoiner;
import java.util.Objects;
import java.util.Map;
import java.util.HashMap;
import java.util.Locale;
import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonTypeName;
import com.fasterxml.jackson.annotation.JsonValue;
import java.util.Arrays;
import com.fasterxml.jackson.annotation.JsonPropertyOrder;


import com.adguard.stores.appstoreconnect.ApiClient;
/**
 * ErrorSourcePointer
 */
@JsonPropertyOrder({
  ErrorSourcePointer.JSON_PROPERTY_POINTER
})
@jakarta.annotation.Generated(value = "org.openapitools.codegen.languages.JavaClientCodegen", comments = "Generator version: 7.17.0")
public class ErrorSourcePointer {
  public static final String JSON_PROPERTY_POINTER = "pointer";
  @jakarta.annotation.Nonnull
  private String pointer;

  public ErrorSourcePointer() { 
  }

  public ErrorSourcePointer pointer(@jakarta.annotation.Nonnull String pointer) {
    this.pointer = pointer;
    return this;
  }

  /**
   * Get pointer
   * @return pointer
   */
  @jakarta.annotation.Nonnull
  @JsonProperty(value = JSON_PROPERTY_POINTER, required = true)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)
  public String getPointer() {
    return pointer;
  }


  @JsonProperty(value = JSON_PROPERTY_POINTER, required = true)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)
  public void setPointer(@jakarta.annotation.Nonnull String pointer) {
    this.pointer = pointer;
  }


  /**
   * Return true if this ErrorSourcePointer object is equal to o.
   */
  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    ErrorSourcePointer errorSourcePointer = (ErrorSourcePointer) o;
    return Objects.equals(this.pointer, errorSourcePointer.pointer);
  }

  @Override
  public int hashCode() {
    return Objects.hash(pointer);
  }

  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class ErrorSourcePointer {\n");
    sb.append("    pointer: ").append(toIndentedString(pointer)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

  /**
   * Convert the instance into URL query string.
   *
   * @return URL query string
   */
  public String toUrlQueryString() {
    return toUrlQueryString(null);
  }

  /**
   * Convert the instance into URL query string.
   *
   * @param prefix prefix of the query string
   * @return URL query string
   */
  public String toUrlQueryString(String prefix) {
    String suffix = "";
    String containerSuffix = "";
    String containerPrefix = "";
    if (prefix == null) {
      // style=form, explode=true, e.g. /pet?name=cat&type=manx
      prefix = "";
    } else {
      // deepObject style e.g. /pet?id[name]=cat&id[type]=manx
      prefix = prefix + "[";
      suffix = "]";
      containerSuffix = "]";
      containerPrefix = "[";
    }

    StringJoiner joiner = new StringJoiner("&");

    // add `pointer` to the URL query string
    if (getPointer() != null) {
      joiner.add(String.format(Locale.ROOT, "%spointer%s=%s", prefix, suffix, ApiClient.urlEncode(ApiClient.valueToString(getPointer()))));
    }

    return joiner.toString();
  }
}

