/*
 * App Store Connect API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 4.2
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package com.adguard.stores.appstoreconnect.model;

import java.net.URLEncoder;
import java.nio.charset.StandardCharsets;
import java.util.StringJoiner;
import java.util.Objects;
import java.util.Map;
import java.util.HashMap;
import java.util.Locale;
import com.adguard.stores.appstoreconnect.model.GameCenterMatchmakingNumberRuleResultsV1MetricResponseDataInnerDataPointsValues;
import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonTypeName;
import com.fasterxml.jackson.annotation.JsonValue;
import java.time.OffsetDateTime;
import java.util.Arrays;
import com.fasterxml.jackson.annotation.JsonPropertyOrder;


import com.adguard.stores.appstoreconnect.ApiClient;
/**
 * GameCenterMatchmakingNumberRuleResultsV1MetricResponseDataInnerDataPoints
 */
@JsonPropertyOrder({
  GameCenterMatchmakingNumberRuleResultsV1MetricResponseDataInnerDataPoints.JSON_PROPERTY_START,
  GameCenterMatchmakingNumberRuleResultsV1MetricResponseDataInnerDataPoints.JSON_PROPERTY_END,
  GameCenterMatchmakingNumberRuleResultsV1MetricResponseDataInnerDataPoints.JSON_PROPERTY_VALUES
})
@jakarta.annotation.Generated(value = "org.openapitools.codegen.languages.JavaClientCodegen", comments = "Generator version: 7.17.0")
public class GameCenterMatchmakingNumberRuleResultsV1MetricResponseDataInnerDataPoints {
  public static final String JSON_PROPERTY_START = "start";
  @jakarta.annotation.Nullable
  private OffsetDateTime start;

  public static final String JSON_PROPERTY_END = "end";
  @jakarta.annotation.Nullable
  private OffsetDateTime end;

  public static final String JSON_PROPERTY_VALUES = "values";
  @jakarta.annotation.Nullable
  private GameCenterMatchmakingNumberRuleResultsV1MetricResponseDataInnerDataPointsValues values;

  public GameCenterMatchmakingNumberRuleResultsV1MetricResponseDataInnerDataPoints() { 
  }

  public GameCenterMatchmakingNumberRuleResultsV1MetricResponseDataInnerDataPoints start(@jakarta.annotation.Nullable OffsetDateTime start) {
    this.start = start;
    return this;
  }

  /**
   * Get start
   * @return start
   */
  @jakarta.annotation.Nullable
  @JsonProperty(value = JSON_PROPERTY_START, required = false)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public OffsetDateTime getStart() {
    return start;
  }


  @JsonProperty(value = JSON_PROPERTY_START, required = false)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setStart(@jakarta.annotation.Nullable OffsetDateTime start) {
    this.start = start;
  }


  public GameCenterMatchmakingNumberRuleResultsV1MetricResponseDataInnerDataPoints end(@jakarta.annotation.Nullable OffsetDateTime end) {
    this.end = end;
    return this;
  }

  /**
   * Get end
   * @return end
   */
  @jakarta.annotation.Nullable
  @JsonProperty(value = JSON_PROPERTY_END, required = false)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public OffsetDateTime getEnd() {
    return end;
  }


  @JsonProperty(value = JSON_PROPERTY_END, required = false)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setEnd(@jakarta.annotation.Nullable OffsetDateTime end) {
    this.end = end;
  }


  public GameCenterMatchmakingNumberRuleResultsV1MetricResponseDataInnerDataPoints values(@jakarta.annotation.Nullable GameCenterMatchmakingNumberRuleResultsV1MetricResponseDataInnerDataPointsValues values) {
    this.values = values;
    return this;
  }

  /**
   * Get values
   * @return values
   */
  @jakarta.annotation.Nullable
  @JsonProperty(value = JSON_PROPERTY_VALUES, required = false)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public GameCenterMatchmakingNumberRuleResultsV1MetricResponseDataInnerDataPointsValues getValues() {
    return values;
  }


  @JsonProperty(value = JSON_PROPERTY_VALUES, required = false)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setValues(@jakarta.annotation.Nullable GameCenterMatchmakingNumberRuleResultsV1MetricResponseDataInnerDataPointsValues values) {
    this.values = values;
  }


  /**
   * Return true if this GameCenterMatchmakingNumberRuleResultsV1MetricResponse_data_inner_dataPoints object is equal to o.
   */
  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    GameCenterMatchmakingNumberRuleResultsV1MetricResponseDataInnerDataPoints gameCenterMatchmakingNumberRuleResultsV1MetricResponseDataInnerDataPoints = (GameCenterMatchmakingNumberRuleResultsV1MetricResponseDataInnerDataPoints) o;
    return Objects.equals(this.start, gameCenterMatchmakingNumberRuleResultsV1MetricResponseDataInnerDataPoints.start) &&
        Objects.equals(this.end, gameCenterMatchmakingNumberRuleResultsV1MetricResponseDataInnerDataPoints.end) &&
        Objects.equals(this.values, gameCenterMatchmakingNumberRuleResultsV1MetricResponseDataInnerDataPoints.values);
  }

  @Override
  public int hashCode() {
    return Objects.hash(start, end, values);
  }

  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class GameCenterMatchmakingNumberRuleResultsV1MetricResponseDataInnerDataPoints {\n");
    sb.append("    start: ").append(toIndentedString(start)).append("\n");
    sb.append("    end: ").append(toIndentedString(end)).append("\n");
    sb.append("    values: ").append(toIndentedString(values)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

  /**
   * Convert the instance into URL query string.
   *
   * @return URL query string
   */
  public String toUrlQueryString() {
    return toUrlQueryString(null);
  }

  /**
   * Convert the instance into URL query string.
   *
   * @param prefix prefix of the query string
   * @return URL query string
   */
  public String toUrlQueryString(String prefix) {
    String suffix = "";
    String containerSuffix = "";
    String containerPrefix = "";
    if (prefix == null) {
      // style=form, explode=true, e.g. /pet?name=cat&type=manx
      prefix = "";
    } else {
      // deepObject style e.g. /pet?id[name]=cat&id[type]=manx
      prefix = prefix + "[";
      suffix = "]";
      containerSuffix = "]";
      containerPrefix = "[";
    }

    StringJoiner joiner = new StringJoiner("&");

    // add `start` to the URL query string
    if (getStart() != null) {
      joiner.add(String.format(Locale.ROOT, "%sstart%s=%s", prefix, suffix, ApiClient.urlEncode(ApiClient.valueToString(getStart()))));
    }

    // add `end` to the URL query string
    if (getEnd() != null) {
      joiner.add(String.format(Locale.ROOT, "%send%s=%s", prefix, suffix, ApiClient.urlEncode(ApiClient.valueToString(getEnd()))));
    }

    // add `values` to the URL query string
    if (getValues() != null) {
      joiner.add(getValues().toUrlQueryString(prefix + "values" + suffix));
    }

    return joiner.toString();
  }
}

