/*
 * App Store Connect API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 4.2
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package com.adguard.stores.appstoreconnect.model;

import java.util.Map;
import java.util.HashMap;
import com.fasterxml.jackson.annotation.JsonAnyGetter;
import com.fasterxml.jackson.annotation.JsonAnySetter;
import java.net.URLEncoder;
import java.nio.charset.StandardCharsets;
import java.util.StringJoiner;
import java.util.Objects;
import java.util.Map;
import java.util.HashMap;
import java.util.Locale;
import com.adguard.stores.appstoreconnect.model.GameCenterAchievement;
import com.adguard.stores.appstoreconnect.model.GameCenterActivity;
import com.adguard.stores.appstoreconnect.model.GameCenterChallenge;
import com.adguard.stores.appstoreconnect.model.GameCenterDetail;
import com.adguard.stores.appstoreconnect.model.GameCenterLeaderboard;
import com.adguard.stores.appstoreconnect.model.GameCenterLeaderboardAttributes;
import com.adguard.stores.appstoreconnect.model.GameCenterLeaderboardRelationships;
import com.adguard.stores.appstoreconnect.model.GameCenterLeaderboardSet;
import com.adguard.stores.appstoreconnect.model.ResourceLinks;
import com.fasterxml.jackson.annotation.JsonIgnoreProperties;
import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonSubTypes;
import com.fasterxml.jackson.annotation.JsonTypeInfo;
import com.fasterxml.jackson.annotation.JsonTypeName;
import com.fasterxml.jackson.annotation.JsonValue;
import java.util.Arrays;
import com.fasterxml.jackson.annotation.JsonPropertyOrder;

import com.fasterxml.jackson.core.type.TypeReference;

import java.io.IOException;
import java.util.logging.Level;
import java.util.logging.Logger;
import java.util.ArrayList;
import java.util.Collections;
import java.util.HashSet;
import java.util.Locale;

import com.fasterxml.jackson.core.JsonGenerator;
import com.fasterxml.jackson.core.JsonParser;
import com.fasterxml.jackson.core.JsonProcessingException;
import com.fasterxml.jackson.core.JsonToken;
import com.fasterxml.jackson.databind.DeserializationContext;
import com.fasterxml.jackson.databind.JsonMappingException;
import com.fasterxml.jackson.databind.JsonNode;
import com.fasterxml.jackson.databind.MapperFeature;
import com.fasterxml.jackson.databind.SerializerProvider;
import com.fasterxml.jackson.databind.annotation.JsonDeserialize;
import com.fasterxml.jackson.databind.annotation.JsonSerialize;
import com.fasterxml.jackson.databind.deser.std.StdDeserializer;
import com.fasterxml.jackson.databind.ser.std.StdSerializer;
import com.adguard.stores.appstoreconnect.ApiClient;
import com.adguard.stores.appstoreconnect.JSON;

@jakarta.annotation.Generated(value = "org.openapitools.codegen.languages.JavaClientCodegen", comments = "Generator version: 7.17.0")
@JsonDeserialize(using = GameCenterGroupsResponseIncludedInner.GameCenterGroupsResponseIncludedInnerDeserializer.class)
@JsonSerialize(using = GameCenterGroupsResponseIncludedInner.GameCenterGroupsResponseIncludedInnerSerializer.class)
public class GameCenterGroupsResponseIncludedInner extends AbstractOpenApiSchema {
    private static final Logger log = Logger.getLogger(GameCenterGroupsResponseIncludedInner.class.getName());

    public static class GameCenterGroupsResponseIncludedInnerSerializer extends StdSerializer<GameCenterGroupsResponseIncludedInner> {
        public GameCenterGroupsResponseIncludedInnerSerializer(Class<GameCenterGroupsResponseIncludedInner> t) {
            super(t);
        }

        public GameCenterGroupsResponseIncludedInnerSerializer() {
            this(null);
        }

        @Override
        public void serialize(GameCenterGroupsResponseIncludedInner value, JsonGenerator jgen, SerializerProvider provider) throws IOException, JsonProcessingException {
            jgen.writeObject(value.getActualInstance());
        }
    }

    public static class GameCenterGroupsResponseIncludedInnerDeserializer extends StdDeserializer<GameCenterGroupsResponseIncludedInner> {
        public GameCenterGroupsResponseIncludedInnerDeserializer() {
            this(GameCenterGroupsResponseIncludedInner.class);
        }

        public GameCenterGroupsResponseIncludedInnerDeserializer(Class<?> vc) {
            super(vc);
        }

        @Override
        public GameCenterGroupsResponseIncludedInner deserialize(JsonParser jp, DeserializationContext ctxt) throws IOException, JsonProcessingException {
            JsonNode tree = jp.readValueAsTree();
            Object deserialized = null;
            boolean typeCoercion = ctxt.isEnabled(MapperFeature.ALLOW_COERCION_OF_SCALARS);
            int match = 0;
            JsonToken token = tree.traverse(jp.getCodec()).nextToken();
            // deserialize GameCenterAchievement
            try {
                boolean attemptParsing = true;
                // ensure that we respect type coercion as set on the client ObjectMapper
                if (GameCenterAchievement.class.equals(Integer.class) || GameCenterAchievement.class.equals(Long.class) || GameCenterAchievement.class.equals(Float.class) || GameCenterAchievement.class.equals(Double.class) || GameCenterAchievement.class.equals(Boolean.class) || GameCenterAchievement.class.equals(String.class)) {
                    attemptParsing = typeCoercion;
                    if (!attemptParsing) {
                        attemptParsing |= ((GameCenterAchievement.class.equals(Integer.class) || GameCenterAchievement.class.equals(Long.class)) && token == JsonToken.VALUE_NUMBER_INT);
                        attemptParsing |= ((GameCenterAchievement.class.equals(Float.class) || GameCenterAchievement.class.equals(Double.class)) && token == JsonToken.VALUE_NUMBER_FLOAT);
                        attemptParsing |= (GameCenterAchievement.class.equals(Boolean.class) && (token == JsonToken.VALUE_FALSE || token == JsonToken.VALUE_TRUE));
                        attemptParsing |= (GameCenterAchievement.class.equals(String.class) && token == JsonToken.VALUE_STRING);
                    }
                }
                if (attemptParsing) {
                    deserialized = tree.traverse(jp.getCodec()).readValueAs(GameCenterAchievement.class);
                    // TODO: there is no validation against JSON schema constraints
                    // (min, max, enum, pattern...), this does not perform a strict JSON
                    // validation, which means the 'match' count may be higher than it should be.
                    match++;
                    log.log(Level.FINER, "Input data matches schema 'GameCenterAchievement'");
                }
            } catch (Exception e) {
                // deserialization failed, continue
                log.log(Level.FINER, "Input data does not match schema 'GameCenterAchievement'", e);
            }

            // deserialize GameCenterActivity
            try {
                boolean attemptParsing = true;
                // ensure that we respect type coercion as set on the client ObjectMapper
                if (GameCenterActivity.class.equals(Integer.class) || GameCenterActivity.class.equals(Long.class) || GameCenterActivity.class.equals(Float.class) || GameCenterActivity.class.equals(Double.class) || GameCenterActivity.class.equals(Boolean.class) || GameCenterActivity.class.equals(String.class)) {
                    attemptParsing = typeCoercion;
                    if (!attemptParsing) {
                        attemptParsing |= ((GameCenterActivity.class.equals(Integer.class) || GameCenterActivity.class.equals(Long.class)) && token == JsonToken.VALUE_NUMBER_INT);
                        attemptParsing |= ((GameCenterActivity.class.equals(Float.class) || GameCenterActivity.class.equals(Double.class)) && token == JsonToken.VALUE_NUMBER_FLOAT);
                        attemptParsing |= (GameCenterActivity.class.equals(Boolean.class) && (token == JsonToken.VALUE_FALSE || token == JsonToken.VALUE_TRUE));
                        attemptParsing |= (GameCenterActivity.class.equals(String.class) && token == JsonToken.VALUE_STRING);
                    }
                }
                if (attemptParsing) {
                    deserialized = tree.traverse(jp.getCodec()).readValueAs(GameCenterActivity.class);
                    // TODO: there is no validation against JSON schema constraints
                    // (min, max, enum, pattern...), this does not perform a strict JSON
                    // validation, which means the 'match' count may be higher than it should be.
                    match++;
                    log.log(Level.FINER, "Input data matches schema 'GameCenterActivity'");
                }
            } catch (Exception e) {
                // deserialization failed, continue
                log.log(Level.FINER, "Input data does not match schema 'GameCenterActivity'", e);
            }

            // deserialize GameCenterChallenge
            try {
                boolean attemptParsing = true;
                // ensure that we respect type coercion as set on the client ObjectMapper
                if (GameCenterChallenge.class.equals(Integer.class) || GameCenterChallenge.class.equals(Long.class) || GameCenterChallenge.class.equals(Float.class) || GameCenterChallenge.class.equals(Double.class) || GameCenterChallenge.class.equals(Boolean.class) || GameCenterChallenge.class.equals(String.class)) {
                    attemptParsing = typeCoercion;
                    if (!attemptParsing) {
                        attemptParsing |= ((GameCenterChallenge.class.equals(Integer.class) || GameCenterChallenge.class.equals(Long.class)) && token == JsonToken.VALUE_NUMBER_INT);
                        attemptParsing |= ((GameCenterChallenge.class.equals(Float.class) || GameCenterChallenge.class.equals(Double.class)) && token == JsonToken.VALUE_NUMBER_FLOAT);
                        attemptParsing |= (GameCenterChallenge.class.equals(Boolean.class) && (token == JsonToken.VALUE_FALSE || token == JsonToken.VALUE_TRUE));
                        attemptParsing |= (GameCenterChallenge.class.equals(String.class) && token == JsonToken.VALUE_STRING);
                    }
                }
                if (attemptParsing) {
                    deserialized = tree.traverse(jp.getCodec()).readValueAs(GameCenterChallenge.class);
                    // TODO: there is no validation against JSON schema constraints
                    // (min, max, enum, pattern...), this does not perform a strict JSON
                    // validation, which means the 'match' count may be higher than it should be.
                    match++;
                    log.log(Level.FINER, "Input data matches schema 'GameCenterChallenge'");
                }
            } catch (Exception e) {
                // deserialization failed, continue
                log.log(Level.FINER, "Input data does not match schema 'GameCenterChallenge'", e);
            }

            // deserialize GameCenterDetail
            try {
                boolean attemptParsing = true;
                // ensure that we respect type coercion as set on the client ObjectMapper
                if (GameCenterDetail.class.equals(Integer.class) || GameCenterDetail.class.equals(Long.class) || GameCenterDetail.class.equals(Float.class) || GameCenterDetail.class.equals(Double.class) || GameCenterDetail.class.equals(Boolean.class) || GameCenterDetail.class.equals(String.class)) {
                    attemptParsing = typeCoercion;
                    if (!attemptParsing) {
                        attemptParsing |= ((GameCenterDetail.class.equals(Integer.class) || GameCenterDetail.class.equals(Long.class)) && token == JsonToken.VALUE_NUMBER_INT);
                        attemptParsing |= ((GameCenterDetail.class.equals(Float.class) || GameCenterDetail.class.equals(Double.class)) && token == JsonToken.VALUE_NUMBER_FLOAT);
                        attemptParsing |= (GameCenterDetail.class.equals(Boolean.class) && (token == JsonToken.VALUE_FALSE || token == JsonToken.VALUE_TRUE));
                        attemptParsing |= (GameCenterDetail.class.equals(String.class) && token == JsonToken.VALUE_STRING);
                    }
                }
                if (attemptParsing) {
                    deserialized = tree.traverse(jp.getCodec()).readValueAs(GameCenterDetail.class);
                    // TODO: there is no validation against JSON schema constraints
                    // (min, max, enum, pattern...), this does not perform a strict JSON
                    // validation, which means the 'match' count may be higher than it should be.
                    match++;
                    log.log(Level.FINER, "Input data matches schema 'GameCenterDetail'");
                }
            } catch (Exception e) {
                // deserialization failed, continue
                log.log(Level.FINER, "Input data does not match schema 'GameCenterDetail'", e);
            }

            // deserialize GameCenterLeaderboard
            try {
                boolean attemptParsing = true;
                // ensure that we respect type coercion as set on the client ObjectMapper
                if (GameCenterLeaderboard.class.equals(Integer.class) || GameCenterLeaderboard.class.equals(Long.class) || GameCenterLeaderboard.class.equals(Float.class) || GameCenterLeaderboard.class.equals(Double.class) || GameCenterLeaderboard.class.equals(Boolean.class) || GameCenterLeaderboard.class.equals(String.class)) {
                    attemptParsing = typeCoercion;
                    if (!attemptParsing) {
                        attemptParsing |= ((GameCenterLeaderboard.class.equals(Integer.class) || GameCenterLeaderboard.class.equals(Long.class)) && token == JsonToken.VALUE_NUMBER_INT);
                        attemptParsing |= ((GameCenterLeaderboard.class.equals(Float.class) || GameCenterLeaderboard.class.equals(Double.class)) && token == JsonToken.VALUE_NUMBER_FLOAT);
                        attemptParsing |= (GameCenterLeaderboard.class.equals(Boolean.class) && (token == JsonToken.VALUE_FALSE || token == JsonToken.VALUE_TRUE));
                        attemptParsing |= (GameCenterLeaderboard.class.equals(String.class) && token == JsonToken.VALUE_STRING);
                    }
                }
                if (attemptParsing) {
                    deserialized = tree.traverse(jp.getCodec()).readValueAs(GameCenterLeaderboard.class);
                    // TODO: there is no validation against JSON schema constraints
                    // (min, max, enum, pattern...), this does not perform a strict JSON
                    // validation, which means the 'match' count may be higher than it should be.
                    match++;
                    log.log(Level.FINER, "Input data matches schema 'GameCenterLeaderboard'");
                }
            } catch (Exception e) {
                // deserialization failed, continue
                log.log(Level.FINER, "Input data does not match schema 'GameCenterLeaderboard'", e);
            }

            // deserialize GameCenterLeaderboardSet
            try {
                boolean attemptParsing = true;
                // ensure that we respect type coercion as set on the client ObjectMapper
                if (GameCenterLeaderboardSet.class.equals(Integer.class) || GameCenterLeaderboardSet.class.equals(Long.class) || GameCenterLeaderboardSet.class.equals(Float.class) || GameCenterLeaderboardSet.class.equals(Double.class) || GameCenterLeaderboardSet.class.equals(Boolean.class) || GameCenterLeaderboardSet.class.equals(String.class)) {
                    attemptParsing = typeCoercion;
                    if (!attemptParsing) {
                        attemptParsing |= ((GameCenterLeaderboardSet.class.equals(Integer.class) || GameCenterLeaderboardSet.class.equals(Long.class)) && token == JsonToken.VALUE_NUMBER_INT);
                        attemptParsing |= ((GameCenterLeaderboardSet.class.equals(Float.class) || GameCenterLeaderboardSet.class.equals(Double.class)) && token == JsonToken.VALUE_NUMBER_FLOAT);
                        attemptParsing |= (GameCenterLeaderboardSet.class.equals(Boolean.class) && (token == JsonToken.VALUE_FALSE || token == JsonToken.VALUE_TRUE));
                        attemptParsing |= (GameCenterLeaderboardSet.class.equals(String.class) && token == JsonToken.VALUE_STRING);
                    }
                }
                if (attemptParsing) {
                    deserialized = tree.traverse(jp.getCodec()).readValueAs(GameCenterLeaderboardSet.class);
                    // TODO: there is no validation against JSON schema constraints
                    // (min, max, enum, pattern...), this does not perform a strict JSON
                    // validation, which means the 'match' count may be higher than it should be.
                    match++;
                    log.log(Level.FINER, "Input data matches schema 'GameCenterLeaderboardSet'");
                }
            } catch (Exception e) {
                // deserialization failed, continue
                log.log(Level.FINER, "Input data does not match schema 'GameCenterLeaderboardSet'", e);
            }

            if (match == 1) {
                GameCenterGroupsResponseIncludedInner ret = new GameCenterGroupsResponseIncludedInner();
                ret.setActualInstance(deserialized);
                return ret;
            }
            throw new IOException(String.format(Locale.ROOT, "Failed deserialization for GameCenterGroupsResponseIncludedInner: %d classes match result, expected 1", match));
        }

        /**
         * Handle deserialization of the 'null' value.
         */
        @Override
        public GameCenterGroupsResponseIncludedInner getNullValue(DeserializationContext ctxt) throws JsonMappingException {
            throw new JsonMappingException(ctxt.getParser(), "GameCenterGroupsResponseIncludedInner cannot be null");
        }
    }

    // store a list of schema names defined in oneOf
    public static final Map<String, Class<?>> schemas = new HashMap<>();

    public GameCenterGroupsResponseIncludedInner() {
        super("oneOf", Boolean.FALSE);
    }
  /**
   * A container for additional, undeclared properties.
   * This is a holder for any undeclared properties as specified with
   * the 'additionalProperties' keyword in the OAS document.
   */
  private Map<String, Object> additionalProperties;

  /**
   * Set the additional (undeclared) property with the specified name and value.
   * If the property does not already exist, create it otherwise replace it.
   * @param key the name of the property
   * @param value the value of the property
   * @return self reference
   */
  @JsonAnySetter
  public GameCenterGroupsResponseIncludedInner putAdditionalProperty(String key, Object value) {
    if (this.additionalProperties == null) {
        this.additionalProperties = new HashMap<String, Object>();
    }
    this.additionalProperties.put(key, value);
    return this;
  }

  /**
   * Return the additional (undeclared) properties.
   * @return the additional (undeclared) properties
   */
  @JsonAnyGetter
  public Map<String, Object> getAdditionalProperties() {
    return additionalProperties;
  }

  /**
   * Return the additional (undeclared) property with the specified name.
   * @param key the name of the property
   * @return the additional (undeclared) property with the specified name
   */
  public Object getAdditionalProperty(String key) {
    if (this.additionalProperties == null) {
        return null;
    }
    return this.additionalProperties.get(key);
  }

    /**
     * Return true if this GameCenterGroupsResponse_included_inner object is equal to o.
     */
    @Override
    public boolean equals(Object o) {
        return super.equals(o) && Objects.equals(this.additionalProperties, ((GameCenterGroupsResponseIncludedInner)o).additionalProperties);
    }

    @Override
    public int hashCode() {
        return Objects.hash(getActualInstance(), isNullable(), getSchemaType(), additionalProperties);
    }
    public GameCenterGroupsResponseIncludedInner(GameCenterAchievement o) {
        super("oneOf", Boolean.FALSE);
        setActualInstance(o);
    }

    public GameCenterGroupsResponseIncludedInner(GameCenterActivity o) {
        super("oneOf", Boolean.FALSE);
        setActualInstance(o);
    }

    public GameCenterGroupsResponseIncludedInner(GameCenterChallenge o) {
        super("oneOf", Boolean.FALSE);
        setActualInstance(o);
    }

    public GameCenterGroupsResponseIncludedInner(GameCenterDetail o) {
        super("oneOf", Boolean.FALSE);
        setActualInstance(o);
    }

    public GameCenterGroupsResponseIncludedInner(GameCenterLeaderboard o) {
        super("oneOf", Boolean.FALSE);
        setActualInstance(o);
    }

    public GameCenterGroupsResponseIncludedInner(GameCenterLeaderboardSet o) {
        super("oneOf", Boolean.FALSE);
        setActualInstance(o);
    }

    static {
        schemas.put("GameCenterAchievement", GameCenterAchievement.class);
        schemas.put("GameCenterActivity", GameCenterActivity.class);
        schemas.put("GameCenterChallenge", GameCenterChallenge.class);
        schemas.put("GameCenterDetail", GameCenterDetail.class);
        schemas.put("GameCenterLeaderboard", GameCenterLeaderboard.class);
        schemas.put("GameCenterLeaderboardSet", GameCenterLeaderboardSet.class);
        JSON.registerDescendants(GameCenterGroupsResponseIncludedInner.class, Collections.unmodifiableMap(schemas));
        // Initialize and register the discriminator mappings.
        Map<String, Class<?>> mappings = new HashMap<String, Class<?>>();
        mappings.put("gameCenterAchievements", GameCenterAchievement.class);
        mappings.put("gameCenterActivities", GameCenterActivity.class);
        mappings.put("gameCenterChallenges", GameCenterChallenge.class);
        mappings.put("gameCenterDetails", GameCenterDetail.class);
        mappings.put("gameCenterLeaderboardSets", GameCenterLeaderboardSet.class);
        mappings.put("gameCenterLeaderboards", GameCenterLeaderboard.class);
        mappings.put("GameCenterGroupsResponse_included_inner", GameCenterGroupsResponseIncludedInner.class);
        JSON.registerDiscriminator(GameCenterGroupsResponseIncludedInner.class, "type", mappings);
    }

    @Override
    public Map<String, Class<?>> getSchemas() {
        return GameCenterGroupsResponseIncludedInner.schemas;
    }

    /**
     * Set the instance that matches the oneOf child schema, check
     * the instance parameter is valid against the oneOf child schemas:
     * GameCenterAchievement, GameCenterActivity, GameCenterChallenge, GameCenterDetail, GameCenterLeaderboard, GameCenterLeaderboardSet
     *
     * It could be an instance of the 'oneOf' schemas.
     * The oneOf child schemas may themselves be a composed schema (allOf, anyOf, oneOf).
     */
    @Override
    public void setActualInstance(Object instance) {
        if (JSON.isInstanceOf(GameCenterAchievement.class, instance, new HashSet<Class<?>>())) {
            super.setActualInstance(instance);
            return;
        }

        if (JSON.isInstanceOf(GameCenterActivity.class, instance, new HashSet<Class<?>>())) {
            super.setActualInstance(instance);
            return;
        }

        if (JSON.isInstanceOf(GameCenterChallenge.class, instance, new HashSet<Class<?>>())) {
            super.setActualInstance(instance);
            return;
        }

        if (JSON.isInstanceOf(GameCenterDetail.class, instance, new HashSet<Class<?>>())) {
            super.setActualInstance(instance);
            return;
        }

        if (JSON.isInstanceOf(GameCenterLeaderboard.class, instance, new HashSet<Class<?>>())) {
            super.setActualInstance(instance);
            return;
        }

        if (JSON.isInstanceOf(GameCenterLeaderboardSet.class, instance, new HashSet<Class<?>>())) {
            super.setActualInstance(instance);
            return;
        }

        throw new RuntimeException("Invalid instance type. Must be GameCenterAchievement, GameCenterActivity, GameCenterChallenge, GameCenterDetail, GameCenterLeaderboard, GameCenterLeaderboardSet");
    }

    /**
     * Get the actual instance, which can be the following:
     * GameCenterAchievement, GameCenterActivity, GameCenterChallenge, GameCenterDetail, GameCenterLeaderboard, GameCenterLeaderboardSet
     *
     * @return The actual instance (GameCenterAchievement, GameCenterActivity, GameCenterChallenge, GameCenterDetail, GameCenterLeaderboard, GameCenterLeaderboardSet)
     */
    @Override
    public Object getActualInstance() {
        return super.getActualInstance();
    }

    /**
     * Get the actual instance of `GameCenterAchievement`. If the actual instance is not `GameCenterAchievement`,
     * the ClassCastException will be thrown.
     *
     * @return The actual instance of `GameCenterAchievement`
     * @throws ClassCastException if the instance is not `GameCenterAchievement`
     */
    public GameCenterAchievement getGameCenterAchievement() throws ClassCastException {
        return (GameCenterAchievement)super.getActualInstance();
    }

    /**
     * Get the actual instance of `GameCenterActivity`. If the actual instance is not `GameCenterActivity`,
     * the ClassCastException will be thrown.
     *
     * @return The actual instance of `GameCenterActivity`
     * @throws ClassCastException if the instance is not `GameCenterActivity`
     */
    public GameCenterActivity getGameCenterActivity() throws ClassCastException {
        return (GameCenterActivity)super.getActualInstance();
    }

    /**
     * Get the actual instance of `GameCenterChallenge`. If the actual instance is not `GameCenterChallenge`,
     * the ClassCastException will be thrown.
     *
     * @return The actual instance of `GameCenterChallenge`
     * @throws ClassCastException if the instance is not `GameCenterChallenge`
     */
    public GameCenterChallenge getGameCenterChallenge() throws ClassCastException {
        return (GameCenterChallenge)super.getActualInstance();
    }

    /**
     * Get the actual instance of `GameCenterDetail`. If the actual instance is not `GameCenterDetail`,
     * the ClassCastException will be thrown.
     *
     * @return The actual instance of `GameCenterDetail`
     * @throws ClassCastException if the instance is not `GameCenterDetail`
     */
    public GameCenterDetail getGameCenterDetail() throws ClassCastException {
        return (GameCenterDetail)super.getActualInstance();
    }

    /**
     * Get the actual instance of `GameCenterLeaderboard`. If the actual instance is not `GameCenterLeaderboard`,
     * the ClassCastException will be thrown.
     *
     * @return The actual instance of `GameCenterLeaderboard`
     * @throws ClassCastException if the instance is not `GameCenterLeaderboard`
     */
    public GameCenterLeaderboard getGameCenterLeaderboard() throws ClassCastException {
        return (GameCenterLeaderboard)super.getActualInstance();
    }

    /**
     * Get the actual instance of `GameCenterLeaderboardSet`. If the actual instance is not `GameCenterLeaderboardSet`,
     * the ClassCastException will be thrown.
     *
     * @return The actual instance of `GameCenterLeaderboardSet`
     * @throws ClassCastException if the instance is not `GameCenterLeaderboardSet`
     */
    public GameCenterLeaderboardSet getGameCenterLeaderboardSet() throws ClassCastException {
        return (GameCenterLeaderboardSet)super.getActualInstance();
    }



  /**
   * Convert the instance into URL query string.
   *
   * @return URL query string
   */
  public String toUrlQueryString() {
    return toUrlQueryString(null);
  }

  /**
   * Convert the instance into URL query string.
   *
   * @param prefix prefix of the query string
   * @return URL query string
   */
  public String toUrlQueryString(String prefix) {
    String suffix = "";
    String containerSuffix = "";
    String containerPrefix = "";
    if (prefix == null) {
      // style=form, explode=true, e.g. /pet?name=cat&type=manx
      prefix = "";
    } else {
      // deepObject style e.g. /pet?id[name]=cat&id[type]=manx
      prefix = prefix + "[";
      suffix = "]";
      containerSuffix = "]";
      containerPrefix = "[";
    }

    StringJoiner joiner = new StringJoiner("&");

    if (getActualInstance() instanceof GameCenterAchievement) {
        if (getActualInstance() != null) {
          joiner.add(((GameCenterAchievement)getActualInstance()).toUrlQueryString(prefix + "one_of_0" + suffix));
        }
        return joiner.toString();
    }
    if (getActualInstance() instanceof GameCenterActivity) {
        if (getActualInstance() != null) {
          joiner.add(((GameCenterActivity)getActualInstance()).toUrlQueryString(prefix + "one_of_1" + suffix));
        }
        return joiner.toString();
    }
    if (getActualInstance() instanceof GameCenterChallenge) {
        if (getActualInstance() != null) {
          joiner.add(((GameCenterChallenge)getActualInstance()).toUrlQueryString(prefix + "one_of_2" + suffix));
        }
        return joiner.toString();
    }
    if (getActualInstance() instanceof GameCenterDetail) {
        if (getActualInstance() != null) {
          joiner.add(((GameCenterDetail)getActualInstance()).toUrlQueryString(prefix + "one_of_3" + suffix));
        }
        return joiner.toString();
    }
    if (getActualInstance() instanceof GameCenterLeaderboardSet) {
        if (getActualInstance() != null) {
          joiner.add(((GameCenterLeaderboardSet)getActualInstance()).toUrlQueryString(prefix + "one_of_4" + suffix));
        }
        return joiner.toString();
    }
    if (getActualInstance() instanceof GameCenterLeaderboard) {
        if (getActualInstance() != null) {
          joiner.add(((GameCenterLeaderboard)getActualInstance()).toUrlQueryString(prefix + "one_of_5" + suffix));
        }
        return joiner.toString();
    }
    return null;
  }

}

