/*
 * App Store Connect API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 4.2
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package com.adguard.stores.appstoreconnect.model;

import java.net.URLEncoder;
import java.nio.charset.StandardCharsets;
import java.util.StringJoiner;
import java.util.Objects;
import java.util.Map;
import java.util.HashMap;
import java.util.Locale;
import com.adguard.stores.appstoreconnect.model.GameCenterLeaderboardSetLocalizationRelationshipsGameCenterLeaderboardSet;
import com.adguard.stores.appstoreconnect.model.GameCenterLeaderboardSetVersionV2RelationshipsLocalizations;
import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonTypeName;
import com.fasterxml.jackson.annotation.JsonValue;
import java.util.Arrays;
import com.fasterxml.jackson.annotation.JsonPropertyOrder;


import com.adguard.stores.appstoreconnect.ApiClient;
/**
 * GameCenterLeaderboardSetVersionV2Relationships
 */
@JsonPropertyOrder({
  GameCenterLeaderboardSetVersionV2Relationships.JSON_PROPERTY_LEADERBOARD_SET,
  GameCenterLeaderboardSetVersionV2Relationships.JSON_PROPERTY_LOCALIZATIONS
})
@jakarta.annotation.Generated(value = "org.openapitools.codegen.languages.JavaClientCodegen", comments = "Generator version: 7.17.0")
public class GameCenterLeaderboardSetVersionV2Relationships {
  public static final String JSON_PROPERTY_LEADERBOARD_SET = "leaderboardSet";
  @jakarta.annotation.Nullable
  private GameCenterLeaderboardSetLocalizationRelationshipsGameCenterLeaderboardSet leaderboardSet;

  public static final String JSON_PROPERTY_LOCALIZATIONS = "localizations";
  @jakarta.annotation.Nullable
  private GameCenterLeaderboardSetVersionV2RelationshipsLocalizations localizations;

  public GameCenterLeaderboardSetVersionV2Relationships() { 
  }

  public GameCenterLeaderboardSetVersionV2Relationships leaderboardSet(@jakarta.annotation.Nullable GameCenterLeaderboardSetLocalizationRelationshipsGameCenterLeaderboardSet leaderboardSet) {
    this.leaderboardSet = leaderboardSet;
    return this;
  }

  /**
   * Get leaderboardSet
   * @return leaderboardSet
   */
  @jakarta.annotation.Nullable
  @JsonProperty(value = JSON_PROPERTY_LEADERBOARD_SET, required = false)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public GameCenterLeaderboardSetLocalizationRelationshipsGameCenterLeaderboardSet getLeaderboardSet() {
    return leaderboardSet;
  }


  @JsonProperty(value = JSON_PROPERTY_LEADERBOARD_SET, required = false)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setLeaderboardSet(@jakarta.annotation.Nullable GameCenterLeaderboardSetLocalizationRelationshipsGameCenterLeaderboardSet leaderboardSet) {
    this.leaderboardSet = leaderboardSet;
  }


  public GameCenterLeaderboardSetVersionV2Relationships localizations(@jakarta.annotation.Nullable GameCenterLeaderboardSetVersionV2RelationshipsLocalizations localizations) {
    this.localizations = localizations;
    return this;
  }

  /**
   * Get localizations
   * @return localizations
   */
  @jakarta.annotation.Nullable
  @JsonProperty(value = JSON_PROPERTY_LOCALIZATIONS, required = false)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public GameCenterLeaderboardSetVersionV2RelationshipsLocalizations getLocalizations() {
    return localizations;
  }


  @JsonProperty(value = JSON_PROPERTY_LOCALIZATIONS, required = false)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setLocalizations(@jakarta.annotation.Nullable GameCenterLeaderboardSetVersionV2RelationshipsLocalizations localizations) {
    this.localizations = localizations;
  }


  /**
   * Return true if this GameCenterLeaderboardSetVersionV2_relationships object is equal to o.
   */
  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    GameCenterLeaderboardSetVersionV2Relationships gameCenterLeaderboardSetVersionV2Relationships = (GameCenterLeaderboardSetVersionV2Relationships) o;
    return Objects.equals(this.leaderboardSet, gameCenterLeaderboardSetVersionV2Relationships.leaderboardSet) &&
        Objects.equals(this.localizations, gameCenterLeaderboardSetVersionV2Relationships.localizations);
  }

  @Override
  public int hashCode() {
    return Objects.hash(leaderboardSet, localizations);
  }

  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class GameCenterLeaderboardSetVersionV2Relationships {\n");
    sb.append("    leaderboardSet: ").append(toIndentedString(leaderboardSet)).append("\n");
    sb.append("    localizations: ").append(toIndentedString(localizations)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

  /**
   * Convert the instance into URL query string.
   *
   * @return URL query string
   */
  public String toUrlQueryString() {
    return toUrlQueryString(null);
  }

  /**
   * Convert the instance into URL query string.
   *
   * @param prefix prefix of the query string
   * @return URL query string
   */
  public String toUrlQueryString(String prefix) {
    String suffix = "";
    String containerSuffix = "";
    String containerPrefix = "";
    if (prefix == null) {
      // style=form, explode=true, e.g. /pet?name=cat&type=manx
      prefix = "";
    } else {
      // deepObject style e.g. /pet?id[name]=cat&id[type]=manx
      prefix = prefix + "[";
      suffix = "]";
      containerSuffix = "]";
      containerPrefix = "[";
    }

    StringJoiner joiner = new StringJoiner("&");

    // add `leaderboardSet` to the URL query string
    if (getLeaderboardSet() != null) {
      joiner.add(getLeaderboardSet().toUrlQueryString(prefix + "leaderboardSet" + suffix));
    }

    // add `localizations` to the URL query string
    if (getLocalizations() != null) {
      joiner.add(getLocalizations().toUrlQueryString(prefix + "localizations" + suffix));
    }

    return joiner.toString();
  }
}

