/*
 * App Store Connect API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 4.2
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package com.adguard.stores.appstoreconnect.model;

import java.net.URLEncoder;
import java.nio.charset.StandardCharsets;
import java.util.StringJoiner;
import java.util.Objects;
import java.util.Map;
import java.util.HashMap;
import java.util.Locale;
import com.adguard.stores.appstoreconnect.model.DocumentLinks;
import com.adguard.stores.appstoreconnect.model.GameCenterAchievementVersionV2;
import com.adguard.stores.appstoreconnect.model.GameCenterAchievementVersionsV2ResponseIncludedInner;
import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonTypeName;
import com.fasterxml.jackson.annotation.JsonValue;
import java.util.ArrayList;
import java.util.Arrays;
import java.util.List;
import com.fasterxml.jackson.annotation.JsonPropertyOrder;


import com.adguard.stores.appstoreconnect.ApiClient;
/**
 * GameCenterAchievementVersionV2Response
 */
@JsonPropertyOrder({
  GameCenterAchievementVersionV2Response.JSON_PROPERTY_DATA,
  GameCenterAchievementVersionV2Response.JSON_PROPERTY_INCLUDED,
  GameCenterAchievementVersionV2Response.JSON_PROPERTY_LINKS
})
@jakarta.annotation.Generated(value = "org.openapitools.codegen.languages.JavaClientCodegen", comments = "Generator version: 7.17.0")
public class GameCenterAchievementVersionV2Response {
  public static final String JSON_PROPERTY_DATA = "data";
  @jakarta.annotation.Nonnull
  private GameCenterAchievementVersionV2 data;

  public static final String JSON_PROPERTY_INCLUDED = "included";
  @jakarta.annotation.Nullable
  private List<GameCenterAchievementVersionsV2ResponseIncludedInner> included = new ArrayList<>();

  public static final String JSON_PROPERTY_LINKS = "links";
  @jakarta.annotation.Nonnull
  private DocumentLinks links;

  public GameCenterAchievementVersionV2Response() { 
  }

  public GameCenterAchievementVersionV2Response data(@jakarta.annotation.Nonnull GameCenterAchievementVersionV2 data) {
    this.data = data;
    return this;
  }

  /**
   * Get data
   * @return data
   */
  @jakarta.annotation.Nonnull
  @JsonProperty(value = JSON_PROPERTY_DATA, required = true)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)
  public GameCenterAchievementVersionV2 getData() {
    return data;
  }


  @JsonProperty(value = JSON_PROPERTY_DATA, required = true)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)
  public void setData(@jakarta.annotation.Nonnull GameCenterAchievementVersionV2 data) {
    this.data = data;
  }


  public GameCenterAchievementVersionV2Response included(@jakarta.annotation.Nullable List<GameCenterAchievementVersionsV2ResponseIncludedInner> included) {
    this.included = included;
    return this;
  }

  public GameCenterAchievementVersionV2Response addIncludedItem(GameCenterAchievementVersionsV2ResponseIncludedInner includedItem) {
    if (this.included == null) {
      this.included = new ArrayList<>();
    }
    this.included.add(includedItem);
    return this;
  }

  /**
   * Get included
   * @return included
   */
  @jakarta.annotation.Nullable
  @JsonProperty(value = JSON_PROPERTY_INCLUDED, required = false)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public List<GameCenterAchievementVersionsV2ResponseIncludedInner> getIncluded() {
    return included;
  }


  @JsonProperty(value = JSON_PROPERTY_INCLUDED, required = false)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setIncluded(@jakarta.annotation.Nullable List<GameCenterAchievementVersionsV2ResponseIncludedInner> included) {
    this.included = included;
  }


  public GameCenterAchievementVersionV2Response links(@jakarta.annotation.Nonnull DocumentLinks links) {
    this.links = links;
    return this;
  }

  /**
   * Get links
   * @return links
   */
  @jakarta.annotation.Nonnull
  @JsonProperty(value = JSON_PROPERTY_LINKS, required = true)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)
  public DocumentLinks getLinks() {
    return links;
  }


  @JsonProperty(value = JSON_PROPERTY_LINKS, required = true)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)
  public void setLinks(@jakarta.annotation.Nonnull DocumentLinks links) {
    this.links = links;
  }


  /**
   * Return true if this GameCenterAchievementVersionV2Response object is equal to o.
   */
  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    GameCenterAchievementVersionV2Response gameCenterAchievementVersionV2Response = (GameCenterAchievementVersionV2Response) o;
    return Objects.equals(this.data, gameCenterAchievementVersionV2Response.data) &&
        Objects.equals(this.included, gameCenterAchievementVersionV2Response.included) &&
        Objects.equals(this.links, gameCenterAchievementVersionV2Response.links);
  }

  @Override
  public int hashCode() {
    return Objects.hash(data, included, links);
  }

  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class GameCenterAchievementVersionV2Response {\n");
    sb.append("    data: ").append(toIndentedString(data)).append("\n");
    sb.append("    included: ").append(toIndentedString(included)).append("\n");
    sb.append("    links: ").append(toIndentedString(links)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

  /**
   * Convert the instance into URL query string.
   *
   * @return URL query string
   */
  public String toUrlQueryString() {
    return toUrlQueryString(null);
  }

  /**
   * Convert the instance into URL query string.
   *
   * @param prefix prefix of the query string
   * @return URL query string
   */
  public String toUrlQueryString(String prefix) {
    String suffix = "";
    String containerSuffix = "";
    String containerPrefix = "";
    if (prefix == null) {
      // style=form, explode=true, e.g. /pet?name=cat&type=manx
      prefix = "";
    } else {
      // deepObject style e.g. /pet?id[name]=cat&id[type]=manx
      prefix = prefix + "[";
      suffix = "]";
      containerSuffix = "]";
      containerPrefix = "[";
    }

    StringJoiner joiner = new StringJoiner("&");

    // add `data` to the URL query string
    if (getData() != null) {
      joiner.add(getData().toUrlQueryString(prefix + "data" + suffix));
    }

    // add `included` to the URL query string
    if (getIncluded() != null) {
      for (int i = 0; i < getIncluded().size(); i++) {
        if (getIncluded().get(i) != null) {
          joiner.add(getIncluded().get(i).toUrlQueryString(String.format(Locale.ROOT, "%sincluded%s%s", prefix, suffix,
          "".equals(suffix) ? "" : String.format(Locale.ROOT, "%s%d%s", containerPrefix, i, containerSuffix))));
        }
      }
    }

    // add `links` to the URL query string
    if (getLinks() != null) {
      joiner.add(getLinks().toUrlQueryString(prefix + "links" + suffix));
    }

    return joiner.toString();
  }
}

