/*
 * App Store Connect API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 4.2
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package com.adguard.stores.appstoreconnect.model;

import java.net.URLEncoder;
import java.nio.charset.StandardCharsets;
import java.util.StringJoiner;
import java.util.Objects;
import java.util.Map;
import java.util.HashMap;
import java.util.Locale;
import com.adguard.stores.appstoreconnect.model.GameCenterAchievementV2RelationshipsGameCenterGroup;
import com.adguard.stores.appstoreconnect.model.GameCenterChallengeCreateRequestDataRelationshipsLeaderboard;
import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonTypeName;
import com.fasterxml.jackson.annotation.JsonValue;
import java.util.Arrays;
import com.fasterxml.jackson.annotation.JsonPropertyOrder;


import com.adguard.stores.appstoreconnect.ApiClient;
/**
 * GameCenterDetailUpdateRequestDataRelationships
 */
@JsonPropertyOrder({
  GameCenterDetailUpdateRequestDataRelationships.JSON_PROPERTY_GAME_CENTER_GROUP,
  GameCenterDetailUpdateRequestDataRelationships.JSON_PROPERTY_DEFAULT_LEADERBOARD,
  GameCenterDetailUpdateRequestDataRelationships.JSON_PROPERTY_DEFAULT_LEADERBOARD_V2,
  GameCenterDetailUpdateRequestDataRelationships.JSON_PROPERTY_DEFAULT_GROUP_LEADERBOARD,
  GameCenterDetailUpdateRequestDataRelationships.JSON_PROPERTY_DEFAULT_GROUP_LEADERBOARD_V2
})
@jakarta.annotation.Generated(value = "org.openapitools.codegen.languages.JavaClientCodegen", comments = "Generator version: 7.17.0")
public class GameCenterDetailUpdateRequestDataRelationships {
  public static final String JSON_PROPERTY_GAME_CENTER_GROUP = "gameCenterGroup";
  @jakarta.annotation.Nullable
  private GameCenterAchievementV2RelationshipsGameCenterGroup gameCenterGroup;

  public static final String JSON_PROPERTY_DEFAULT_LEADERBOARD = "defaultLeaderboard";
  @jakarta.annotation.Nullable
  private GameCenterChallengeCreateRequestDataRelationshipsLeaderboard defaultLeaderboard;

  public static final String JSON_PROPERTY_DEFAULT_LEADERBOARD_V2 = "defaultLeaderboardV2";
  @jakarta.annotation.Nullable
  private GameCenterChallengeCreateRequestDataRelationshipsLeaderboard defaultLeaderboardV2;

  public static final String JSON_PROPERTY_DEFAULT_GROUP_LEADERBOARD = "defaultGroupLeaderboard";
  @jakarta.annotation.Nullable
  private GameCenterChallengeCreateRequestDataRelationshipsLeaderboard defaultGroupLeaderboard;

  public static final String JSON_PROPERTY_DEFAULT_GROUP_LEADERBOARD_V2 = "defaultGroupLeaderboardV2";
  @jakarta.annotation.Nullable
  private GameCenterChallengeCreateRequestDataRelationshipsLeaderboard defaultGroupLeaderboardV2;

  public GameCenterDetailUpdateRequestDataRelationships() { 
  }

  public GameCenterDetailUpdateRequestDataRelationships gameCenterGroup(@jakarta.annotation.Nullable GameCenterAchievementV2RelationshipsGameCenterGroup gameCenterGroup) {
    this.gameCenterGroup = gameCenterGroup;
    return this;
  }

  /**
   * Get gameCenterGroup
   * @return gameCenterGroup
   */
  @jakarta.annotation.Nullable
  @JsonProperty(value = JSON_PROPERTY_GAME_CENTER_GROUP, required = false)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public GameCenterAchievementV2RelationshipsGameCenterGroup getGameCenterGroup() {
    return gameCenterGroup;
  }


  @JsonProperty(value = JSON_PROPERTY_GAME_CENTER_GROUP, required = false)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setGameCenterGroup(@jakarta.annotation.Nullable GameCenterAchievementV2RelationshipsGameCenterGroup gameCenterGroup) {
    this.gameCenterGroup = gameCenterGroup;
  }


  public GameCenterDetailUpdateRequestDataRelationships defaultLeaderboard(@jakarta.annotation.Nullable GameCenterChallengeCreateRequestDataRelationshipsLeaderboard defaultLeaderboard) {
    this.defaultLeaderboard = defaultLeaderboard;
    return this;
  }

  /**
   * Get defaultLeaderboard
   * @return defaultLeaderboard
   */
  @jakarta.annotation.Nullable
  @JsonProperty(value = JSON_PROPERTY_DEFAULT_LEADERBOARD, required = false)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public GameCenterChallengeCreateRequestDataRelationshipsLeaderboard getDefaultLeaderboard() {
    return defaultLeaderboard;
  }


  @JsonProperty(value = JSON_PROPERTY_DEFAULT_LEADERBOARD, required = false)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setDefaultLeaderboard(@jakarta.annotation.Nullable GameCenterChallengeCreateRequestDataRelationshipsLeaderboard defaultLeaderboard) {
    this.defaultLeaderboard = defaultLeaderboard;
  }


  public GameCenterDetailUpdateRequestDataRelationships defaultLeaderboardV2(@jakarta.annotation.Nullable GameCenterChallengeCreateRequestDataRelationshipsLeaderboard defaultLeaderboardV2) {
    this.defaultLeaderboardV2 = defaultLeaderboardV2;
    return this;
  }

  /**
   * Get defaultLeaderboardV2
   * @return defaultLeaderboardV2
   */
  @jakarta.annotation.Nullable
  @JsonProperty(value = JSON_PROPERTY_DEFAULT_LEADERBOARD_V2, required = false)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public GameCenterChallengeCreateRequestDataRelationshipsLeaderboard getDefaultLeaderboardV2() {
    return defaultLeaderboardV2;
  }


  @JsonProperty(value = JSON_PROPERTY_DEFAULT_LEADERBOARD_V2, required = false)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setDefaultLeaderboardV2(@jakarta.annotation.Nullable GameCenterChallengeCreateRequestDataRelationshipsLeaderboard defaultLeaderboardV2) {
    this.defaultLeaderboardV2 = defaultLeaderboardV2;
  }


  public GameCenterDetailUpdateRequestDataRelationships defaultGroupLeaderboard(@jakarta.annotation.Nullable GameCenterChallengeCreateRequestDataRelationshipsLeaderboard defaultGroupLeaderboard) {
    this.defaultGroupLeaderboard = defaultGroupLeaderboard;
    return this;
  }

  /**
   * Get defaultGroupLeaderboard
   * @return defaultGroupLeaderboard
   */
  @jakarta.annotation.Nullable
  @JsonProperty(value = JSON_PROPERTY_DEFAULT_GROUP_LEADERBOARD, required = false)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public GameCenterChallengeCreateRequestDataRelationshipsLeaderboard getDefaultGroupLeaderboard() {
    return defaultGroupLeaderboard;
  }


  @JsonProperty(value = JSON_PROPERTY_DEFAULT_GROUP_LEADERBOARD, required = false)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setDefaultGroupLeaderboard(@jakarta.annotation.Nullable GameCenterChallengeCreateRequestDataRelationshipsLeaderboard defaultGroupLeaderboard) {
    this.defaultGroupLeaderboard = defaultGroupLeaderboard;
  }


  public GameCenterDetailUpdateRequestDataRelationships defaultGroupLeaderboardV2(@jakarta.annotation.Nullable GameCenterChallengeCreateRequestDataRelationshipsLeaderboard defaultGroupLeaderboardV2) {
    this.defaultGroupLeaderboardV2 = defaultGroupLeaderboardV2;
    return this;
  }

  /**
   * Get defaultGroupLeaderboardV2
   * @return defaultGroupLeaderboardV2
   */
  @jakarta.annotation.Nullable
  @JsonProperty(value = JSON_PROPERTY_DEFAULT_GROUP_LEADERBOARD_V2, required = false)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public GameCenterChallengeCreateRequestDataRelationshipsLeaderboard getDefaultGroupLeaderboardV2() {
    return defaultGroupLeaderboardV2;
  }


  @JsonProperty(value = JSON_PROPERTY_DEFAULT_GROUP_LEADERBOARD_V2, required = false)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setDefaultGroupLeaderboardV2(@jakarta.annotation.Nullable GameCenterChallengeCreateRequestDataRelationshipsLeaderboard defaultGroupLeaderboardV2) {
    this.defaultGroupLeaderboardV2 = defaultGroupLeaderboardV2;
  }


  /**
   * Return true if this GameCenterDetailUpdateRequest_data_relationships object is equal to o.
   */
  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    GameCenterDetailUpdateRequestDataRelationships gameCenterDetailUpdateRequestDataRelationships = (GameCenterDetailUpdateRequestDataRelationships) o;
    return Objects.equals(this.gameCenterGroup, gameCenterDetailUpdateRequestDataRelationships.gameCenterGroup) &&
        Objects.equals(this.defaultLeaderboard, gameCenterDetailUpdateRequestDataRelationships.defaultLeaderboard) &&
        Objects.equals(this.defaultLeaderboardV2, gameCenterDetailUpdateRequestDataRelationships.defaultLeaderboardV2) &&
        Objects.equals(this.defaultGroupLeaderboard, gameCenterDetailUpdateRequestDataRelationships.defaultGroupLeaderboard) &&
        Objects.equals(this.defaultGroupLeaderboardV2, gameCenterDetailUpdateRequestDataRelationships.defaultGroupLeaderboardV2);
  }

  @Override
  public int hashCode() {
    return Objects.hash(gameCenterGroup, defaultLeaderboard, defaultLeaderboardV2, defaultGroupLeaderboard, defaultGroupLeaderboardV2);
  }

  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class GameCenterDetailUpdateRequestDataRelationships {\n");
    sb.append("    gameCenterGroup: ").append(toIndentedString(gameCenterGroup)).append("\n");
    sb.append("    defaultLeaderboard: ").append(toIndentedString(defaultLeaderboard)).append("\n");
    sb.append("    defaultLeaderboardV2: ").append(toIndentedString(defaultLeaderboardV2)).append("\n");
    sb.append("    defaultGroupLeaderboard: ").append(toIndentedString(defaultGroupLeaderboard)).append("\n");
    sb.append("    defaultGroupLeaderboardV2: ").append(toIndentedString(defaultGroupLeaderboardV2)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

  /**
   * Convert the instance into URL query string.
   *
   * @return URL query string
   */
  public String toUrlQueryString() {
    return toUrlQueryString(null);
  }

  /**
   * Convert the instance into URL query string.
   *
   * @param prefix prefix of the query string
   * @return URL query string
   */
  public String toUrlQueryString(String prefix) {
    String suffix = "";
    String containerSuffix = "";
    String containerPrefix = "";
    if (prefix == null) {
      // style=form, explode=true, e.g. /pet?name=cat&type=manx
      prefix = "";
    } else {
      // deepObject style e.g. /pet?id[name]=cat&id[type]=manx
      prefix = prefix + "[";
      suffix = "]";
      containerSuffix = "]";
      containerPrefix = "[";
    }

    StringJoiner joiner = new StringJoiner("&");

    // add `gameCenterGroup` to the URL query string
    if (getGameCenterGroup() != null) {
      joiner.add(getGameCenterGroup().toUrlQueryString(prefix + "gameCenterGroup" + suffix));
    }

    // add `defaultLeaderboard` to the URL query string
    if (getDefaultLeaderboard() != null) {
      joiner.add(getDefaultLeaderboard().toUrlQueryString(prefix + "defaultLeaderboard" + suffix));
    }

    // add `defaultLeaderboardV2` to the URL query string
    if (getDefaultLeaderboardV2() != null) {
      joiner.add(getDefaultLeaderboardV2().toUrlQueryString(prefix + "defaultLeaderboardV2" + suffix));
    }

    // add `defaultGroupLeaderboard` to the URL query string
    if (getDefaultGroupLeaderboard() != null) {
      joiner.add(getDefaultGroupLeaderboard().toUrlQueryString(prefix + "defaultGroupLeaderboard" + suffix));
    }

    // add `defaultGroupLeaderboardV2` to the URL query string
    if (getDefaultGroupLeaderboardV2() != null) {
      joiner.add(getDefaultGroupLeaderboardV2().toUrlQueryString(prefix + "defaultGroupLeaderboardV2" + suffix));
    }

    return joiner.toString();
  }
}

