/*
 * App Store Connect API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 4.2
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package com.adguard.stores.appstoreconnect.model;

import java.net.URLEncoder;
import java.nio.charset.StandardCharsets;
import java.util.StringJoiner;
import java.util.Objects;
import java.util.Map;
import java.util.HashMap;
import java.util.Locale;
import com.adguard.stores.appstoreconnect.model.GameCenterAchievementReleaseRelationshipsGameCenterDetail;
import com.adguard.stores.appstoreconnect.model.GameCenterAchievementV2RelationshipsGameCenterGroup;
import com.adguard.stores.appstoreconnect.model.GameCenterChallengeRelationshipsLeaderboard;
import com.adguard.stores.appstoreconnect.model.GameCenterChallengeRelationshipsVersions;
import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonTypeName;
import com.fasterxml.jackson.annotation.JsonValue;
import java.util.Arrays;
import com.fasterxml.jackson.annotation.JsonPropertyOrder;


import com.adguard.stores.appstoreconnect.ApiClient;
/**
 * GameCenterChallengeRelationships
 */
@JsonPropertyOrder({
  GameCenterChallengeRelationships.JSON_PROPERTY_GAME_CENTER_DETAIL,
  GameCenterChallengeRelationships.JSON_PROPERTY_GAME_CENTER_GROUP,
  GameCenterChallengeRelationships.JSON_PROPERTY_VERSIONS,
  GameCenterChallengeRelationships.JSON_PROPERTY_LEADERBOARD,
  GameCenterChallengeRelationships.JSON_PROPERTY_LEADERBOARD_V2
})
@jakarta.annotation.Generated(value = "org.openapitools.codegen.languages.JavaClientCodegen", comments = "Generator version: 7.17.0")
public class GameCenterChallengeRelationships {
  public static final String JSON_PROPERTY_GAME_CENTER_DETAIL = "gameCenterDetail";
  @jakarta.annotation.Nullable
  private GameCenterAchievementReleaseRelationshipsGameCenterDetail gameCenterDetail;

  public static final String JSON_PROPERTY_GAME_CENTER_GROUP = "gameCenterGroup";
  @jakarta.annotation.Nullable
  private GameCenterAchievementV2RelationshipsGameCenterGroup gameCenterGroup;

  public static final String JSON_PROPERTY_VERSIONS = "versions";
  @jakarta.annotation.Nullable
  private GameCenterChallengeRelationshipsVersions versions;

  public static final String JSON_PROPERTY_LEADERBOARD = "leaderboard";
  @jakarta.annotation.Nullable
  private GameCenterChallengeRelationshipsLeaderboard leaderboard;

  public static final String JSON_PROPERTY_LEADERBOARD_V2 = "leaderboardV2";
  @jakarta.annotation.Nullable
  private GameCenterChallengeRelationshipsLeaderboard leaderboardV2;

  public GameCenterChallengeRelationships() { 
  }

  public GameCenterChallengeRelationships gameCenterDetail(@jakarta.annotation.Nullable GameCenterAchievementReleaseRelationshipsGameCenterDetail gameCenterDetail) {
    this.gameCenterDetail = gameCenterDetail;
    return this;
  }

  /**
   * Get gameCenterDetail
   * @return gameCenterDetail
   */
  @jakarta.annotation.Nullable
  @JsonProperty(value = JSON_PROPERTY_GAME_CENTER_DETAIL, required = false)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public GameCenterAchievementReleaseRelationshipsGameCenterDetail getGameCenterDetail() {
    return gameCenterDetail;
  }


  @JsonProperty(value = JSON_PROPERTY_GAME_CENTER_DETAIL, required = false)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setGameCenterDetail(@jakarta.annotation.Nullable GameCenterAchievementReleaseRelationshipsGameCenterDetail gameCenterDetail) {
    this.gameCenterDetail = gameCenterDetail;
  }


  public GameCenterChallengeRelationships gameCenterGroup(@jakarta.annotation.Nullable GameCenterAchievementV2RelationshipsGameCenterGroup gameCenterGroup) {
    this.gameCenterGroup = gameCenterGroup;
    return this;
  }

  /**
   * Get gameCenterGroup
   * @return gameCenterGroup
   */
  @jakarta.annotation.Nullable
  @JsonProperty(value = JSON_PROPERTY_GAME_CENTER_GROUP, required = false)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public GameCenterAchievementV2RelationshipsGameCenterGroup getGameCenterGroup() {
    return gameCenterGroup;
  }


  @JsonProperty(value = JSON_PROPERTY_GAME_CENTER_GROUP, required = false)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setGameCenterGroup(@jakarta.annotation.Nullable GameCenterAchievementV2RelationshipsGameCenterGroup gameCenterGroup) {
    this.gameCenterGroup = gameCenterGroup;
  }


  public GameCenterChallengeRelationships versions(@jakarta.annotation.Nullable GameCenterChallengeRelationshipsVersions versions) {
    this.versions = versions;
    return this;
  }

  /**
   * Get versions
   * @return versions
   */
  @jakarta.annotation.Nullable
  @JsonProperty(value = JSON_PROPERTY_VERSIONS, required = false)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public GameCenterChallengeRelationshipsVersions getVersions() {
    return versions;
  }


  @JsonProperty(value = JSON_PROPERTY_VERSIONS, required = false)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setVersions(@jakarta.annotation.Nullable GameCenterChallengeRelationshipsVersions versions) {
    this.versions = versions;
  }


  public GameCenterChallengeRelationships leaderboard(@jakarta.annotation.Nullable GameCenterChallengeRelationshipsLeaderboard leaderboard) {
    this.leaderboard = leaderboard;
    return this;
  }

  /**
   * Get leaderboard
   * @return leaderboard
   */
  @jakarta.annotation.Nullable
  @JsonProperty(value = JSON_PROPERTY_LEADERBOARD, required = false)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public GameCenterChallengeRelationshipsLeaderboard getLeaderboard() {
    return leaderboard;
  }


  @JsonProperty(value = JSON_PROPERTY_LEADERBOARD, required = false)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setLeaderboard(@jakarta.annotation.Nullable GameCenterChallengeRelationshipsLeaderboard leaderboard) {
    this.leaderboard = leaderboard;
  }


  public GameCenterChallengeRelationships leaderboardV2(@jakarta.annotation.Nullable GameCenterChallengeRelationshipsLeaderboard leaderboardV2) {
    this.leaderboardV2 = leaderboardV2;
    return this;
  }

  /**
   * Get leaderboardV2
   * @return leaderboardV2
   */
  @jakarta.annotation.Nullable
  @JsonProperty(value = JSON_PROPERTY_LEADERBOARD_V2, required = false)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public GameCenterChallengeRelationshipsLeaderboard getLeaderboardV2() {
    return leaderboardV2;
  }


  @JsonProperty(value = JSON_PROPERTY_LEADERBOARD_V2, required = false)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setLeaderboardV2(@jakarta.annotation.Nullable GameCenterChallengeRelationshipsLeaderboard leaderboardV2) {
    this.leaderboardV2 = leaderboardV2;
  }


  /**
   * Return true if this GameCenterChallenge_relationships object is equal to o.
   */
  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    GameCenterChallengeRelationships gameCenterChallengeRelationships = (GameCenterChallengeRelationships) o;
    return Objects.equals(this.gameCenterDetail, gameCenterChallengeRelationships.gameCenterDetail) &&
        Objects.equals(this.gameCenterGroup, gameCenterChallengeRelationships.gameCenterGroup) &&
        Objects.equals(this.versions, gameCenterChallengeRelationships.versions) &&
        Objects.equals(this.leaderboard, gameCenterChallengeRelationships.leaderboard) &&
        Objects.equals(this.leaderboardV2, gameCenterChallengeRelationships.leaderboardV2);
  }

  @Override
  public int hashCode() {
    return Objects.hash(gameCenterDetail, gameCenterGroup, versions, leaderboard, leaderboardV2);
  }

  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class GameCenterChallengeRelationships {\n");
    sb.append("    gameCenterDetail: ").append(toIndentedString(gameCenterDetail)).append("\n");
    sb.append("    gameCenterGroup: ").append(toIndentedString(gameCenterGroup)).append("\n");
    sb.append("    versions: ").append(toIndentedString(versions)).append("\n");
    sb.append("    leaderboard: ").append(toIndentedString(leaderboard)).append("\n");
    sb.append("    leaderboardV2: ").append(toIndentedString(leaderboardV2)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

  /**
   * Convert the instance into URL query string.
   *
   * @return URL query string
   */
  public String toUrlQueryString() {
    return toUrlQueryString(null);
  }

  /**
   * Convert the instance into URL query string.
   *
   * @param prefix prefix of the query string
   * @return URL query string
   */
  public String toUrlQueryString(String prefix) {
    String suffix = "";
    String containerSuffix = "";
    String containerPrefix = "";
    if (prefix == null) {
      // style=form, explode=true, e.g. /pet?name=cat&type=manx
      prefix = "";
    } else {
      // deepObject style e.g. /pet?id[name]=cat&id[type]=manx
      prefix = prefix + "[";
      suffix = "]";
      containerSuffix = "]";
      containerPrefix = "[";
    }

    StringJoiner joiner = new StringJoiner("&");

    // add `gameCenterDetail` to the URL query string
    if (getGameCenterDetail() != null) {
      joiner.add(getGameCenterDetail().toUrlQueryString(prefix + "gameCenterDetail" + suffix));
    }

    // add `gameCenterGroup` to the URL query string
    if (getGameCenterGroup() != null) {
      joiner.add(getGameCenterGroup().toUrlQueryString(prefix + "gameCenterGroup" + suffix));
    }

    // add `versions` to the URL query string
    if (getVersions() != null) {
      joiner.add(getVersions().toUrlQueryString(prefix + "versions" + suffix));
    }

    // add `leaderboard` to the URL query string
    if (getLeaderboard() != null) {
      joiner.add(getLeaderboard().toUrlQueryString(prefix + "leaderboard" + suffix));
    }

    // add `leaderboardV2` to the URL query string
    if (getLeaderboardV2() != null) {
      joiner.add(getLeaderboardV2().toUrlQueryString(prefix + "leaderboardV2" + suffix));
    }

    return joiner.toString();
  }
}

