/*
 * App Store Connect API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 4.2
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package com.adguard.stores.appstoreconnect.model;

import java.net.URLEncoder;
import java.nio.charset.StandardCharsets;
import java.util.StringJoiner;
import java.util.Objects;
import java.util.Map;
import java.util.HashMap;
import java.util.Locale;
import com.adguard.stores.appstoreconnect.model.OfferCodeEnvironment;
import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonTypeName;
import com.fasterxml.jackson.annotation.JsonValue;
import java.time.LocalDate;
import java.util.Arrays;
import com.fasterxml.jackson.annotation.JsonPropertyOrder;


import com.adguard.stores.appstoreconnect.ApiClient;
/**
 * InAppPurchaseOfferCodeOneTimeUseCodeCreateRequestDataAttributes
 */
@JsonPropertyOrder({
  InAppPurchaseOfferCodeOneTimeUseCodeCreateRequestDataAttributes.JSON_PROPERTY_NUMBER_OF_CODES,
  InAppPurchaseOfferCodeOneTimeUseCodeCreateRequestDataAttributes.JSON_PROPERTY_EXPIRATION_DATE,
  InAppPurchaseOfferCodeOneTimeUseCodeCreateRequestDataAttributes.JSON_PROPERTY_ENVIRONMENT
})
@jakarta.annotation.Generated(value = "org.openapitools.codegen.languages.JavaClientCodegen", comments = "Generator version: 7.17.0")
public class InAppPurchaseOfferCodeOneTimeUseCodeCreateRequestDataAttributes {
  public static final String JSON_PROPERTY_NUMBER_OF_CODES = "numberOfCodes";
  @jakarta.annotation.Nonnull
  private Integer numberOfCodes;

  public static final String JSON_PROPERTY_EXPIRATION_DATE = "expirationDate";
  @jakarta.annotation.Nonnull
  private LocalDate expirationDate;

  public static final String JSON_PROPERTY_ENVIRONMENT = "environment";
  @jakarta.annotation.Nullable
  private OfferCodeEnvironment environment;

  public InAppPurchaseOfferCodeOneTimeUseCodeCreateRequestDataAttributes() { 
  }

  public InAppPurchaseOfferCodeOneTimeUseCodeCreateRequestDataAttributes numberOfCodes(@jakarta.annotation.Nonnull Integer numberOfCodes) {
    this.numberOfCodes = numberOfCodes;
    return this;
  }

  /**
   * Get numberOfCodes
   * @return numberOfCodes
   */
  @jakarta.annotation.Nonnull
  @JsonProperty(value = JSON_PROPERTY_NUMBER_OF_CODES, required = true)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)
  public Integer getNumberOfCodes() {
    return numberOfCodes;
  }


  @JsonProperty(value = JSON_PROPERTY_NUMBER_OF_CODES, required = true)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)
  public void setNumberOfCodes(@jakarta.annotation.Nonnull Integer numberOfCodes) {
    this.numberOfCodes = numberOfCodes;
  }


  public InAppPurchaseOfferCodeOneTimeUseCodeCreateRequestDataAttributes expirationDate(@jakarta.annotation.Nonnull LocalDate expirationDate) {
    this.expirationDate = expirationDate;
    return this;
  }

  /**
   * Get expirationDate
   * @return expirationDate
   */
  @jakarta.annotation.Nonnull
  @JsonProperty(value = JSON_PROPERTY_EXPIRATION_DATE, required = true)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)
  public LocalDate getExpirationDate() {
    return expirationDate;
  }


  @JsonProperty(value = JSON_PROPERTY_EXPIRATION_DATE, required = true)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)
  public void setExpirationDate(@jakarta.annotation.Nonnull LocalDate expirationDate) {
    this.expirationDate = expirationDate;
  }


  public InAppPurchaseOfferCodeOneTimeUseCodeCreateRequestDataAttributes environment(@jakarta.annotation.Nullable OfferCodeEnvironment environment) {
    this.environment = environment;
    return this;
  }

  /**
   * Get environment
   * @return environment
   */
  @jakarta.annotation.Nullable
  @JsonProperty(value = JSON_PROPERTY_ENVIRONMENT, required = false)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public OfferCodeEnvironment getEnvironment() {
    return environment;
  }


  @JsonProperty(value = JSON_PROPERTY_ENVIRONMENT, required = false)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setEnvironment(@jakarta.annotation.Nullable OfferCodeEnvironment environment) {
    this.environment = environment;
  }


  /**
   * Return true if this InAppPurchaseOfferCodeOneTimeUseCodeCreateRequest_data_attributes object is equal to o.
   */
  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    InAppPurchaseOfferCodeOneTimeUseCodeCreateRequestDataAttributes inAppPurchaseOfferCodeOneTimeUseCodeCreateRequestDataAttributes = (InAppPurchaseOfferCodeOneTimeUseCodeCreateRequestDataAttributes) o;
    return Objects.equals(this.numberOfCodes, inAppPurchaseOfferCodeOneTimeUseCodeCreateRequestDataAttributes.numberOfCodes) &&
        Objects.equals(this.expirationDate, inAppPurchaseOfferCodeOneTimeUseCodeCreateRequestDataAttributes.expirationDate) &&
        Objects.equals(this.environment, inAppPurchaseOfferCodeOneTimeUseCodeCreateRequestDataAttributes.environment);
  }

  @Override
  public int hashCode() {
    return Objects.hash(numberOfCodes, expirationDate, environment);
  }

  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class InAppPurchaseOfferCodeOneTimeUseCodeCreateRequestDataAttributes {\n");
    sb.append("    numberOfCodes: ").append(toIndentedString(numberOfCodes)).append("\n");
    sb.append("    expirationDate: ").append(toIndentedString(expirationDate)).append("\n");
    sb.append("    environment: ").append(toIndentedString(environment)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

  /**
   * Convert the instance into URL query string.
   *
   * @return URL query string
   */
  public String toUrlQueryString() {
    return toUrlQueryString(null);
  }

  /**
   * Convert the instance into URL query string.
   *
   * @param prefix prefix of the query string
   * @return URL query string
   */
  public String toUrlQueryString(String prefix) {
    String suffix = "";
    String containerSuffix = "";
    String containerPrefix = "";
    if (prefix == null) {
      // style=form, explode=true, e.g. /pet?name=cat&type=manx
      prefix = "";
    } else {
      // deepObject style e.g. /pet?id[name]=cat&id[type]=manx
      prefix = prefix + "[";
      suffix = "]";
      containerSuffix = "]";
      containerPrefix = "[";
    }

    StringJoiner joiner = new StringJoiner("&");

    // add `numberOfCodes` to the URL query string
    if (getNumberOfCodes() != null) {
      joiner.add(String.format(Locale.ROOT, "%snumberOfCodes%s=%s", prefix, suffix, ApiClient.urlEncode(ApiClient.valueToString(getNumberOfCodes()))));
    }

    // add `expirationDate` to the URL query string
    if (getExpirationDate() != null) {
      joiner.add(String.format(Locale.ROOT, "%sexpirationDate%s=%s", prefix, suffix, ApiClient.urlEncode(ApiClient.valueToString(getExpirationDate()))));
    }

    // add `environment` to the URL query string
    if (getEnvironment() != null) {
      joiner.add(String.format(Locale.ROOT, "%senvironment%s=%s", prefix, suffix, ApiClient.urlEncode(ApiClient.valueToString(getEnvironment()))));
    }

    return joiner.toString();
  }
}

