/*
 * App Store Connect API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 4.2
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package com.adguard.stores.appstoreconnect.model;

import java.net.URLEncoder;
import java.nio.charset.StandardCharsets;
import java.util.StringJoiner;
import java.util.Objects;
import java.util.Map;
import java.util.HashMap;
import java.util.Locale;
import com.adguard.stores.appstoreconnect.model.AlternativeDistributionKeyCreateRequestDataRelationshipsApp;
import com.adguard.stores.appstoreconnect.model.AnalyticsReportInstanceRelationshipsSegments;
import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonTypeName;
import com.fasterxml.jackson.annotation.JsonValue;
import java.util.Arrays;
import com.fasterxml.jackson.annotation.JsonPropertyOrder;


import com.adguard.stores.appstoreconnect.ApiClient;
/**
 * WebhookRelationships
 */
@JsonPropertyOrder({
  WebhookRelationships.JSON_PROPERTY_APP,
  WebhookRelationships.JSON_PROPERTY_DELIVERIES
})
@jakarta.annotation.Generated(value = "org.openapitools.codegen.languages.JavaClientCodegen", comments = "Generator version: 7.17.0")
public class WebhookRelationships {
  public static final String JSON_PROPERTY_APP = "app";
  @jakarta.annotation.Nullable
  private AlternativeDistributionKeyCreateRequestDataRelationshipsApp app;

  public static final String JSON_PROPERTY_DELIVERIES = "deliveries";
  @jakarta.annotation.Nullable
  private AnalyticsReportInstanceRelationshipsSegments deliveries;

  public WebhookRelationships() { 
  }

  public WebhookRelationships app(@jakarta.annotation.Nullable AlternativeDistributionKeyCreateRequestDataRelationshipsApp app) {
    this.app = app;
    return this;
  }

  /**
   * Get app
   * @return app
   */
  @jakarta.annotation.Nullable
  @JsonProperty(value = JSON_PROPERTY_APP, required = false)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public AlternativeDistributionKeyCreateRequestDataRelationshipsApp getApp() {
    return app;
  }


  @JsonProperty(value = JSON_PROPERTY_APP, required = false)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setApp(@jakarta.annotation.Nullable AlternativeDistributionKeyCreateRequestDataRelationshipsApp app) {
    this.app = app;
  }


  public WebhookRelationships deliveries(@jakarta.annotation.Nullable AnalyticsReportInstanceRelationshipsSegments deliveries) {
    this.deliveries = deliveries;
    return this;
  }

  /**
   * Get deliveries
   * @return deliveries
   */
  @jakarta.annotation.Nullable
  @JsonProperty(value = JSON_PROPERTY_DELIVERIES, required = false)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public AnalyticsReportInstanceRelationshipsSegments getDeliveries() {
    return deliveries;
  }


  @JsonProperty(value = JSON_PROPERTY_DELIVERIES, required = false)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setDeliveries(@jakarta.annotation.Nullable AnalyticsReportInstanceRelationshipsSegments deliveries) {
    this.deliveries = deliveries;
  }


  /**
   * Return true if this Webhook_relationships object is equal to o.
   */
  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    WebhookRelationships webhookRelationships = (WebhookRelationships) o;
    return Objects.equals(this.app, webhookRelationships.app) &&
        Objects.equals(this.deliveries, webhookRelationships.deliveries);
  }

  @Override
  public int hashCode() {
    return Objects.hash(app, deliveries);
  }

  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class WebhookRelationships {\n");
    sb.append("    app: ").append(toIndentedString(app)).append("\n");
    sb.append("    deliveries: ").append(toIndentedString(deliveries)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

  /**
   * Convert the instance into URL query string.
   *
   * @return URL query string
   */
  public String toUrlQueryString() {
    return toUrlQueryString(null);
  }

  /**
   * Convert the instance into URL query string.
   *
   * @param prefix prefix of the query string
   * @return URL query string
   */
  public String toUrlQueryString(String prefix) {
    String suffix = "";
    String containerSuffix = "";
    String containerPrefix = "";
    if (prefix == null) {
      // style=form, explode=true, e.g. /pet?name=cat&type=manx
      prefix = "";
    } else {
      // deepObject style e.g. /pet?id[name]=cat&id[type]=manx
      prefix = prefix + "[";
      suffix = "]";
      containerSuffix = "]";
      containerPrefix = "[";
    }

    StringJoiner joiner = new StringJoiner("&");

    // add `app` to the URL query string
    if (getApp() != null) {
      joiner.add(getApp().toUrlQueryString(prefix + "app" + suffix));
    }

    // add `deliveries` to the URL query string
    if (getDeliveries() != null) {
      joiner.add(getDeliveries().toUrlQueryString(prefix + "deliveries" + suffix));
    }

    return joiner.toString();
  }
}

