/*
 * App Store Connect API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 4.2
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package com.adguard.stores.appstoreconnect.model;

import java.net.URLEncoder;
import java.nio.charset.StandardCharsets;
import java.util.StringJoiner;
import java.util.Objects;
import java.util.Map;
import java.util.HashMap;
import java.util.Locale;
import com.adguard.stores.appstoreconnect.model.XcodeMetricsInsights;
import com.adguard.stores.appstoreconnect.model.XcodeMetricsProductDataInner;
import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonTypeName;
import com.fasterxml.jackson.annotation.JsonValue;
import java.util.ArrayList;
import java.util.Arrays;
import java.util.List;
import com.fasterxml.jackson.annotation.JsonPropertyOrder;


import com.adguard.stores.appstoreconnect.ApiClient;
/**
 * XcodeMetrics
 */
@JsonPropertyOrder({
  XcodeMetrics.JSON_PROPERTY_VERSION,
  XcodeMetrics.JSON_PROPERTY_INSIGHTS,
  XcodeMetrics.JSON_PROPERTY_PRODUCT_DATA
})
@jakarta.annotation.Generated(value = "org.openapitools.codegen.languages.JavaClientCodegen", comments = "Generator version: 7.17.0")
public class XcodeMetrics {
  public static final String JSON_PROPERTY_VERSION = "version";
  @jakarta.annotation.Nullable
  private String version;

  public static final String JSON_PROPERTY_INSIGHTS = "insights";
  @jakarta.annotation.Nullable
  private XcodeMetricsInsights insights;

  public static final String JSON_PROPERTY_PRODUCT_DATA = "productData";
  @jakarta.annotation.Nullable
  private List<XcodeMetricsProductDataInner> productData = new ArrayList<>();

  public XcodeMetrics() { 
  }

  public XcodeMetrics version(@jakarta.annotation.Nullable String version) {
    this.version = version;
    return this;
  }

  /**
   * Get version
   * @return version
   */
  @jakarta.annotation.Nullable
  @JsonProperty(value = JSON_PROPERTY_VERSION, required = false)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public String getVersion() {
    return version;
  }


  @JsonProperty(value = JSON_PROPERTY_VERSION, required = false)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setVersion(@jakarta.annotation.Nullable String version) {
    this.version = version;
  }


  public XcodeMetrics insights(@jakarta.annotation.Nullable XcodeMetricsInsights insights) {
    this.insights = insights;
    return this;
  }

  /**
   * Get insights
   * @return insights
   */
  @jakarta.annotation.Nullable
  @JsonProperty(value = JSON_PROPERTY_INSIGHTS, required = false)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public XcodeMetricsInsights getInsights() {
    return insights;
  }


  @JsonProperty(value = JSON_PROPERTY_INSIGHTS, required = false)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setInsights(@jakarta.annotation.Nullable XcodeMetricsInsights insights) {
    this.insights = insights;
  }


  public XcodeMetrics productData(@jakarta.annotation.Nullable List<XcodeMetricsProductDataInner> productData) {
    this.productData = productData;
    return this;
  }

  public XcodeMetrics addProductDataItem(XcodeMetricsProductDataInner productDataItem) {
    if (this.productData == null) {
      this.productData = new ArrayList<>();
    }
    this.productData.add(productDataItem);
    return this;
  }

  /**
   * Get productData
   * @return productData
   */
  @jakarta.annotation.Nullable
  @JsonProperty(value = JSON_PROPERTY_PRODUCT_DATA, required = false)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public List<XcodeMetricsProductDataInner> getProductData() {
    return productData;
  }


  @JsonProperty(value = JSON_PROPERTY_PRODUCT_DATA, required = false)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setProductData(@jakarta.annotation.Nullable List<XcodeMetricsProductDataInner> productData) {
    this.productData = productData;
  }


  /**
   * Return true if this xcodeMetrics object is equal to o.
   */
  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    XcodeMetrics xcodeMetrics = (XcodeMetrics) o;
    return Objects.equals(this.version, xcodeMetrics.version) &&
        Objects.equals(this.insights, xcodeMetrics.insights) &&
        Objects.equals(this.productData, xcodeMetrics.productData);
  }

  @Override
  public int hashCode() {
    return Objects.hash(version, insights, productData);
  }

  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class XcodeMetrics {\n");
    sb.append("    version: ").append(toIndentedString(version)).append("\n");
    sb.append("    insights: ").append(toIndentedString(insights)).append("\n");
    sb.append("    productData: ").append(toIndentedString(productData)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

  /**
   * Convert the instance into URL query string.
   *
   * @return URL query string
   */
  public String toUrlQueryString() {
    return toUrlQueryString(null);
  }

  /**
   * Convert the instance into URL query string.
   *
   * @param prefix prefix of the query string
   * @return URL query string
   */
  public String toUrlQueryString(String prefix) {
    String suffix = "";
    String containerSuffix = "";
    String containerPrefix = "";
    if (prefix == null) {
      // style=form, explode=true, e.g. /pet?name=cat&type=manx
      prefix = "";
    } else {
      // deepObject style e.g. /pet?id[name]=cat&id[type]=manx
      prefix = prefix + "[";
      suffix = "]";
      containerSuffix = "]";
      containerPrefix = "[";
    }

    StringJoiner joiner = new StringJoiner("&");

    // add `version` to the URL query string
    if (getVersion() != null) {
      joiner.add(String.format(Locale.ROOT, "%sversion%s=%s", prefix, suffix, ApiClient.urlEncode(ApiClient.valueToString(getVersion()))));
    }

    // add `insights` to the URL query string
    if (getInsights() != null) {
      joiner.add(getInsights().toUrlQueryString(prefix + "insights" + suffix));
    }

    // add `productData` to the URL query string
    if (getProductData() != null) {
      for (int i = 0; i < getProductData().size(); i++) {
        if (getProductData().get(i) != null) {
          joiner.add(getProductData().get(i).toUrlQueryString(String.format(Locale.ROOT, "%sproductData%s%s", prefix, suffix,
          "".equals(suffix) ? "" : String.format(Locale.ROOT, "%s%d%s", containerPrefix, i, containerSuffix))));
        }
      }
    }

    return joiner.toString();
  }
}

